### ISSUE TITLE
Year Progressions, only show 2 years

### ISSUE THREAD

**Issue by lukasc-ubc** [thomaschampagne/elevate#1002]
previously, Elevate would show multiple years in Year Progressions, and there was a way to turn on and off different years.  This disappeared for me

![image](https://user-images.githubusercontent.com/15843200/96938583-9d749f00-147f-11eb-8c78-a6e12754769d.png)

You can see it only shows 2 years.

Yet, I do have data from the past 5 years:
![image](https://user-images.githubusercontent.com/15843200/96938623-b4b38c80-147f-11eb-83fa-5fb6970e6f33.png)

I am running
Plugin version: 6.16.2 Stable
Angular Core version: 8.2.14
Angular Material version: 8.2.3
D3js version: 5.16.0
You are running the latest version
Chrome, Mac OS 10.15.7

thank you

**Comment by thomaschampagne** [comment]
Just open the window wider ;)
