### ISSUE TITLE
My query is about activity selection and how this choice impacts on Kms accumulated towards monthly trophies. I very recently purchased an racing pedal assist type-bike due to problems I am now having with my heart beating too fast when climbing steep gradients. I still want to bike up hills but not have the worry about having what I think is atrial fibrillation occurring. I have learnt how I feel just prior to it happening (shortness of breath and light headiness) but get frustrated having to stop to get my heart rate down. However, after taking my new e-bike for a ride I was a bit frustrated that the Vertical Meters climbed and kms ridden didn't get included in my signed up challenges for December. I'm not trying to compete in Strava segment times when riding on my e-bike. However I would have thought I should be allowed to included them in my personal signed up cycling challenges. 

### ISSUE THREAD

**Issue by KMW10** [thomaschampagne/elevate#1015]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
The issue do not respect the description rules. 

If still an issue please reopen and edit this issue (do not create new one)

Thanks
