### ISSUE TITLE
Strava import stuck on 400 activities

### ISSUE THREAD

**Issue by unixworker** [thomaschampagne/elevate#1023]
### Step 2: Describe your environment
Plugin version: 6.16.2 Stable
Angular Core version: 8.2.14
Angular Material version: 8.2.3
D3js version: 5.16.0
Chrome Version 87.0.4280.88 (Official Build) (64-bit)
Manjaro, newest Version.

  
### Step 3: Describe the problem:
First import from Strava not working.
Activities found 1585
Sync works up to around 400. Trying for three days to import all activities.
Pressing F5 to refresh the window starts again from zero telling me to wait for 4-5h.

Any ideas on how to make it work?

**Comment by monzarun** [comment]
Same here.
Everything worked fine in the past
Then I had to resync to include some changes and in my case sync up to 980 Activities (54%)

**Comment by thomaschampagne** [comment]
I know how annoying this is. As written in the message you should have seen, it's a limitation Strava put in their server. You have to sync after every 4 hours if sync started from scratch.

The future of this project is the desktop app not the plugin limited especially by this issue.

Drop me a mail if you want to test the desktop app in alpha: th.champagne (gmail)
