### ISSUE TITLE
[Minor] App opens small since v7.0.0-4.alpha

### ISSUE THREAD

**Issue by AplysiaSeaHare** [thomaschampagne/elevate#1027]
* Plugin version: v7.0.0-4.alpha
  * OS version: Windows 10
  
### Step 3: Describe the problem:

Since the latest update, when I open the program, it opens as a very small window that I need to increase the size of to use. Upon restart, the program always starts very small.

#### Steps to reproduce:

  1. Double click on the app to open it
  
#### Actual Behavior:

  * What happened? Very small window size
  * Do you have javascript errors logs in browser console? No error
  
#### Expected Behavior:

  * What did you expect to happen?
  Open bigger, so that I do not need to resize every time. Ideally it should remember the latest size.

This is the size it opens :
![Capture](https://user-images.githubusercontent.com/78860209/107518874-5f9da280-6b64-11eb-99c2-8fc4a80fb8b7.JPG)

#### Media attachement:

![Capture](https://user-images.githubusercontent.com/78860209/107518874-5f9da280-6b64-11eb-99c2-8fc4a80fb8b7.JPG)

**Comment by thomaschampagne** [comment]
This should have been fixed in 7.0.0-5.alpha do you confirm?

**Comment by AplysiaSeaHare** [comment]
Yes. I can confirm that now everything works fine.
