### ISSUE TITLE
Display extended statistics is Not showing in Strava

### ISSUE THREAD

**Issue by daveschoovaerts** [thomaschampagne/elevate#1030]
### Step 1: Are you in the right place?

Hallo,

I installed the Elevate Chrome Extension today. I’m really stunned when I see the capabilities of the application. Also my 600 activities were synced fluently in 2 times.

All day I’ve tried to find a solution for the one thing I can’t find. The button “show extended statistics’ does not appear in my strava page.

I downloaded the latest plugin on your website and tried it on 2 pc’s. On google chrome and opera. In none of the 4 cases the button appears.

I ran out of ideas. Any ideas what is causing this,

kind regards

dave

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
Do you have activity links where issue occurs? (must be public accessible)

**Comment by daveschoovaerts** [comment]
Hi Thomas,

Merci pour ta réponse. 

Quelques liens:
1) https://www.strava.com/activities/4822966531
2) https://www.strava.com/activities/4831195466
3) https://www.strava.com/activities/4851534902

J'en ai plus si tu veux. 

Ce qui est bizarre est qu'en bas toutes les calculations apparaissent graçe à ton développement...(voir photo)
https://user-images.githubusercontent.com/79763575/109401662-36488900-7950-11eb-8073-e0fbbdb3399b.png

Mais en haut je ne trouve pas le bouton pour les statistiques détaillées.(photo en bas)

![image](https://user-images.githubusercontent.com/79763575/109401704-642dcd80-7950-11eb-832d-940796882b17.png)

J'ai regardé par tout sur internet mais nul part trouvé un aide ou une réponse, ou même le même problème. Comme je l'ai sur deux PC différents et en plus dans deux navigateurs ne voyais pas d'autre manière que de demander de l'aide.

Déjà un très grand merci pour ta réponse.
Un grand fan de plus.
Bàt,
Dave

**Comment by thomaschampagne** [comment]
étrange cela marche chez moi:

![image](https://user-images.githubusercontent.com/151973/109401941-187c2380-7952-11eb-9654-9ca1afcd8d5e.png)

- Quelles erreurs as tu dans la console (touche F12, puis F5)

Thomas

**Comment by daveschoovaerts** [comment]
[image: image.png]

Op za 27 feb. 2021 om 23:19 schreef Thomas Champagne <
notifications@github.com>:

**Comment by daveschoovaerts** [comment]
Thomas,

J'ai de nouveau synchronisé... Maintenant le bouton est la.

Mes excuses pour l'inconvénient. Cela semble maintenant de fonctionner.

Un grand merci pour ton aide.

Bat,

Dave

Op za 27 feb. 2021 23:19 schreef Thomas Champagne <notifications@github.com

**Comment by thomaschampagne** [comment]
Il y a t'il des erreurs dans la console? Touche F12 ou ctrl+shift+i ?
