### ISSUE TITLE
Download the desktop app

### ISSUE THREAD

**Issue by lordvalium** [thomaschampagne/elevate#1031]
Hi, i just saw the info in my browser extension, that there is a desktop app. 
Can somebody tell me the place?
I cant find it
Thx

**Comment by thomaschampagne** [comment]
Hi it's still a closed alpha at the moment. Drop you email and os for testing

**Comment by lordvalium** [comment]
@thomaschampagne detailversessen at gmail.com

Would be nice thx. I can give back alpha feedback and issues i find ok? 

Best

**Comment by thomaschampagne** [comment]
Added for next release ;)
