### ISSUE TITLE
Desktop version 

### ISSUE THREAD

**Issue by SKOHscripts** [thomaschampagne/elevate#1032]
Good morning (from France),
I just discovered that there was a closed alpha desktop version. Is it possible to download it for Linux (Ubuntu)? 
By the way, I'm really exited about the new features developed. Very good job. 

Best regards, 
S+KOH

**Comment by thomaschampagne** [comment]
There's no linux closed alpha build to be shipped at the moment. Btw it's works under linux:

![image](https://user-images.githubusercontent.com/151973/109419725-2fad2680-79cf-11eb-905a-431648251f41.png)

**Comment by guifrecuni** [comment]
Here another Linux user that will be happy to try it as soon as there is an alpha/beta version available.
Currently I'm really enjoying the Chrome extension.

**Comment by SKOHscripts** [comment]
I also really enjoy the chrome extension. I am just really interested in deleting my Strava account because of privacy issues. And the desktop version would allow me to only have local storage of my routes. 
By the way, excellent job!!

**Comment by SKOHscripts** [comment]
Any news about a possible linux alpha version ? :)
