### ISSUE TITLE
Problems restoring activities

### ISSUE THREAD

**Issue by A1Dan75** [thomaschampagne/elevate#1034]
Plugin version: 6.16.3 Stable
Angular Core version: 8.2.14
Angular Material version: 8.2.3
D3js version: 5.16.0

Chrome Version 88.0.4324.190
Windows 10

Hi, 

I opened Elevate yesterday, and all of my activities had disappeared.  I can only think this must have been linked to the fact I logged into a different Strava account on my laptop, but despite being logged back into my own there were no activities... is that expected behaviour?

Anyway, I tried doing a full re-sync, but it only managed a couple of hundred records before telling me I'd used my quota and I'd have to wait 5 or 6 hours.  Given that I have around 2,000 activities, this isn't ideal.

So I tried restoring the last backup I took, which unfortunately was from last August, but does have all but around 200 of my activities in it.  That worked OK, but then when I tried to do Sync Recent Activities, it brought in the last few weeks, but deleted all the earlier ones.  Again, not sure if that's how it's meant to work?

I'm at a bit of a loss as to how to get all my activities back in now... any advice?

Thanks

Aidan

**Comment by 4262mikeb** [comment]
Same experience here. ~2400 activities, restored from oldish backup which would have a few 100 activities missing, but then the sync wipes them out. Currently reloading with 4-5 hour intervals.

**Comment by nwmurray** [comment]
I'm having repeted issues with synced ativities disappearing. I've taken backups once thy have synced finally, but now the backups wont resore.  Not going throught the week long full sync again, so sorry, but app is unusable.

**Comment by patmagauran** [comment]
Also having similar issues.

**Comment by s-kem** [comment]
This bug's been around for awhile. Seems that whenever you try and sync recent when you haven't synced after a certain threshold of time, it's not treated as a sync that merges existing w/ new, but instead deletes all existing and replaces them with the recents.

I've seen a couple GH Issues pop up for this problem & they've been closed due to inactivity.
