### ISSUE TITLE
Extended Segment Statistics Button Not Showing

### ISSUE THREAD

**Issue by shaunginsbourg** [thomaschampagne/elevate#1036]
### Step 2: Describe your environment

  * Plugin version: _____6.13.6
  * Chrome/Opera/Chromium version: _____89.0.4389.82
  * OS version: _____Windows 10 Pro 20H2 19042.804
  
### Step 3: Describe the problem:

When I expand a segment, the red button labelled Show Extended Statistics of this Effort does not appear

#### Steps to reproduce:

  1. _____Go to (cycling) activity
  2. _____Click on a segment in the Segment Efforts lists
  3. _____
  
#### Actual Behavior:

[www.strava.com-1615264659427.log](https://github.com/thomaschampagne/elevate/files/6105884/www.strava.com-1615264659427.log)
Button did not appear
  
#### Expected Behavior:
The button to appear
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by Myshor** [comment]
Same behavior with newest version - 6.16.4.
Button dissapeared and not showing on single activity page.

**Comment by ldrkKps** [comment]
More or less the same issue. Extended stats showing on bike activities – but they disappeared on running activities 2 days ago.

elevate 6.16.4
chrome Version 89.0.4389.82 (Official Build) (x86_64)
macos 10.13.6

**Comment by ldrkKps** [comment]
Problem solved in the new version 6.16.5

Thanks a lot - Keep the good work up!
