### ISSUE TITLE
Segment time comparison keeps loading

### ISSUE THREAD

**Issue by DavidScheers** [thomaschampagne/elevate#1038]
### Step 2: Describe your environment

  * Plugin version: 6.16.5 Stable
  * Chrome/Opera/Chromium version: Chromium 89.0
  * OS version: Pop!_Os 20.10 
  
### Step 3: Describe the problem:
Segment time comparison keeps loading (spinning), both for KOM and PR

#### Steps to reproduce:
Open any strava activity

  
#### Actual Behavior:
Spinning loaders

  
#### Expected Behavior:

  * Able to see segment time comparison
  
#### Media attachement:

>You can upload/attach any images to this ticket.
![Elevate_Bug](https://user-images.githubusercontent.com/11273503/112284995-20e22880-8c8a-11eb-8c6f-076464de017a.png)

**Comment by steve78b** [comment]
I am getting exactly the same 
Chrome 91
Elevate 6.16.6
