### ISSUE TITLE
I can't run Elevate..? Machineid or authorization?

### ISSUE THREAD

**Issue by cameronmehl** [thomaschampagne/elevate#1040]
Environment:
MacBook Pro M1
Elevate 7.0.0.6-alpha
  
Problem: 
Open Elevate-7.0.0-6.alpha-universal.dmg, drag Elevate to applications folder, right click on app, open, then get this window... 
<img width="1336" alt="Screen Shot 2021-03-28 at 1 01 06 PM" src="https://user-images.githubusercontent.com/50921538/112760611-ae44b600-8fc5-11eb-8ab5-0adbebc8ddd2.png">

Internet is working.
Firewall is off. No proxy set up.
Newest version of Elevate, right?

I came up pretty empty handed with a google search and must be missing something. Any help much appreciated.

**Comment by thomaschampagne** [comment]
Hi,

It's normal. It's an alpha closed testing version. Just drop me an email. I put you in the loop and grant you the access ;)

Thomas

**Comment by cameronmehl** [comment]
Oh, okay great. Thanks for the reply - just emailed you.
