### ISSUE TITLE
CYCLING

### ISSUE THREAD

**Issue by monzarun** [thomaschampagne/elevate#1043]
### Step 2: Describe your environment

  * Plugin version:Plugin version: 6.16.5 Stable
Angular Core version: 8.2.14
Angular Material version: 8.2.3
D3js version: 5.16.0
  * Chrome/Opera/Chromium version: _Version 88.0.4324.182 (Official Build) (64-bit)
  * OS version: _____
  
### Step 3: Describe the problem:
The Fitness Trend Graph doesn't take in consideration Riding activities (I can see th dot in the graph but no effect on the three lines)

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
It's a common issue. You probably have missing thresholds in athlete settings. No stress score can be calculated.

If no HRM or power on activities ensure you have estimated power inside strava activities.
