### ISSUE TITLE
Proposition de traduction

### ISSUE THREAD

**Issue by RenaudPERRAI** [thomaschampagne/elevate#1044]
Bonjour @thomaschampagne,

Je viens de faire un fork de ton super application. Bravo pour tout le travail accompli.
Si ça te convient, je vais me lancer dans la traduction de l'application en français.
J'avais dans l'idée d'utiliser ngx-translate pour faciliter le travail des autres traducteurs et ne pas détruire tout le travail déjà réalisé.
Je pensais directement le faire sur ta branche 7.0.0 web et desktop.
En attendant, je vais m'amuser avec ma version locale ;)

**Comment by thomaschampagne** [comment]
Salut @RenaudPERRAI,

Merci pour ta proposition, c'est super cool de ta part !! Ce serait génial d'avoir les traductions dans l'app. 

Mais je te previens il s'agit d'un gros boulot!! ;)

Je te conseil de regarder autour de la solution officielle de angular `@angular/localize` apparue dans la v9: https://angular.io/guide/i18n. Le format officiel de traduction xliff est supporté. Je l'ai déjà intégré dans un projet au boulot.

Merci à toi!

Thomas

**Comment by RenaudPERRAI** [comment]
Je me doute que ce soit un gros travail, j'avancerai au fur et à mesure :)
Une fois que les modules de traduction seront fonctionnels, je ferai un premier push.
Ensuite, je ferai page par page ;)

**Comment by thomaschampagne** [comment]
Hésites pas si tu veux que je te guide dans l'existant pour avoir un pied à l'étrier ;)

**Comment by RenaudPERRAI** [comment]
Je viens de faire un push.
Je n'arrive pas à comprendre pourquoi le fichier de traduction n'est pas pris en compte dans le build :(

**Comment by thomaschampagne** [comment]
Il faut que je te genere une "base" de démarrage dans une branche dédiée je pense comme je l'ai deja fait sur un autre projet. Je pourrais pas faire ça avant plusieurs jours par contre

**Comment by RenaudPERRAI** [comment]
Je viens de réussir à traduire des bouts de code :)
Je vais créer une branche depuis la 7.0.0 pour suivre plus facilement les développements.
J'utilise ngx-translate qui est plus puissant que le module interne Angular avec la génération de fichier .po pour la traduction.
On en discute à l'occasion ;)

**Comment by RenaudPERRAI** [comment]
Si tu veux tester rapidement : https://github.com/RenaudPERRAI/elevate.git
J'ai modifié directement la branche 7.0.0
Il faut juste modifier dans app.component : translate.use('fr');

Par contre, j'ai une erreur de compilation dans la phase de test à cause du pipe translate qui n'est pas importé par shared.module. Ce sera à vérifier ;)
