### ISSUE TITLE
Feature request: Display more than 15 activities at once

### ISSUE THREAD

**Issue by AplysiaSeaHare** [thomaschampagne/elevate#1047]
### Step 1: Are you in the right place?

I checked and I could not find this feature request anywhere

### Step 2: Describe your environment

  * Stand alone app version: Version 7.0.0-11.alpha / Build 20210413.74220ba3
  * OS version: Windows 10
  
### Step 3: Describe the problem:

On the "activities" section you can select how many activities you can see at once. The choices are 5, 10, or 15. If you have a 40+ inches screen, even 15 entries are too few. It would be great to have options like "50" and/or "infinite scrolling" instead of pagination.

#### Steps to reproduce:

  1. Open app
  2. Click on "Activities"
  
#### Actual Behavior:

  * What happened?
  15 activities are displayed at once. There is no option to see more of them at once.
  * Do you have javascript errors logs in browser console?
  No
  
#### Expected Behavior:

Ability to see more than 15 activities at once.
  
#### Media attachement:
![Capture](https://user-images.githubusercontent.com/78860209/114708608-6e2d4500-9ce0-11eb-9368-37f40757ded9.JPG)

>You can upload/attach any images to this ticket.

Attached
![Capture](https://user-images.githubusercontent.com/78860209/114708649-7a190700-9ce0-11eb-8a1b-de570e94ad05.JPG)

**Comment by thomaschampagne** [comment]
I added 30 & 50 option size ;)

**Comment by AplysiaSeaHare** [comment]
Oh wow. Fulfilled the request even before i filled the feature request.

I am very impressed!

  Marco

**Comment by thomaschampagne** [comment]
Easy stuff ;)
