### ISSUE TITLE
All of Synced Data Disappears every 2-3 months

### ISSUE THREAD

**Issue by mattlaufer** [thomaschampagne/elevate#1069]
### Step 1: Are you in the right place?

I hope I'm in the right place!

### Step 2: Describe your environment

  * Plugin version: 6.16.6
  * Chrome/Opera/Chromium version: 92.0.4515.131
  * OS version: Mac OS 10.15.7
  
#### Steps to reproduce:

  1. Open elevate

  
#### Actual Behavior:

There are no synced activities
  
#### Expected Behavior:

I expected all my data to be there.
  
#### Media attachment:

Not applicable.

**Comment by schlikkes** [comment]
I notice a related behavoir:
I use Elevate not this often but I have more than 3000 rides on STRAVA. The initial replication takes quite a while. 
But when I come back to Elevate after several days (3-4 weeks) it shows that the last sync is quite a time ago and still shows all my 3000 rides. But after 1-2 minuntes my new rides appear but without my histoy, so only the last 20 rides. So I again need to replicate all the data.

**Comment by podistajp** [comment]
same problem here, but with chrome extension
after some time ( one month or so), alle data have disappeared and a full new sync of all data is necessary, which takes forever ... some 4000 activities by now
Where are the data supposed to be stored ? What file ? What folder ?
Knowing this would perhaps help us to find the origin of the problem ( why does this file disappear e.g.? )

**Comment by clclaxman** [comment]
Chrome extension - same issue.   Do have a 3 mth old back up, but the system fails to re-sync anything since then too so you have to run full sync

**Comment by JMA1972** [comment]
I have the same problem when I don't use my browser for a month. Even when I restore my activities from a backup and the last activity in the backup is more than a month old, all these activities will be deleted when the next automatic sync is executed or when I choose "Sync recent activities".

**Comment by jsstefanko** [comment]
I have the same problem. All of my synced data disappeared and I had to do a full new sync. It happened again, and I lost my athlete settings.

**Comment by ZhivkoDelchev** [comment]
Same issue here. All data just disappears at some point and only new activities are sync unless a full sync is made again.
Using the extension in brave.

**Comment by john-haugland** [comment]
same problem here.
