### ISSUE TITLE
I cannot sync my strava activities with elevate chrome extension. I have more than 1200 activities and it stops at around 400. I get the message to try 4 hours later, but it starts all over from the beginning. how can I solve this?

### ISSUE THREAD

**Issue by icamacho78** [thomaschampagne/elevate#1080]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by sjclark76** [comment]
I also have the same issue. I am trying to do an initial sync but have over 1800 activities. 1600 activities have been loaded but the remaining 200 fail because  the tools stops with the message to try again in 4 hours.

I have tried repeatedly but no more activities get loaded.

**Comment by thomaschampagne** [comment]
This is not an issue. It's strava behaviour unfortunatly... This is why I build a new desktop app for 3 years.

You can install the desktop beta version from here: https://thomaschampagne.github.io/elevate-docs/
