### ISSUE TITLE
Elevate API certificate issues

### ISSUE THREAD

**Issue by drieshooghe** [thomaschampagne/elevate#1084]
### Step 1: Are you in the right place?

  /

### Step 2: Describe your environment

  * Plugin version: Desktop Alpha 7.0.0-13.alpha
  * OS version: MacOS Monterey 12.1
  
### Step 3: Describe the problem:

Application can't fetch data from the Elevate API, even though my machine ID has been granted access and it worked in the past. Probably caused by issues with the SSL certificate of the API

![Screenshot 2022-02-16 at 08 39 49](https://user-images.githubusercontent.com/25033847/154218323-05322b1f-1571-440f-ad66-ed7d442cd3b6.jpg)

**Developer console**
  ```javascript
POST https://api.elevate.duckdns.org/api/athlete/access net::ERR_CERT_REVOKED
  ```

**Certificate information**
![Screenshot 2022-02-16 at 08 44 15](https://user-images.githubusercontent.com/25033847/154218845-86c7423b-12ea-4594-8aa3-fa50d2a61314.jpg)

**Comment by thomaschampagne** [comment]
You should now use the desktop app (beta) instead: https://thomaschampagne.github.io/elevate-docs/
