### ISSUE TITLE
Elevate Imported, a ride I did approximately 3 years ago as thought I did it yesterday at a speed of 270kph

### ISSUE THREAD

**Issue by Kirsty99** [thomaschampagne/elevate#1087]
**⚠ BEFORE ANYTHING: Are you in the right place?**

Before creating any issues, you HAVE TO check if issue already exists:

* Check for answer in Frequently Asked Questions here: https://thomaschampagne.github.io/elevate-docs/
* Check for already existing issues matching with yours: https://github.com/thomaschampagne/elevate/issues

Any unsuitable issues will not be handled. Since this project is performed on free time and has hundreds
of thousands users now, there's no room to handle duplicate or irrelevant issues...

Please be wise when opening an issue.

Thank you for your understanding!

If your issue is suitable, you can remove this warning before submitting it.

**Describe the bug**
Elevate Imported, a ride I did approximately 3 years ago overnight as thought I did it yesterday 13 March  at a speed of 270kph and a power of 2000+w. It was naturedly flagged as an error.
So I thought I'd just let you know 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Windows, Linux, MacOS]
 - Desktop app version [e.g. 7.0.0]

**Additional context**

**Comment by thomaschampagne** [comment]
Hi,

Do you have the file associated to the ride?

Thanks
