### ISSUE TITLE
Weather on running activities

### ISSUE THREAD

**Issue by philipwhiuk** [thomaschampagne/elevate#109]
Currently as documented (and it seems to be this way) Stravistix only shows weather for cycling activities. Is there a specific technical reason why running is not supported?

If it's just development time, I'm happy to try and poke around and see if I can make a first contribution to do this feature.

**Comment by thomaschampagne** [comment]
It's normal. Because i'm not able to get the right date and time on running activities

**Comment by philipwhiuk** [comment]
The activity does seem to contain the date time: 
e.g. : https://www.strava.com/activities/360230280

10:25 on Monday, 3 August 2015

Is it the time-zone you're missing?

**Comment by thomaschampagne** [comment]
Nop,

It must work for all language. It's complicated to compute date with different language and format like your example.

In cycling i can get the start date like this:

```
pageView.activity().get('startDateLocal')
```

This does not work for running activities. If you are able to get it properly... give me your JS code ;)

Tom
