### ISSUE TITLE
[Web-Ext][Bug] Activity Type (and Power data) is no longer imported from Strava for both types of Sync

### ISSUE THREAD

**Issue by MisterTickle** [thomaschampagne/elevate#1207]
**Describe the bug**
Since around 21st October, the extension no longer imports the Type (Walk. Run, etc) of every event from Strava. I noticed only the other day, on the "Fitness Trend" graph that the types were all missing. On the "Activities" page, all the types are blank. It's added a type of "Undefined", which if I select, clears the list.

Not being about to break down the different types is a bit of a catastrophe! This affects all pages in the extension in some way or other. 

I have two PCs. On the first, I export my full profile data, then edited the JSON very carefully to put back in the correct types (copied from earlier events - eg
end of each event **should** be something like

```
    "trainer": false,
    "type": "Walk"
}
```

but the recent "bad" events from the last two weeks only had:
```
    "trainer": false
}
```
). Next, I tried to re-import this full-profile "repaired backup" JSON file in the normal way, but it complained about a duplicate event (and the duplicate was my earliest event). I know I've restored a profile before without any issues, so wondered if something in a new update to the Extension has caused either issue. Because my attempts at a repair didn't work, I kicked off a "full" sync which first wipes all the event data, and now ALL events (not just the most recent few weeks) **are completely missing the type.** I now regret trying a full re-sync, because on this PC they are all screwed up instead of only the most recent ones.

On my other PC, I'm too scared to do anything, but I can see that every event since 21st Oct is firmly missing the type no matter what I try. Nothing is different about them on the Strava side.

**To Reproduce**
Steps to reproduce the behaviour:
Synchronise any recent event from Strava.
Check what type it is shown as, on the Activities page.
See that the "Type" column shows "-" for the event.

**Expected behaviour**
The "Type" should be filled with the correct sport, eg Run, Walk, etc.

**Screenshots**
![Screenshot 2024-10-31 125654](https://github.com/user-attachments/assets/1be4edb6-de90-419d-a8b7-0858635bd852)
![a061c86a-09d7-452a-b069-58104c4583c6](https://github.com/user-attachments/assets/1b2c12b9-22d5-4a11-bdde-47d949698924)

**Screenshots - tangential**
These screenshots are errors which have appeared on pages of the plugin **since** I started the "full sync", in order to try to get my data back. They are not the core problem I raise this bug about. They may be because I have ticked various selection of Type previously, and those screens are now upset that they can't find those Types in the data as it is now. I do not think they are the main cause, but I will provide them in case they help in any way!
![Screenshot 2024-10-31 125844](https://github.com/user-attachments/assets/7ad2feca-7f22-4232-9f15-50d312306e8e)
![Screenshot 2024-10-31 125759](https://github.com/user-attachments/assets/7d129efd-68a7-4a65-8e46-a2a0cff079b9)

**Environment**
 - OS: Window 11
 - Chrome Version 130.0.6723.92 (Official Build) (64-bit)
 - Elevate for Strava 7.2.0

**Additional context**

**Comment by Oskin-hub** [comment]
I have the same problem, Activity Type is no longer imported from Strava. In addition, activities since Oct 15, in ElevateApp (Chrome extension) lost the Activity Type, some days before the type was correct - Ride. 
![image](https://github.com/user-attachments/assets/766a8673-c779-4656-809a-979aec3dec62)
Windows 10
Chrome Version 130.0.6723.92 (Offizieller Build) (64-Bit)

**Comment by EddyTwerckx** [comment]
Having the same problem.

**Comment by MisterTickle** [comment]
Thanks for the replies, to me this shows it's a much more widespread issue.

**Comment by MisterTickle** [comment]
My full sync has now completed, as expected the 'type' is now wiped for every event.

Interestingly, when comparing the old JSON profile backup with the newly created backup from the full sync, I can also see that the "power" data fails to import, not only the type.

I had 297 events with power data before, eg

`                "power": {
                    "avg": 224.057,
                    "avgKg": 2.667,
                    "best20min": null,
                    "intensityFactor": null,
                    "lowQ": 214.032,
                    "max": 258.586,
                    "median": 229.32,
                    "peaks": null,
                    "stdDev": 29.124,
                    "upperQ": 238.056,
                    "variabilityIndex": 1.015,
                    "weighted": 227.313,
                    "weightedKg": 2.706,
                    "work": 71,
                    "zones": null
                },
`

Every single one of these has been imported as:
`"power": null,`

**Comment by Askildbo** [comment]
I have the same issue, but for me its back to october 1st. Got a new computer around then and downloaded every activity from Strava (no backup). Everything was fine, i.e. the graph for yearly progression was normal. About a week ago activities dated after october 1st was like described from others: activity type was blank and they were not counted. 
I suspected athlete settings since they were updated around october 1st, but I reccon it's something with the import from Strava.

**Comment by MCBUQUETS** [comment]
I am having the same issue. 9/29 was the last time activity type was imported.

**Comment by pjktk2** [comment]
I have the same issue. I tried re-syncing (didn't work), adding new dated athlete setting & re-syncing (didn't work), and then somehow all my dated athlete settings got erased, but after adding new athlete settings and doing another re-sync, still doesn't work.

**Comment by thomaschampagne** [comment]
I made a hotfix in version 7.2.1 for this. Waiting for google to be published.

**Comment by drewguy** [comment]
Sorry - realize now I posted this issue in the desktop app thread.  

The activity type is not syncing in the Google extension (Mac Chrome) and hasn't since Sept. 28.

**Comment by thomaschampagne** [comment]
@ALL The 7.2.1 fix is now live. You may fully restart your browser to get the update

**Comment by MisterTickle** [comment]
Excellent, many thanks!

**Comment by drewguy** [comment]
Thanks for fix - didn't even need to resync activites in browser extension.
