### ISSUE TITLE
Export of the training journal

### ISSUE THREAD

**Issue by tschm** [thomaschampagne/elevate#131]
Love your little project. Could you please, please make a simple export (to csv, or display via datatables.net) of the Strava training journal. Should be a piece of cake for you
thomas

**Comment by praveentiru** [comment]
@tschm Can you kindly explain what is that you miss from strava's "My Activities" page? It would help me what exactly you are looking for and maybe a develop a good solution around that.

**Comment by tazmanska** [comment]
@praveentiru I started to work on export activities feature but due to lack of time I didn't finsh it. Take a look https://github.com/tazmanska/stravistix/commit/266eaf5f691100a49d6846e17da0a6ae85b952b8

**Comment by praveentiru** [comment]
@tazmanska I will look at this once I find some time.

**Comment by ethanopp** [comment]
Realize this is a little old... but +1
