### ISSUE TITLE
Extended stats for all activities as generic

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/elevate#167]

**Comment by philipwhiuk** [comment]
As a hotfix:

Change this line to no longer reference a future (esp. an old one)

https://github.com/thomaschampagne/stravistix/blob/a3d020cb9fd4dcbcb2078cabb778f235fe65cb60/hook/extension/js/StravistiX.js#L461

Example activity: https://www.strava.com/activities/463519034/overview (yellow box)

**Comment by thomaschampagne** [comment]
@philipwhiuk Thanks for report.

I will see that change into next release

Tom

**Comment by tomfiv** [comment]
Have you looked more into this?


The majority of my activities this time of the year are skiing, and won't let me see the extended stats (time spent in different zones being the most important to me)
