### ISSUE TITLE
LTHR-based heart rate zones

### ISSUE THREAD

**Issue by gmucha** [thomaschampagne/elevate#18]
This would be based on Joe Friel's way of setting zones -based on Lactate Threshold. Strava has something akin to that for FTP or Pace Zones (in Premium). As this is quite popular for runners, I imagine adding this would be quite valuable.

http://home.trainingpeaks.com/blog/article/joe-friel-s-quick-guide-to-setting-zones

This could be accomplished with current HRR zones (set rest HR to 0, max HR to LTHR value)., but right now rest HR is limited to 10.

**Comment by patfelst** [comment]
Also let us define HR zones in % of Maximum, not just % of HRR. Thanks!

**Comment by jayti74** [comment]
A LTHR or FTHR heart-rate zone method could be implemented with the LTHR/FTHR value we need for the new pmc feature described in #341.

For the calcualtions i would prefere the coggan method over friels, as used in the british cycling calculator https://www.britishcycling.org.uk/membership/article/20120925-Power-Calculator-0

1 <68%
2 69-83%
3 84-94%
4 94-105%
5 >105%
