### ISSUE TITLE
Add Google Maps directly on Maps

### ISSUE THREAD

**Issue by glandais** [thomaschampagne/elevate#183]
A snippet that works for flyby view : https://gist.github.com/glandais/00caf3059e11254ee910

But I don't know how to retrieve the maps instances in activity view...

**Comment by tazmanska** [comment]
Do you mean the Mapbox map object?
https://github.com/thomaschampagne/stravistix/blob/develop/hook/extension/js/modifiers/ActivityBestSplitsModifier.js#L122

**Comment by liskin** [comment]
I took your snippet and added it to my strava map switcher bookmarklet, which now offers LOTS of additional map options directly in the map picker on activity page: https://github.com/liskin/strava-map-switcher/blob/master/fix.js

(I wouldn't mind if this was integrated into stravistix, although I don't use it myself for performance reasons.)
