### ISSUE TITLE
Set Zone wattage to users choice.

### ISSUE THREAD

**Issue by Knoxie** [thomaschampagne/elevate#189]
Why can I not set my zone to what I  want. The Cycling zones seem way out of wack.

This is what I want to set it to: ![capture](https://cloud.githubusercontent.com/assets/1057404/12728196/a2ada5ac-c8ee-11e5-801d-dc48b114bcaf.PNG)

But it wont let me. Also, why do i have to use the up/down arrows, not just type it in?

**Comment by thomaschampagne** [comment]
HI,

You should probably start your ticket with an "hello", "hi"... and finish with "thanks" no?

Basically you want to give names to your zones?

>But it wont let me. Also, why do i have to use the up/down arrows, not just type it in?

Because of technical problems ;) i don't want overlapping and to ensure no overlapping zones.

Cheers,

Tom
