### ISSUE TITLE
Analyze workouts and display in data in table

### ISSUE THREAD

**Issue by Knoxie** [thomaschampagne/elevate#207]
If you could analyze a workout based on specific intervals and then see the related data like in perf pro it would be great. Here is example image of what i'm talking about: 

![Perf pro workout analyzer table](http://96bda424cfcc34d9dd1a-0a7f10f87519dba22d2dbc6233a731e5.r41.cf2.rackcdn.com/CyclingCenterDallas/Feb_9_6_minute_intervals.jpg)

**Comment by kuba-wu** [comment]
Vote up for this. As in general such feature can be tedious to implement, I'd propose to implement first version in a following way:
- add interval analysis modal (window) per workout
- in the first step, define number and length of intervals to be found (eg 4 intervals, 4 minutes - classic VO2max training)
- let stravastix find the intervals as per configuration and display in table - NP, avg power, avg HR, avg cadence, time started
What do you think?
