### ISSUE TITLE
Upload photo

### ISSUE THREAD

**Issue by glandais** [thomaschampagne/elevate#217]
It would be great if we were able to upload a photo from the browser!

I have no idea of the photo endpoint used in the web app...

**Comment by thomaschampagne** [comment]
@glandais Seems to be hard to handle :/

No API endpoint for photos on web app. Only cloudfront link for each image you put from smartphone app.

**Comment by liskin** [comment]
There is an API endpoint, https://www.strava.com/api/v3/photos/metadata, that accepts Content-Type: application/json via PUT in this format:

    {"location":[49.123,16.456],"taken_at":"1468140911","uuid":"5da0f64d-f82e-4404-8602-75066fd58f90"}

location and taken_at can be left out, just the uuid is important (the client is expected to generate a new random uuid). It will return a JSON with URL to Amazon S3 where the photo should be uploaded. Then a PUT to the normal activity update endpoint (https://strava.github.io/api/v3/activities/#put-updates) may contain a photo_ids field, like so:

    {"photo_ids":["1:5da0f64d-f82e-4404-8602-75066fd58f90"]}

Unfortunately these API endpoints don't accept cookie based auth and need an auth token. I wanted to implement photo uploading to stravistix today, but I don't think I know enough js to implement the auth part. I'll try to implement it into https://github.com/tfausak/strive and test if it works, but I already tried some of this manually via curl and it seems to work.

(None of this is documented, unfortunately, I had to reverse engineer things.)

**Comment by tariquesani** [comment]
I remember reading somewhere on the API Google group that Strava does not want to open the upload API as it stands. Won't be a good idea to fall on the wrong side with Strava...

**Comment by liskin** [comment]
Would you happen to remember where you read that? Any idea why they want to keep it closed? Sounds very suspicious to me.

**Comment by liskin** [comment]
I thought it might be for security reasons, but after uploading an animated gif, it got converted to a jpeg and resized, so it's not like it'll let you store arbitrary data there. And I doubt they're just worried about imagemagick bugs (maybe they're converting it using something else).

**Comment by tariquesani** [comment]
https://groups.google.com/forum/#!searchin/strava-api/photo$20upload/strava-api/pmvADkb0n7U/lUeog1UbAAAJ No details - just that there are no plans

**Comment by Doogal666** [comment]
liskin, what do you mean regarding the authentication requirements? Does it not work with OAuth tokens?

**Comment by liskin** [comment]
@Doogal666 I think it does. It's just that Stravistix does not use oauth.

**Comment by Doogal666** [comment]
@liskin I've knocked together something using OAuth and I get a 401 when using the metadata endpoint but I can access other parts of the API. Do you still have an example of the HTTP request that worked for you? Maybe the user agent string has to be something specific

**Comment by liskin** [comment]
@Doogal666 Well I must admit I did use the OAuth token that the mobile app uses, I didn't generate my own. Maybe there's a special permission that it obtains. :-/

**Comment by liskin** [comment]
(By permission I mean scope in the API.)

**Comment by Doogal666** [comment]
@liskin Seems so, I still get the 401 with scope of write and view_private. Very annoying that Strava make it almost impossible to upload a photo unless you've got the Strava app

**Comment by c5creative** [comment]
@liskin @Doogal666 For what it's worth, I'm not sure it's restricted to the Strava App. Zwift is one example (perhaps the only one) of an app that can upload pictures via a mechanism outside of the Strava app. I presumed it's through the API and perhaps there is an undocumented bypass feature for commercial partners, like Zwift.

**Comment by Doogal666** [comment]
Absolutely mental, a website for cyclists lets a computer game upload screenshots but doesn't let cyclists upload photos from their rides... But if any Zwift users are able to capture the http traffic I'd be interested to have a look.

I did have a thought about hooking up to the Instagram API and posting a photo to Instagram with a date and time matching the desired activity but then I discovered the Instagram API doesn't allow photo uploads...

**Comment by c5creative** [comment]
@Doogal666 I have a friend that uses Zwift (that's how I noticed), and I've spoken to him about intercepting his HTTP traffic. He said, "whhaaaaat?". Still, it's not a guarantee. It could be that the data is sent to Zwift first, and that some dedicated data-sync occurs between Zwift and Strava.

**Comment by liskin** [comment]
HTTP is almost always SSL-encrypted nowadays, so just intercepting packets won't help. We'll need to reverse engineer Zwift or the Strava Android app. I did the latter but just the photo uploading part, not authentication. If Zwift uses API to upload photos, it might be a good idea to reveng that, too. Not sure if I get to it any time soon though. :-(
