### ISSUE TITLE
Add targets/presets to year progression

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/elevate#328]
**Target/presets:**

A preset is combination of **Progress type*** + **Activity types*** + **target value**

- [ ] "Add preset or target" button => _Open form dialog w/ fields_: **Progress type*** + **Activity types*** + **target value**. Validate with an **Add** button.

- [ ] "Load presets (x)" button: display dialog w/ current presets in a table with actions on rows: **load** + **delete**

x = count of presets

_***required field**_

**Comment by thomaschampagne** [comment]
Progress preview:
![image](https://cloud.githubusercontent.com/assets/151973/22404217/91805142-e62c-11e6-8628-49e5b4f42393.png)

**Comment by tazmanska** [comment]
Awesome job!

**Comment by thomaschampagne** [comment]
@tazmanska Job from you ;)

**Comment by thomaschampagne** [comment]
- [ ] Targets Ride/Run support
- [ ] Miles/Km support
- [ ] Time format support
- [ ] 30d support

**Comment by thomaschampagne** [comment]
**Target/presets:**

A preset is combination of **Progress type*** + **Activity types*** + **target value**

- [ ] "Add preset or target" button => _Open form dialog w/ fields_: **Progress type*** + **Activity types*** + **target value** _and **Add** button_

- [ ] "Load presets (x)" button: display dialog w/ current presets in table with actions on rows: **load** + **delete**

x = count of presets

_***required field**_
