### ISSUE TITLE
As another character than plus when joing activities in Multisport Fitness Trend

### ISSUE THREAD

**Issue by hnaess** [thomaschampagne/elevate#336]
The plus symbol is a very common character to use in activities titles, so when several activities (on the same day) are joined together in the Multisport Fitness Trend it is difficult to separate activities from each other (because of + used in activities titles and as a character for joining activities titles)

**Comment by thomaschampagne** [comment]
@hnaess Thanks for report.

Which separation do you suggest?

**Comment by hnaess** [comment]
Good question. https://en.wikipedia.org/wiki/Delimiter describe the problem also. But not the solution.

Not sure what is best:
Maybe two of the same characthes like:
||
//
^^
