### ISSUE TITLE
Activities links?

### ISSUE THREAD

**Issue by PeteHarston** [thomaschampagne/elevate#342]
**Bug description:** 

**Actual Behavior:** 

**Expected Behavior:** 

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by PeteHarston** [comment]
StravistiX isn't synchronising activities. Strava has listed a number of sessions during January and February involving riding bike which has failed to be added to StravistiX this is despite the synchronising functioning.

Any reasons why?

**Comment by thomaschampagne** [comment]
Do you have activities link example? Any files of theses activities (source file)?

Ty

**Comment by PeteHarston** [comment]
I have spent most of the winter using Gym bikes because of the weather. I've ridden over 300 miles doing so but non of this has been registered in Stravistix. My heart rate is registered but not through Strava as this cant be used but through the 'Activity app' used apple watch. The time, mileage, speed is registered on Strava after completion. Could it be that that lack of heart rate reading means it doesn't tract in Stravistix?
