### ISSUE TITLE
New Yearly progressions activities selected

### ISSUE THREAD

**Issue by DaveHaygarth** [thomaschampagne/elevate#369]
**Bug description:** 
Activities selectes one over count 
**Actual Behavior:** 
Shows two selected when one is selected, three selected when 2 selected etc
**Expected Behavior:** 
Show 1 selected when 1 is selected
**Steps to Reproduce:** 
- ? All I did was open it!
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**
http://support.reversedelta.com/capture_upload/14-12-19.png

**Comment by AdriaanPan** [comment]
Same here. It always include virtual ride somehow?!? (If you scroll down you will see this!)

If you select RUN, you get 2 selected:  VirtualRide + Run
If you select RIDE, you get 2 selected:  VirtualRide + Ride
