### ISSUE TITLE
Year progression hours bug?

### ISSUE THREAD

**Issue by whizwith** [thomaschampagne/elevate#373]
The distance looks fine, but it looks like one activity may be overstated, almost 60 hours (see 2017 jump in Feb). On that date, there was one 5 mile run, about 45 minutes long. I opened the json file with notepad and it appears the elapsed time is quite large although I'm not sure how it is calculated. Also, no matter what I do, it seems as though it always says 2 activities are selected, even though I only select "run". Keep up the good work. I just started using this and it looks great.
![screenshot178](https://cloud.githubusercontent.com/assets/26703062/24341621/ea8ca8fc-1288-11e7-85b0-0fa1b80b6d18.jpg)
![screenshot179](https://cloud.githubusercontent.com/assets/26703062/24341620/ea8c6770-1288-11e7-81f7-52b30c6fc994.jpg)

**Comment by drahdiwaberl** [comment]
i've got one month summing up to 5,423.9 hours - checking in strava there's only one activity there with 1:32:05 moving time and no other suspicious data.. https://www.strava.com/activities/108361745

**Comment by gethin88** [comment]
![image](https://cloud.githubusercontent.com/assets/11189817/25855812/8a57fce8-34d4-11e7-8756-fed97510d7b7.png)
It's easily overlooked, probably a time sync issue from your gps device.
Cut off the start (or end) to remove the fault long time.
