### ISSUE TITLE
Year progression in Time(h) view shows incorrect graph and data in the table below

### ISSUE THREAD

**Issue by sergtimosh** [thomaschampagne/elevate#374]
**Bug description:** 
when switch to Year progression tab, and chose Time(h) option the graph and table below shows incorrect data due to acual data in Strava calendar.
**Actual Behavior:** 
2015 results are higher in hours than 2017
For the 2015 from begining to 27.03.2015 - in strava shows 38 Hous, Stravistix - 109 Hours
For the 2017 from begining to 27.02.2017 - strava shows 138 Hours, Stravastix - 80 Hours
**Expected Behavior:** 
2017 stats should be higher than 2015
**Steps to Reproduce:** 
- open Year Progression tab
 - chouse Time (h) option
 - open strava calendar for 2017 https://www.strava.com/athlete/calendar/2017 and for 2015 https://www.strava.com/athlete/calendar/2015 and compare
**Chrome version** 
56.0.2924.87 (64-bit)
**Plugin version:** 
5.7.1
**Activities links?:** 
https://www.strava.com/athletes/6396051
![2017-03-27_14-18-58](https://cloud.githubusercontent.com/assets/26712442/24354685/7b4d843e-12fb-11e7-997e-6d845278f4ef.png)
![2017-03-27_14-19-30](https://cloud.githubusercontent.com/assets/26712442/24354683/7b4d01bc-12fb-11e7-9ec4-72fd34cabae6.png)
![2017-03-27_14-42-54](https://cloud.githubusercontent.com/assets/26712442/24354763/d24cdb68-12fb-11e7-8a3b-a38ffd232025.png)

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by tstraw48** [comment]
I am also experiencing this issue. My 2010 graph shows 100 more hours than I rode.
