### ISSUE TITLE
Extended search activities options.

### ISSUE THREAD

**Issue by Fab4ever** [thomaschampagne/elevate#375]
The standard Strava search misses some possibilities to narrow down and/or sort activities.
E.g. when searching for 'Marmotte', you get an endless list of activities, because lots of people ride the Marmotte. The list includes results from today, as well as last week's, last year's or even earlier rides. There's only the possibility to limit the results by distance, time ridden or height distance.
I wish there was a way to narrow the results down by adding a search period ('ridden between dd/mm/yy and dd/mm/yy').

**Comment by alteredego** [comment]
I've been thinking a lot about extending the search capabilities for your own activities (which Strava still has some longstanding fundamental bugs) - but it's not going to be possible for this extension to make any meaningful differences to the main "Activity Search" function for other people's activities.  Although this extension doesn't use the main Strava API, there are also no open API calls for search functionality.

There is a support thread here - https://support.strava.com/hc/en-us/community/posts/208849587-Feedback-for-Search-features-on-Strava

The thread was started by a Strava employee two years ago asking for ideas to improve search and even includes your suggestion for a search period criteria.

I'd suggest you apply some pressure on Strava, especially if you are a Premium member.
