### ISSUE TITLE
Year Progression Time Plot Error 

### ISSUE THREAD

**Issue by JD1012** [thomaschampagne/elevate#376]
**Bug description:** 
Cumulative time in year progression is wrong
**Actual Behavior:** 
The graph suggests that I rode 1400 hours in 2013. In one 24 hour period, the plot suggests I rode ~100 hours. 
**Expected Behavior:** 
I actually rode around 323
**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 
5.7.1
**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

** comment: 

Honestly, year progression looks a lot worse than it did when it was directly accessible on the main strava page - the graphics are now too small and accessing information is not as streamlined. It also contained the additional feature of looking at how much riding I had done in the last 30days. I really liked this feature and am disappointed its gone. It was perfect as it was before. It would be great if you could either reinstate it as it was or make it as good as it was. As the saying goes, if it aint broke, dont fix it. Thanks

**Comment by mcneary70** [comment]
Just noticing the same thing.  Several years have huge jumps for me over a day or two.

**Comment by tstraw48** [comment]
I should have looked at open issues before I made my own. It's frustrating not knowing what day I'm hovered over in the future. I have a large uptick in km from a few years ago I want to stay above but I have no idea what the date is.
