### ISSUE TITLE
YTD chart doesn't display selected date correctly

### ISSUE THREAD

**Issue by tstraw48** [thomaschampagne/elevate#377]
**Bug description:** 
In the YTD chart, if you hover over a date in the future it only displays the current date. If I hover over the December 31 it says March 30 (today is March 30)
**Actual Behavior:** 

**Expected Behavior:** 
The date should show the date I'm hovered over.
**Steps to Reproduce:** 
- go to YTD chart
 -hover over date in the future
 - ...

**Chrome version** 
Version 56.0.2924.87
**Plugin version:** 
5.7.1
**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**
https://drive.google.com/file/d/0BwjtcZdaqM05UjByOGdpeUhIbGM/view?usp=sharing

**Comment by superbole** [comment]
I have the same request.
