### ISSUE TITLE
Running power meter supported in statistics but not for Multisport Fitness Trend

### ISSUE THREAD

**Issue by mikaeln** [thomaschampagne/elevate#389]
Power from a running power meter (like Stryd) is displayed in the Stravistix statistics (and extended statistics), but is not supported in the Multisport Fitness Trend. There should be an option to use Power Stress Score (as an alternative or supplement to TRIMP) for running activites with power data.

**Comment by grzegorz-jazurek** [comment]
@mikaeln this feature is available right now

![screen shot 2017-07-31 at 19](https://user-images.githubusercontent.com/4790672/28790779-9f166c9a-762a-11e7-8378-3c64db059d53.png)

**Comment by thomaschampagne** [comment]
It's only for cyclists at the moment. You have to wear an heartrate monitor.
