### ISSUE TITLE
143 activities on strava, only 11 are synced with Stravistix

### ISSUE THREAD

**Issue by veggel75** [thomaschampagne/elevate#393]
**Bug description:** 
143 activities on strava, only 11 are synced with Stravistix

**Actual Behavior:** 

**Expected Behavior:** 
All activies must be synced 
**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
57.0.2987.133
**Plugin version:** 
Installed 3 days ago
**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by ossolisergio** [comment]
i had same issue, it's cause only activities with HR monitor will be shown
