### ISSUE TITLE
Meters showing yearly/monthly/weekly progress against the annual overall target distance are not consistent in considering Virtual Rides

### ISSUE THREAD

**Issue by sugose** [thomaschampagne/elevate#398]
**Bug description:** 
Meters showing yearly/monthly/weekly progress against the annual overall target distance are not consistent in considering Virtual Rides. The standard Strava "out of the box" presentation of progress towards the annual goal includes Virtual Rides in the aggregation while the StravistiX counters (monthly/weekly) does not seem to consider Virtual Rides.

**Actual Behavior:** 
Virtual Rides not considered when presenting progress towards annual goal
**Expected Behavior:** 
Virtual Rides should be considered when presenting progress towards annual goal as that is how Strava "out of the box" is calculating  yearly progress.
**Steps to Reproduce:** 
- Note your progress on the yearly/monthly/weekly progress counters
- Do a ride of X distance that is classified as a "normal" ride. The distance will be reflected on your counters as yearly+X/monthly+X/weekly+X.
- Do a ride of Y distance that is classified as a Virtual Ride (e.g. by using Zwift). The distance for this ride will only be added to the yearly counter.

**Chrome version** 
 58.0.3029.110 (64-bit)
**Plugin version:** 
5.7.2 stable
**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
N/A
``` 

**Link screenshots or youtube video link if necessary:**
I  am linking screen shots of my riding activities for current week (Monday May 22-Wednesday May 24) and a view of how my progress counters look as a result. Note that for the week I have done a total of 31.2 km of riding on the road and 83 km Virtual Riding (in Zwift)

https://www.dropbox.com/s/zjth288hgfzljce/Screenshot%202017-05-25%2010.27.13.png?dl=0
https://www.dropbox.com/s/umqft5bozyjaqu3/Screenshot%202017-05-25%2010.26.25.png?dl=0

Also added a screenie of how Strava "out-of-the-box" is presenting the yearly progress
https://www.dropbox.com/s/ghvlpmilf8pnzeg/Screenshot%202017-05-25%2010.26.03.png?dl=0

**Comment by akrzysztofek** [comment]
@sugose Noob question here: How do you set weekly goal in StravistiX? Aren't all of these (presented on screenshots) Strava and not StravistiX goals?
