### ISSUE TITLE
Graph dives after absence of HR monitor for a week.

### ISSUE THREAD

**Issue by pomistea** [thomaschampagne/elevate#399]
**Bug description:** 

**Actual Behavior:** 
After a week with no HR monitor, I started using a HR monitor again. Fitness and fatigue levels dropped considerably. Fitness level dropped by about 15%, fatigue level dropped by about 60%.
**Expected Behavior:** 
My training remained consistent with what is has been for the past 3 months, fitness and fatigue levels should have risen slightly or remained more or less constant.

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
Version 58.0.3029.110 (64-bit)

**Plugin version:** 
5.7.2 Stable

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**
<img width="937" alt="screen shot 2017-05-28 at 6 03 35 pm" src="https://cloud.githubusercontent.com/assets/29020939/26530603/0b662d3c-43d0-11e7-8e56-7d13b2266ca6.png">

**Comment by bjohns2** [comment]
This is expected behavior, but a possible solution could be to allow users to manually add TRIMPs on a given day.
