### ISSUE TITLE
Since three days when i sync, the workouts doens't add to the list.

### ISSUE THREAD

**Issue by vancamptim** [thomaschampagne/elevate#402]
**Bug description:** 

**Actual Behavior:** 

**Expected Behavior:** 

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by CommanderBrot** [comment]
Do these workouts include heart rate values? AFAIK they don't show up in that case.
