### ISSUE TITLE
Predicting fitness and fatigue

### ISSUE THREAD

**Issue by joshsmith** [thomaschampagne/elevate#406]
Something I'd been thinking about: using planned workouts within certain heart rate zones in order to predict whether training is likely to be too hard.

Is there any way for us to potentially add in predicted data points and massage them to find the best training zone for us?

**Comment by duhlig** [comment]
You could estimate your TRIMP score by looking at the hourly TRIMP-rate of one of your historical workouts that had a similar effort level than what you're planning now. Just multiply that by the hours of training for your predicted workout and you get a fair estimate. With that estimate it's fairly easy to calculate the impact.

CTL = CTL' + (TRIMP - CTL') / 42
ATL = ATL' + (TRIMP - ATL') / 7
TSB = CTL - ATL
where CTL' is the CTL value of the day before the predicted workout. ATL' respectively.

**Comment by JoshSmith** [comment]
Thanks, @duhlig! That's very helpful. I'd still love for something like this to be possible to use in Strava/Stravistix, but I suppose the worst case scenario here would be to plug this into a spreadsheet to predict and graph it myself. Seems straightforward enough.

**Comment by duhlig** [comment]
I agree @JoshSmith, this would be a great feature to have.

**Comment by JoshSmith** [comment]
@thomaschampagne I know you're busy, but would you mind commenting as to whether this is something you would like? I might be happy to dedicate some time to a PR just to avoid doing this myself in a spreadsheet 😂
