### ISSUE TITLE
Multisport fitness trend

### ISSUE THREAD

**Issue by alexisrosuel** [thomaschampagne/elevate#407]
Hi,

I noticed that the beta feature 'multisport fitness trend' doesn't take into account races when my cardio was off. It think that it would be great to propose an estimation ('maybe based on the average cardio of the previous races ?), in order to keep up to date the graphs ?

Thanks a lot

**Comment by alexkirkp** [comment]
Something like this would be very helpful.  Using inaccurate heart rate data to generate a TRIMP score for each workout would result in much more useful data than completely ignoring the workout.

TRIMP can be calculated by using an average heart rate for an activity (although I assume the default method for stravistix is more complicated?).  I see three ways to get an average heart rate for a workout that doesn't have any HR data:

1) Get the average HR of the last X number of workouts of the same activity type
    - This would be the easiest for the end user
    - At some point going back would be excessive, for example if the user had 5 rides with a HR monitor 6 years ago and has not used one since
2) Allow users to set a default HR for each activity type
    - Probably the easiest method to implement
    - Requires action by the end user, but not an unreasonable amount
3) Allow users to set an HR for each activity that doesn't have it
   - Seems unlikely to be feasible, presumably the data would be removed and have to be re-entered every time a full sync was preformed

**Comment by CommanderBrot** [comment]
Yes, I second that.
I too have some activities without HR and now everything's off (trimp, fitness, fatigue).

As a software developer myself I would suggest solution #1, I think implementation wouldn't be too difficult and it doesnt't require any user interaction. If the data's old or unusal - well then accuracy is not very good. But a guesstimate is always a guesstimate.

**Comment by nickcoyne** [comment]
Another alternative would be to allow manual entry of a TRIMP score. I have some activities (paddleboarding) where if I fall in the water during the activity, the HR strap starts sending weird values, making the recorded HR innacurate. I manually estimate values for my own TRIMP calculations and TSS in a spreadsheet, but it would be great to have this option in Stravistix.
