### ISSUE TITLE
Big TRIMP differences StravistiX vs TrainingPeaks

### ISSUE THREAD

**Issue by papuass** [thomaschampagne/elevate#408]
I have been trying fitness trend graphs both in StravistiX and TrainingPeaks.

If I take an example of 1:33:00 MTB race with HR avg 172, max 183 then:
* TP gives hrTSS as 204
* StravistiX TRaining IMPulse is 309

My HR is set to 50-185 in both apps, body weight is 77kg. 
Is there something wrong with the HR zones?

**Comment by duhlig** [comment]
TRIMP and hrTSS are different measures. Although they are both based on heart rate they scale differently. hrTSS seems to be already scaled down to be comparable with TSS. On the contrary, TRIMP is not scaled. If you want to approximate TSS from TRIMP you have to divide by ~1.65-1.75. To be more exact, TRIMP of one hour at 85% HRR, which is roughly your FTHR, divided by 100. 

Doing that for your data will get you in the same ballpark for both measures.

**Comment by papuass** [comment]
I am planning to do a sports lab test in near future, but 185 seems to reasonable both by age formula and workout history (during last year I have reached maximum 183). I am training with Trainer Road in winters using their interval workouts and have done FTP test ~10 times.

I understand now the diference between TRIMP and hrTSS, but the reason I brought it up was differences in form graph (StravistiX says I am more fatigued than TrainingPeaks).

**Comment by duhlig** [comment]
The training zones in the Multisport Fitness Trend are based on power (TSS). Thus, with unscaled TRIMP you're likely to overshoot the zones while the general trend is still valid. This is already discussed in issue #341. For now, you can scale up the zones (in your mind) by ~1.65-1.75 like you'd scale down your TRIMP. 

You'd get 
Form < -51: Overload
-51 < Form < -17: Optimal
-17 < Form < 9: Neutral
9 < Form < 43: Freshness
43 < Form: Transition
