### ISSUE TITLE
Hide Stravistix-features from other athletes

### ISSUE THREAD

**Issue by DrD0kter** [thomaschampagne/elevate#415]
Can it be possible to create an option to hide Stravistix-features from orther athletes? Most of the people I'm following have a telephone-based Strava-upload so there are a lot of blanks in the right top corner when I open their rides.
It would be nice if I have an option to show the data at my activities only or (ideally) to select the athletes from who I want to show more Stravistix-data.

**Comment by OndrejSpanel** [comment]
Note: you do not see their extended stats anyway. TRIMP is calculated based on their HR data but your HR zones, which is quite confusing.
