### ISSUE TITLE
Stryd power disappeared from Stravistix since after 5th July

### ISSUE THREAD

**Issue by dobssi** [thomaschampagne/elevate#417]
**Bug description:** 

None of my runs since after 5th July have power data. Using Stryd, all data present in Garmin Connect and Stryd Powercentre

**Chrome version** 

59.0.3071.115 

**Plugin version:** 

5.8.1

**Activities links?:** 

WIth - https://www.strava.com/activities/1069262142/overview
Without - https://www.strava.com/activities/1072903216/overview#

**Comment by thomaschampagne** [comment]
It's a strava problem: they have removed power stream from running activities. 

Let me know if it works again
