### ISSUE TITLE
different power values for the same activity

### ISSUE THREAD

**Issue by meste7** [thomaschampagne/elevate#430]
First of to say that I really like stravistix... 

I find two different values reported in terms of Power, you can see the attachment. One in the higher area (Dr Coggan) and one below this zone which seems to be reported by Strava(?)

 

Which one should be taken into consideration?

Many thanks
<img width="573" alt="screen shot 2017-08-06 at 11 28 18" src="https://user-images.githubusercontent.com/30768682/29001740-8c7c91de-7a9b-11e7-84db-a84c544aece6.png">

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by akrzysztofek** [comment]
@meste7 , you should definitely click on Dr Coggan link as this shows detailed explanation why both of these are different.
