### ISSUE TITLE
Rest day fitness trend decrease Vs workout increase

### ISSUE THREAD

**Issue by Ckemp15** [thomaschampagne/elevate#434]
Hi im enjoying using Stravistix for cycling however I find when I take a rest day (24hours) my fitness trend drops by 1.7 - 1.8. But after a 100TSS workout it only increases by 0.9. So in theory it takes me two consecutive 100TSS workouts to get back to where i was before the rest day. Surely this can not be right, any ideas?
Thank you

**Comment by ct2034** [comment]
Can you please add a screenshot or any data to reproduce you iasue
