### ISSUE TITLE
Cycling-style analysis view for running (only needs a link)

### ISSUE THREAD

**Issue by glenjamin** [thomaschampagne/elevate#438]
I recently discovered via a random buried forum post somewhere that it's possible to get the excellent cycling analysis page up for a run! It also seems to work for open water swims.

The trick is to use the following URL scheme `<activity>/analysis/0/0`. For some reason the /0/0 seems to convince the strava UI that it can do this - and it clearly can.

For an example, see https://www.strava.com/activities/1133541107/analysis/0/0

Perhaps Stravistix could add this link into the navigation?

**Comment by thomaschampagne** [comment]
@glenjamin Nice one :) ! I bring it into next v5.12.0

- Any idea for the feature name?
- Any idea for the title on left menu? "Analysis alternative" ?

(Sorry for the delay of reply. Seen your ticket today)

Tom

**Comment by glenjamin** [comment]
@thomaschampagne I'd be tempted to just make the "Analysis" word on the existing menu a link, but that might not be massively discoverable

Perhaps "Analysis Graph" or "Analysis Timeline".

Weirdly the element class in the HTML for this feature seems to be "basic-analysis"

**Comment by glenjamin** [comment]
I guess for feature name "Enable cycling-style analysis for running"

**Comment by thomaschampagne** [comment]
Thanks for your ideas :)
What do think about  "Detailed Analysis"? Since there is more info than default the graph in "overview"  section.

**Comment by glenjamin** [comment]
Sounds good to me

**Comment by thomaschampagne** [comment]
@glenjamin FYI I move this feature for release 5.13.0.
