### ISSUE TITLE
Chronological activity feed back (as an option)

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/elevate#473]

**Comment by jurgemaister** [comment]
#397

**Comment by mckennajones** [comment]
@thomaschampagne I have this working on initial page load. However, I was wondering what you thought the expected behaviour would be when you reach the bottom of the page and the new activities are loaded. Should the entire list resort? Just the new ones? Or something else? Thanks.

**Comment by thomaschampagne** [comment]
@mckennajones just read your comment today. Sry for delay...

You can checkout the veloviewer plugin (https://chrome.google.com/webstore/detail/veloviewer-strava-plugin/kdgpnlmocdpeckamipkkdblnfcpkgbno)

This plugin sort by start or upload time.

Simply sort  by start time? What do you think?

Sources are here: [vv.zip](https://github.com/thomaschampagne/stravistix/files/1692784/vv.zip)

**Comment by mckennajones** [comment]
@thomaschampagne Sure, Start Time sounds good. I'll have to look into how the activities are being loaded more carefully later in the week.

**Comment by thomaschampagne** [comment]
@mckennajones I postponed that ticket to v6.1.0

**Comment by thomaschampagne** [comment]
No problem. I can handle it or delay it.

**Comment by thomaschampagne** [comment]
closed by https://github.com/thomaschampagne/elevate/pull/649
