### ISSUE TITLE
Year progression (new) - custom season intervals

### ISSUE THREAD

**Issue by duhuni** [thomaschampagne/elevate#478]
Feature request:
The beginning of the season should be a customizable month. Many riders treat their season from November to October of the following year or similarly.

**Comment by jtufto** [comment]
I second this.  For the "nordic skiing" category, the "season" typically starts in October and ends in May.

**Comment by SundPer** [comment]
Season is also divided in different parts. Base, Build up, etc. Would be good to see different years but same part. Base is for an example, november--december, i.e. would be good to be able to choose trained hours, counts, km/miles, etc. between two dates. Great work!

**Comment by mhjartstrom** [comment]
I would also like to see this feature be implemented. Great work!

**Comment by steve78b** [comment]
I'd also like this feature, so I can start the cycling season after the skiing season.
