### ISSUE TITLE
Run pace zones are reversed

### ISSUE THREAD

**Issue by jfcharland** [thomaschampagne/elevate#486]
Merci Thomas pour ton travail sur StravistiX! C'est *vraiment* apprécié!

The new running pace zones are reversed, meaning that the slowest paces are represented as the highest zones (Z6, Z7 etc..). Normally, the slower paces would be the lower zones. 

The running power zones are good. Very useful. Thanks.

**Comment by TRIWOLF79** [comment]
Running pace zones are wrong, are reversed: Z1 should be the slowest pace, Z2 the next pace a bit faster, and so on. All zones in all sports are ordered from easy (Z1) to harder (Z2, Z3, and so on). I hope you can change that feature, as I'm sure for everyone is misleading.

Best regards

**Comment by lunarpropane** [comment]
Just wanted to add support for this change. HR Zones are proper, going from 1: easy to 10: hard. The Running Pace Zones should be switched to match the easy-to-hard escalation.

**Comment by Auke69** [comment]
The pace zones are still reversed!
zone 1 should be easy, and going up a zone should be harder!
The first comment is from 2017 and we are now 2019 but no changes.
Can we expect a change in the zones?

**Comment by joubex** [comment]
same problem. I would be happy to contribute if it works and I don't want to import my # 2400 workouts without a perfect settings (it would cost me a couple of days to do it again...)
Thanks for your job anyway: it seems to work for a lot of people, ...but not me  ;)
