### ISSUE TITLE
I no longer see a weekly and monthly progress bar on my annual goal on premium strava with strvistix.

### ISSUE THREAD

**Issue by bootheelbiker** [thomaschampagne/elevate#514]
**Bug description:** 

**Actual Behavior:** 

**Expected Behavior:** 

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
@bootheelbiker Thanks for reporting this to me

What happen if you disable stravistix in **chrome://extensions/** tab?

Do you have any screenshot or other ?

I need more info :) Thanks
