### ISSUE TITLE
Wrong counting of heart rate zones

### ISSUE THREAD

**Issue by danis7** [thomaschampagne/elevate#530]
**Bug description:** I have set heart rate zones when first zone - Z1 - starts on **120 bpm** ends on **132 bpm**. StravistiX does not count all time spent in Z1 correctly. StravastiX counts all time with HR 0 up to HR 132 as spent in Z1 (in my case of settings zones). 
Correctly it is only HR 120 bpm up to 132 bpm is time spent in Z1, HR 0 bpm up to 119 bpm is not in Z1. 
Stravastix and Chrome are actually.
Thank you for fix it

**Actual Behavior:** 

**Expected Behavior:** 

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
@danis7 Thanks to report

Hard to understand your problem :)

i'm releasing a new version (v6) today with new app. Let me know if fixed with that new app.

Close ticket if fixed ;)

Tom

**Comment by danis7** [comment]
Sorry for my english :)
Once more ... If I set in my first zone Z1 HR from 120 to 130 bpm so that StravastiX counts to Z1 HR with HR less than 120 too. e.g. time with HR 100 is counted to Z1 too.

**Comment by thomaschampagne** [comment]
@danis7 Sry, but i can't  catch it... Screenshot? Image?

**Comment by danis7** [comment]
Two screenshots, the same activity but different time spent in HR 120 - 132 bpm.
At first screenshot is Z1 with HR 120-132 bpm and second screenshot Z2 with HR 120-132 bpm (Z1 with 70-120 bpm).

![5_zones](https://user-images.githubusercontent.com/36600850/36355387-c59be01e-14e2-11e8-8734-7beb1b7755e2.jpg)
![6_zones](https://user-images.githubusercontent.com/36600850/36355388-c5b77c7a-14e2-11e8-935a-9cc614711ca5.jpg)
