### ISSUE TITLE
Export Fitness Trend Graph and Table

### ISSUE THREAD

**Issue by bizzehdee** [thomaschampagne/elevate#539]
Right now, there is an extremely useful graph and table in Fitness Trend. The one thing i find it lacks that i think would be useful for many, is a way to export the graph to a PDF, and the table to CSV or Excel.

It would export everything visible now, no background data, just the end result data, as shown on the graph and table.

**Comment by thomaschampagne** [comment]
@bizzehdee You can currently export the table to csv

**Comment by bizzehdee** [comment]
I have noticed, thank you
