### ISSUE TITLE
W/kg evolution in firness chart?

### ISSUE THREAD

**Issue by FabriceRimlinger** [thomaschampagne/elevate#554]
Could the fitness trend chart include a line showing the evolution of W/kg?

**Comment by jayti74** [comment]
would be really nice to have. but you would need to take a given time into focus. would be nice for the different power profiles: 5sec / 1min / 5min / 20min / 60min.
but that would also rely on a power profile feature like: https://www.trainingpeaks.com/blog/power-profiling/
that would require the power profile calculation on every ride. max power over different duration
