### ISSUE TITLE
Request for a new feature: Own Cycling Power Estimation by stravistix

### ISSUE THREAD

**Issue by Chrisx68** [thomaschampagne/elevate#575]
Strava is using its own cycling power calculation when no power sensor is used for the activity. 
see here: https://support.strava.com/hc/en-us/articles/216917107-How-Strava-Calculates-Power

However, not all parameter can be changed by the user in strava  app (e.g. rolling resistance or wind resistance).  But my experience is, that they do not allways fit very well. For example, when I use my mountain bike only on roads, the strava estimated power is far too high. 
So since stravistix has access to the activity raw data, i.e. speed, altitude as function of time of a cycling activity, an own calculation of the estimated power could be implemented. Individual parameters for the calculation could be then changed under stravistix setting.

**Comment by stelvio03** [comment]
I agree with Chrisx68. 
It would also be more complete if in the calculation weather conditions would have been taken into account. As far as I know weather underground should have API available to retrieve wind speed and direction ,for example
