### ISSUE TITLE
Feature enhancement: enable 'Best Splits' for running activities

### ISSUE THREAD

**Issue by harnbak** [thomaschampagne/elevate#576]
Please enable best splits for running activities as for available for cycling activities. In order to calculate Lactate Heartrate Threshold, I need to know my highest 60 min average heart rate as calculated for cycling activities: 
![image](https://user-images.githubusercontent.com/31338004/38772590-a86845a4-403a-11e8-8d88-59fd44fc14dc.png)

Today I find this by changing the Strava activity type from running to cycling to get access to Stravistix' 60 min best split. Afterwards I have to restore the Strava running activity type again. 

Thx

**Comment by aprokop** [comment]
@harnbak This is tangential, but have you looked at VeloViewer? They have a very nice customizeable best splits access.
