### ISSUE TITLE
1st time sync fail

### ISSUE THREAD

**Issue by MFB99** [thomaschampagne/elevate#596]
### Step 1: Are you in the right place?
Upon first sync Global synchronisation progress stalls at 54%.
Chrome 66.0.3359.181 
Stravavisitix 6.0.1
My activities folder is too big to attach.  185MB

Thanks in advance,

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/stravistix/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
What is the error displayed (just copy paste) when you press F12 during sync process?
