### ISSUE TITLE
HRSS not copying to Fitness trend page

### ISSUE THREAD

**Issue by namasteve** [thomaschampagne/elevate#599]
### Step 2: Describe your environment

  * Plugin version: Plugin version: 6.2.1 Stable
Angular Core version: 5.2.10
Angular Material version: 5.2.5
D3js version: 4.13.0
_____
  * Chrome/Opera/Chromium version: Chrome version 66.0.3359.181
  * OS version: Windows 7 Enterprise SP 1
  
### Step 3: Describe the problem:
As of May 21, 2018 rides, HRSS does not copy from Strava activity to Fitness Trend page. B/c of this, fatigue and form do no calculate propertly. Individiaul activities in Strava still have HRSS calculations.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
You mean HRSS from strava activity and Fitness Trend didn't match? You probably changed your heart rate settings. If you clear your history and resync. Numbers will match
