### ISSUE TITLE
Extended stats panel,  elevation units

### ISSUE THREAD

**Issue by amokrunner** [thomaschampagne/elevate#605]
The elevation in the extended statistics panel is in meters despite my selecting imperial units in my options

**Comment by mnebelsick** [comment]
Extending this issue to also include the Best 20 Speed on the extended stats panel, this one also looks like the value is the metric one (units still show Mi/H) despite selecting imperial units in the options.  (Missed conversion).

**Comment by rymalia** [comment]
Bumping this one up. This is still an open issue: the elevation sections are not following the App System Units setting for Imperial, it only displays the elevation stats in Meters and also in the Zones panel for elevation zones, that continues to be Metric as well.
