### ISSUE TITLE
VO2 MAX

### ISSUE THREAD

**Issue by mkonzen** [thomaschampagne/elevate#606]
Could you implement the VO2 MAX like Garmin Connect already uses for running?
I was trying to figure out a way to calculate my VO2 MAX in cycling also but the app i found doesn't support my device and i don't have a powermeter yet...

![capturar](https://user-images.githubusercontent.com/38529992/40807223-16c2bb40-64fa-11e8-9e21-532b00f62d12.JPG)

**Comment by thomaschampagne** [comment]
Hi,

Can you provide me the maths :) ?

Ty

**Comment by devon-badman** [comment]
I think Garmin use Firstbeat for their VO2 max estimation.

https://assets.firstbeat.com/firstbeat/uploads/2015/10/white_paper_VO2max_11-11-20142.pdf

They plot a chart of speed vs heartrate, then extrapolate to reach max heartrate and determine the maximum speed. They then have a table of activity speed to VO2 and use that to work out the theoretical VO2max.

They also split the data up into segments and ignore the ones with low speeds, erratic data etc.

**Comment by mkonzen** [comment]
@devon-badman 
do you know if there is a way to calculate the cycling vo2max without a powermeter?
