### ISSUE TITLE
Enable Generic Extended stats

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/elevate#617]
Re-opened:
- [ ] Add generic speed/pace zones before release

**Comment by thomaschampagne** [comment]
- [ ] Add generic speed/pace zones before release

**Comment by tomfiv** [comment]
An option, if it's hard to make generic speed/pace zones might be to simply show a pace/speed distribution graph?
At least for me the heart rate zones is the most important aspect of the extended stats.

**Comment by tomfiv** [comment]
Another graph that would be interesting in the extended stats is a distribution graph (or zones, if it's possible to make them generic) that shows elevation gained per minute (m/min or ft/min).
