### ISSUE TITLE
Feature Request: Add option to ignore heart rate and calculate Fitness Trend only on Threshold Running Pace

### ISSUE THREAD

**Issue by coops9309** [thomaschampagne/elevate#628]
### Step 3: Describe the problem:

Fitness trend uses heart rate data, if available, to determine the stress from a particular training run. Fitness trend can also calculate stress based on Functional Threshold Pace for runners, if Heart Rate data is unavailable. 

Many runners use an optical, wrist-based optical heart rate monitor to track heart rate, especially for runs where tracking an accurate HR isn't critical. Sometimes, the wrist-based HRM works great, other times it locks onto cadence and can have very inaccurate readings. 

Here's an example activity where recorded heart rate is accurate: https://www.strava.com/activities/1633571229
Here's an example activity where recorded heart rate locked on to cadence, and is inaccurate: 
https://www.strava.com/activities/1635775831

The problem is when HRM recorded is inaccurate (most commonly too high), the stress calculated for a particular run is inaccurate (typically, way too high).  
  
#### Expected Behavior:

Ideally, I'd like to be able to force Fitness trend to ignore heart rate, and instead always use a specified Functional Threshold Pace to calculate stress for a given activity.

**Comment by IrieDevelopment** [comment]
+1.  I've had some runs record bad HR data (peaks at 235, wow!) and it totally screws up the HRSS and fitness trend.  Some manual ability to ignore the recorded HR data would be nice.
