### ISSUE TITLE
Grade Adjusted Pace graph is blank

### ISSUE THREAD

**Issue by amokrunner** [thomaschampagne/elevate#633]
### Step 2: Describe your environment

  * Plugin version: 6.4.1 Stable
  * Chrome/Opera/Chromium version: 67.0.3396.99
  * OS version: Windows 10
  
### Step 3: Describe the problem:
Since the last upgrade, the Grade Adjusted Pace graph under Extended Statistics is empty

#### Steps to reproduce:

  1. Go to an activity
  2. Click "Show extended statistics"
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console? NO

  > Press F12 to see developer console and javascript logs

  ```javascript
localStorageMustBeCleared is now false
blob:https://www.strava.com/c4dfa772-5d6e-4cfa-be53-ac3d5173a4c7:28 Trying to estimate wattage of this run...
boot.bundle.js:78 Creating activity cache
boot.bundle.js:66 A previous sync exists on Mon Jul 16 2018 06:36:08 GMT-0700 (Pacific Daylight Time)
boot.bundle.js:66 Fast sync mode enabled
boot.bundle.js:78 Using existing activity cache mode
boot.bundle.js:66 Local and remote activities count matches.
boot.bundle.js:66 Last sync date time saved:  Mon Jul 16 2018 06:36:48 GMT-0700 (Pacific Daylight Time)
boot.bundle.js:66 Fast sync finished Object
boot.bundle.js:78   ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by amokrunner** [comment]
![untitled](https://user-images.githubusercontent.com/29108942/42761769-5126d32e-88c3-11e8-9532-e559f15a8139.png)

**Comment by dg001** [comment]
I've had the same issue for months now, everything else works correctly.
![image](https://user-images.githubusercontent.com/18539352/45942216-7a920b00-bfd9-11e8-943d-eff3159643ee.png)

**Comment by Cedric-Pion** [comment]
Same thing here https://www.strava.com/activities/1879223510/overview# . I have never seen this feature working. The pace and grade data look ok though.
<img width="1325" alt="screen shot 2018-10-02 at 16 06 36" src="https://user-images.githubusercontent.com/43785505/46353958-b07c6280-c65d-11e8-9a4f-ac414b815136.png">
<img width="1316" alt="screen shot 2018-10-02 at 16 07 54" src="https://user-images.githubusercontent.com/43785505/46353967-b70ada00-c65d-11e8-9f6e-3884546634b0.png">
