### ISSUE TITLE
New Feature proposal: Power Curve

### ISSUE THREAD

**Issue by akrzysztofek** [thomaschampagne/elevate#636]
**Feature description:**
There is one feature StravistiX seems to be lacking when compared to Strava Premium - **Power Curve**
This could be very nice addition to current set of features. 

![image](https://user-images.githubusercontent.com/14838837/43097524-9f0b9774-8ebc-11e8-84fa-2ebce1a3c718.png)

**Comment by thomaschampagne** [comment]
@akrzysztofek You right i had this in mind.

I already coded the "logic" to compute this curve (=calculate splits from any time value) few weeks ago with that class: https://github.com/thomaschampagne/stravistix/blob/develop/plugin/core/scripts/processors/SplitCalculator.ts

Just need to provide UI & Graph. But no time to put in on this at the moment. Others features are on roadmap at first.

**Comment by hatspencer** [comment]
Where did you move that class? I could not find the corresponding commit. Would try and play around with a UI :)
