### ISSUE TITLE
Feature request: Include gear (different bikes/shoes) in the Year progressions

### ISSUE THREAD

**Issue by kwaaak** [thomaschampagne/elevate#644]
Hello,

it would be cool if the graph in Year progressions had a different colour for each bike or shoe.
Also, showing the graph just for a specific bike or shoe.

**Comment by parkstraat9** [comment]
Same request here, 
Would be great to see the difference between my road/mtb/fatbike 
and to see in which periode I use which bike the most. 
colored lines per bike displayed over the year.

**Comment by st3inar** [comment]
I would like this aswell. It would be greatfor scheduling service of suspension components on a bike which is normally in intervalls of 50 hours or 200 hours.

Another good thing would be to include the hour count on the activity page on strava alongside the odometer for the bike used on cycling activites.
