### ISSUE TITLE
In Athlete Settings LTHR always goes back to default.

### ISSUE THREAD

**Issue by jung1es** [thomaschampagne/elevate#650]
* Plugin version: 6.4.2
  * Chrome 
  * OS version: Win 7
  
In Athlete Settings LTHR always goes back to default.

#### Steps to reproduce:

Try to change default LTHR - say to 180, from 169 (in any of three boxes)
Can enter numbers or use arrows. Looks like it's changed ok.
When you reopen at a later time it's back to the default.
All the other variables on page, i.e. FTP are fine.

**Comment by thomaschampagne** [comment]
Thanks for report. It's a known issue.
Check https://github.com/thomaschampagne/stravistix/issues/641 for a workaround.
