### ISSUE TITLE
Feature request: Show "Best 60min HR"

### ISSUE THREAD

**Issue by Chrisx68** [thomaschampagne/elevate#654]
In addition to "Best 20min HR" a similar statistics "Best 60 min HR" would be great.

Reason: 
The 60 min duration is better for estimating the HR@Lactate Treshold than 20 min.  The "Best 20min HR" is overestimating the HR@LT.

**Comment by Strajk** [comment]
@Chrisx68 Where could **Best 20min HR** be found please?
