### ISSUE TITLE
Rename project to "Elevate"

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/elevate#661]

**Comment by aprokop** [comment]
May I ask why? It felt that Stravistix was easier to remember.

**Comment by thomaschampagne** [comment]
Of course your question is legit :)

In fact I experienced the opposite too many times since 3 years with most of people. That's why i'v been motivated to change it (with reluctantly). Writing was complex. Pronunciation too: difficult to share it orally.
