### ISSUE TITLE
Request: RSS from Manual Entry Run

### ISSUE THREAD

**Issue by amokrunner** [thomaschampagne/elevate#663]
It would be awesome to get RSS from a manual run entry on Strava. It seems like there should be enough information from a manual run to get some kind score. Time, distance, pace, elevation. Even if it's not very accurate, it would be better than nothing in my opinion. As the days are getting shorter I'll be on the treadmill more and I'm trying to figure out how to make those treadmill workouts show up in my fitness trend. Thanks!

**Comment by Strajk** [comment]
@amokrunner Estimated RSS was added quite recently – Is this what you meant?
https://twitter.com/champagnethomas/status/1016386857935015936

It's working great for my treadmill runs and outdoor runs without sports tracker

![2018-10-07 08 24 29](https://user-images.githubusercontent.com/697301/46579021-9b5f5500-ca0a-11e8-82fa-95dd8daaf01d.gif)

**Comment by amokrunner** [comment]
Hi @Strajk - yes this would be an addition to the estimated RSS. If I go to Strava website (or app) and manually enter a run (where you just type in distance, elevation, and time), I do not get an estimated RSS calculated for those activities. Is this how you capturing those treadmill workouts?

**Comment by RunOFX** [comment]
I have this same question. I expected the Estimated RSS to do this, but today I added a treadmill run manually and no RSS showed up even though I have the function turned on and a running FTP entered. What are you doing @Strajk ?

**Comment by thomaschampagne** [comment]
@amokrunner @Strajk @RunOFX The PR https://github.com/thomaschampagne/elevate/pull/751 will close that ticket. I invite you to test a build available in https://github.com/thomaschampagne/elevate/pull/751 and to comment in the same PR your bugs or suggestion. Thanks for your help !

**Comment by thomaschampagne** [comment]
Closed by https://github.com/thomaschampagne/elevate/pull/751
