### ISSUE TITLE
Cannot syncronize due to  "Uncaught Error: Cannot deserialize zones"

### ISSUE THREAD

**Issue by zanza00** [thomaschampagne/elevate#666]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.6.0 Stable
  * Chrome/Opera/Chromium version: Chrome 69.0.3497.100 (Official Build) (64-bit)
  * OS version: Mac OS X 10.14 Mojave
  
#### Steps to reproduce:

  1. login to strava
  2. open elevate and start a sync
  3. Sync fails
  
#### Actual Behavior:

it fails at the first [activity](https://www.strava.com/activities/1893432475)

  > Press F12 to see developer console and javascript logs

  ```javascript
 activityId: 1893432475
errObject: ErrorEvent
bubbles: false
cancelBubble: false
cancelable: true
colno: 95508
composed: false
currentTarget: Worker {onmessage: null, onerror: null}
defaultPrevented: false
error: null
eventPhase: 0
filename: "blob:https://www.strava.com/0bcc383c-35e1-4320-83d4-b7e0185feadf"
isTrusted: true
lineno: 1
message: "Uncaught Error: Cannot deserialize zones"
path: []
returnValue: true
srcElement: Worker {onmessage: null, onerror: null}
target: Worker {onmessage: null, onerror: null}
timeStamp: 9479.60000000603
type: "error"
  ```

[I looked at the code](https://github.com/thomaschampagne/elevate/blob/76d3ccdd599068e20611d875efee2e8c77898691/plugin/core/scripts/shared/models/user-settings/user-zones.model.ts#L70) and it appears that the zone is not a number.

#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

cannot sync so no exports

**Comment by MigoMueller** [comment]
I have the same issue on an existing Elevate (6.6.0 Stable) install (previously Stravistix) on Chromium 57.0.2987.98 Built on 8.7, running on Debian 8.11 (64-bit).  Syncing recent activities has failed for the last few days (since the upgrade to elevate).  I tried syncing all activities as well as "clear and resync" to no avail. 

Interestingly, I do _not_ have this problem on my MacBook running Chrome.  All settings are identical between my two machines as far as I can tell.

**Comment by thomaschampagne** [comment]
Hi,

Can you reproduce using that debug build: [debug_v6.6.0.zip](https://github.com/thomaschampagne/elevate/files/2461091/debug_v6.6.0_stable_2018-10-09-15-30.zip)

And provide me the stacktrace you got for this error?

Ty !

**Comment by zanza00** [comment]
I tryed with the git version and with the debug version that you provided and I __cannot__ reproduce the problem

I reinstalled the published extension and I was able to import it.

Tomorrow I will try again after I sync a ride and report back, I think it's related to Strava

**Comment by thomaschampagne** [comment]
I think it's caused by an error in upgrade to 6.6.0.

In file:
https://github.com/thomaschampagne/elevate/blob/develop/plugin/core/scripts/installer.ts

Method migrate_to_6_6_0()

**Comment by MigoMueller** [comment]
I didn't go as far as installing the debug build, but deleted the extension and re-installed it.  That fixed the issue for me.
Ping, new comment from Thomas. Yes, your idea could explain my issue easily.

**Comment by zanza00** [comment]
This make sense.

I had stravistix ages ago, when I tried the debug version I had to uninstall the old version first, this erase the extension data.

For me this is closed, maybe add it to the faq or something?
