### ISSUE TITLE
Fitness Trend - Form: todays -> tomorrows Form

### ISSUE THREAD

**Issue by jayti74** [thomaschampagne/elevate#670]
Dear Thomas,

thanks for Elevate and pushing the App to what it is today.

I don't know if it has been discussed yet: in Fitness Trend the displayed Form is actually the Form of tomorrow.

Form by definition is (TrainingPeaks):
Training Stress Balance (TSB) or Form represents the balance of training stress.

Form (TSB) = Yesterday's Fitness (CTL) - Yesterday's Fatigue (ATL)

https://help.trainingpeaks.com/hc/en-us/articles/204071764-Form-TSB-

Maybe you can consider that.

Thanks a lot.

**Comment by aprokop** [comment]
A duplicate of #579.

**Comment by jayti74** [comment]
thanks to @aprokop . duplicate of #579 . closed
