### ISSUE TITLE
I think the app is calculating form with delay or not right after the hour change (Oct28)

### ISSUE THREAD

**Issue by retonho** [thomaschampagne/elevate#681]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions? YES
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues? YES

### Step 2: Describe your environment

  * Plugin version: 6.7.0 (Stable)
  * Chrome/Opera/Chromium version: Chrome 70.0.3538.77 (Build oficial) (64 bits)
  * OS version: Windows 10 PRO
  
### Step 3: Describe the problem:

Ran a half marathon on Oct-28 at a very high intensity. Fitness and Fatigue got high as usual. Form got lower. From next day on, there was a delay between Fitness/fatigue and Form. Form is one day behind the other two.

#### Steps to reproduce:

  1. Run the day the hour of your country is changed (was changed from 3 am to 2 am)
  2. Delay

  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

The app doesn't have errors per se. It's the calculation.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
Fitness - Fatigue = Form, for every day
  
#### Media attachement:

Done

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

Can't do it

**Comment by retonho** [comment]
![elevatedelay](https://user-images.githubusercontent.com/17582354/47964587-6b709500-e03c-11e8-8e8d-4b0c73c32849.png)

**Comment by retonho** [comment]
The other user hasn't got a clue about the issue, but i think it looks like they're similar problems. Mine only started to work wrong since that date. Everything before October 28th seems to be right.

**Comment by thomaschampagne** [comment]
So the form drops the day after your efforts right? It seems on graph. DST off too.

The clue is here about form calculated on yesterday efforts: https://help.trainingpeaks.com/hc/en-us/articles/204071764-Form-TSB-

**Comment by thomaschampagne** [comment]
Closing the ticket because everything looks ok to me. You can reopen it if necessary. Thanks
