### ISSUE TITLE
A mistake in calculation of my fitness trend

### ISSUE THREAD

**Issue by puzanart** [thomaschampagne/elevate#682]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.7.0
  * Chrome version: 70.0.3538.77
  * OS version: High Sierra 10.13.6
  
### Step 3: Describe the problem:

I think I've got a mistake in calculation of my fitness trend on 29.11.18 and it influences all further days.
I had a workout that day and my fatique increased by 7,5 points, fitness by 0,8 points but form also went up instead of going down by 6. The chart in Strava confirms my concerns.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?

I expect the calculation to be fixed

#### Media attachement:

>You can upload/attach any images to this ticket.
![2018-11-05 12 06 17](https://user-images.githubusercontent.com/38040604/47988782-345dba80-e0f4-11e8-8292-3efd4c1dab43.png)
[2018.11.5-12.12_v6.7.0.history.json.zip](https://github.com/thomaschampagne/elevate/files/2547602/2018.11.5-12.12_v6.7.0.history.json.zip)

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by aprokop** [comment]
Consult release notes or #579 for the explanation.

**Comment by puzanart** [comment]
Understood. Thanks.

**Comment by thomaschampagne** [comment]
@puzanart You're welcome. As @aprokop asked:

>what is the chart in Strava that you mentioned?

Thanks :)

**Comment by aprokop** [comment]
Hmm, I looked online and people *did* notice that Strava's calculations are different from TrainingPeaks.
