### ISSUE TITLE
Invalid stress score generated for manually entered runs from 2016

### ISSUE THREAD

**Issue by oakmiller** [thomaschampagne/elevate#683]
###
[2018.11.5-10.33_v6.7.0.history.zip](https://github.com/thomaschampagne/elevate/files/2549377/2018.11.5-10.33_v6.7.0.history.zip)
![example](https://user-images.githubusercontent.com/11276731/48007993-c959b700-e0e6-11e8-88ab-0a413b844878.gif)

 Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions? Checked, not found.
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues? Checked, not found.

### Step 2: Describe your environment

  * Plugin version: _____6.7.0 Stable
  * Chrome/Opera/Chromium version: _____Version 70.0.3538.77 (Official Build) (64-bit)
  * OS version: _____ Win7
  
### Step 3: Describe the problem:
7 digit stress scores being calculated for some 2015 and 2016 treadmill manual activities.

#### Steps to reproduce:

  1. Go to Fitness Trend.
  2. Under the Last drop down select Since beginning.
  3. The 7 digit stress scores stick out.
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console? No

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen? A two digit stress score?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by cwasmer** [comment]
I have this problem as well. I don't have any manually entered runs though. Seems to be an issue for treadmill runs only.

**Comment by aprokop** [comment]
Most likely it stems from `"genuineGradeAdjustedAvgPace": -1` in the attached extended stats.

**Comment by quocamus** [comment]
I am having the same issue with treadmill runs. They are not manually entered, but recorded with a watch. RSS is seven digits and throws off the whole fitness trend. Grade adjusted pace in the extended stats is negative.
