### ISSUE TITLE
Form calculated wrongly

### ISSUE THREAD

**Issue by dekruyff** [thomaschampagne/elevate#684]
According to the formula Form = Fitness - Fatigue, my form is not calculated correctly since a few days. Today it says: 

Fitness 36.3
Fatigue 31.6
Form 0.6

Can't figure out why.

**Comment by aprokop** [comment]
Duplicate of #682 and others. Please consult release notes or #579 for the explanation. In short, the correct calculation of Form is based on *yesterday's* fitness and fatigue.
