### ISSUE TITLE
All my achievements have disappeared 

### ISSUE THREAD

**Issue by vunag** [thomaschampagne/elevate#689]
Env:
I am using apple watch, IOS IPhoneX and my chrome on the laptop
Problem Description:
In the last two rides (Mountain biking) I noticed that there are no segments then I discovered that funny enough that my default was changed to handcycle as an activity instead of ride
When changing that back I see the segments but no achievements.
On top of that some of my achievements no longer appear in my history of activities
Can you help get to the bottom of this and fix that.
I can only say that recently I had to change my IPhone and restore from backup and resync my watch with it.
Thanks,
Vunag

**Comment by thomaschampagne** [comment]
Ask strava support for this. Not elevate problem
