### ISSUE TITLE
Feature Request: Calcualte stress without HR

### ISSUE THREAD

**Issue by SteveDrakey** [thomaschampagne/elevate#697]
I understand that the app can estimate stress based on data  you give it.

Please could you consider this use case 

- A rider rides a few times a week, most of the time they use a HR monitor. 
- The rider forgets the HR monitor for the od ride, so they get gaps.
- The rider does not know his or her 'Cycling Functional Threshold Power' etc.

It would be very nice if the app just kinda worked it out, it could just look at previous rides to work this out, for a very crude stress score I guess it could just look for a ride within 1 month (before or even after when you are back filling 5 years worth)  that is about the same length with about the same amount of climbing and use the stress score from that. 

As a mountain biker I try to maintain my fitness for them big , rocky, steep climbs that the extra fitness can help you have the extra push for that little step up, or be the difference between having to jump of and push up or be able to ride it. I don't think us mountain bikers measure the same stats as a road biker does. 

This would be awesome for historic data, I have so many gaps in my fitness and I would like to cross reference this against my times on some of the climbs. 

Awesome App btw, love how you use Angular in a chrome extension, kinda inspired  me to do the same for an extension that allows blind people to use SharePoint without any server side code changes (hopefully this will be open source soon)

**Comment by SteveDrakey** [comment]
Thanks for replying.

Which would be the most fun to code? Is that not the question ;) 

Deep learning would be an awesome addition, I guess in very simple terms you would just give it all the numbers  (miles, time, elevation, temp, wind-speed) and tell it the stress score and once it had enough data it would be able to tell you what it thinks is the stress score. 

But, maybe starting very simple would be good maybe just look at stress per mile for a given ride area that the rider rides in, if rider rides in the same area without a HR monitor then just use that data.

Right now it requires  Cycling Functional Threshold Power, how many cyclist know this? Maybe road riders do but none of the riders I ride with could tell me theirs. (but I ride with MTBers)

**Comment by amokrunner** [comment]
I've thought about this too. Being a runner, this would be an awesome improvement for running as well. Possibly it could be as crude as estimating the FTP for each activity w/ HR data, then using the moving average of the last X activities' estimated FTP for the next one without HR data.
