### ISSUE TITLE
Years Progression Graph + Virtual Rides 

### ISSUE THREAD

**Issue by jcaude** [thomaschampagne/elevate#700]
### Step 1: Are you in the right place?

This issue is different from #129 and #159

### Step 2: Describe your environment

  * Plugin version: 6.8.0
  * Chrome/Opera/Chromium version: 70.0.xxx
  * OS version: OS/X 10.14
  
### Step 3: Describe the problem:

Virtual rides doesn't appear in the years progression graph, while they are displayed in the fitness graph and optionally on the profile year progressions. Note that the indoor check box does not work here as, if I am correct, it includes activities (manual in my case) with distance but no path (gps) data.
  
#### Expected Behavior:

Let the indoor activities checkbox also include virtual activities (ride or cycling)

**Comment by thomaschampagne** [comment]
@jcaude Can you provide a backup from the app?

**Comment by jcaude** [comment]
sure...
[2018.11.22-14.56_v6.8.0.history.json.zip](https://github.com/thomaschampagne/elevate/files/2608305/2018.11.22-14.56_v6.8.0.history.json.zip)

**Comment by jcaude** [comment]
I have another issue with the progression graph page. When I set a target the right table doesn't displayed the delta to target for the current day (but it does for previous days). As it may be related with the current issue (my last activity is a virtual ride) I will wait for your feedback before. Anyway, tell me if you want me to open a new issue.

<img width="574" alt="capture d ecran 2018-11-22 a 15 04 57" src="https://user-images.githubusercontent.com/1268176/48907507-fdafd000-ee67-11e8-990a-eba2efe9df3e.png">

**Comment by thomaschampagne** [comment]
@jcaude They should appears, you just have 2 recent virtual rides done with tiny one.

For other problem, strange :/ Yes please create a ticket with all detailed steps to reproduce your bug.

Ty

**Comment by jcaude** [comment]
Exactly ... just put some flux in my training ;-)  seriously, my last two activities are indeed these two virtual rides. I open a new ticket for the second issue.

**Comment by thomaschampagne** [comment]
If no problem anymore here, you can close ticket.

Ty

**Comment by jcaude** [comment]
ok.
