### ISSUE TITLE
Presets not really deleted on year progression graph

### ISSUE THREAD

**Issue by jcaude** [thomaschampagne/elevate#702]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.8.0
  * Chrome/Opera/Chromium version: 70.0
  * OS version: OS/X 10.14
  
### Step 3: Describe the problem:

After deleting all presets/targets the YP graph still contains the linear regression and the table still ahs the delta-target column (even after a page reload).

#### Steps to reproduce:

  1. Create a preset
  2. Play with it..
  3. Delete the preset
  
  * Do you have javascript errors logs in browser console?

nope

**Comment by thomaschampagne** [comment]
Good call. I will handle that. 

I think we can simplify the behaviour like this: 

- [ ] Clear target line if the associated preset has been deleted.

Right?

**Comment by jcaude** [comment]
Definitely ..

**Comment by thomaschampagne** [comment]
Test build: https://bitbucket.org/thomaschampagne/elevate-ci-builds/downloads/v6.8.0_stable_2018-11-23-11-58.develop.94d82978.zip

You can reopen ticket if needed

**Comment by jcaude** [comment]
Also test this one..
