### ISSUE TITLE
Running Index: New feature?

### ISSUE THREAD

**Issue by Chrisx68** [thomaschampagne/elevate#704]
I could provide a code to calculate a Running Index based on the heart rate and speed data. The Running Index would show you how efficient you are running and the value would be close to the Running Index of Polar TM (see here https://support.polar.com/en/support/tips/Running_Index_feature). The higher the value, the better is your running performance.

This would be another good feature of elevate!

**Comment by lkj19zpdiDDe** [comment]
I'd be interested in learning more about the index, and I may have the time to implement it.

**Comment by Chrisx68** [comment]
That would be great. I could send you more information how it is calculated and also the code for a garmin data field for this.  Please let me know where to send.

**Comment by lkj19zpdiDDe** [comment]
Attaching it to the ticket would be great.

Also, just to confirm, are you the owner of the calculation and donating it to the project or is the calculation public information?  (I'm extra cautious on IP and confidential information protection.)

**Comment by OndrejSpanel** [comment]
I already had a PR #386 which aimed to compute both running and biking index and displayed it in the fitness graph. The PR was before a big refactorization, I am not sure what are the chances of it being ever merged, it is closed now with a reference to #549

**Comment by Chrisx68** [comment]
Yes I am the owner of the calculation and would donate it for the project. 
What I did was fitting the running performance prediction table which available on polar's website: https://www.polar.com/en/smart_coaching/features/running_index/chart 
The result of the fitting was a formula for the running index (left column) based on the running speed and distance. This formula is valid for runs when performing maximal. In a second step a correction was added to take into account also runs at submaximal Heart rates. The basis for this correction was own data as well as public available data. 
So in my opinion there is no IP violation as the chart on polar's website is public information and the calculation is done by my own. To be on the safe site, we could call it "running performance index" to be different to polar. 

The following parameters are needed:
t             running time (minutes)
d            Equivalent running distance (meters)   d = run distance (from strava) + 6*up - 4*down
              This takes into account when the track is hilly. d is the equivalent distance for a flat track. 
              up       ascent meters of the run
              down  descent meters of the run
HR         Mean heart rate
HRmax  Maximum Heart rate

Calculation:

Running Index = RI0 / x
RI0 = 213.9 / t * (d/1000)^1.06 + 3.5
x =  HR/HRmax * 1.45 - 0.30   (x should be truncated to 0..1)

**Comment by lkj19zpdiDDe** [comment]
@Chrisx68 Thanks for the details. I've tested the calculation with my recent runs, and it looks predictive to me. 

@OndrejSpanel Any feel for this approach vs. your original approach? Is one more predictive than the other? I also like how your version also works for biking.

**Comment by OndrejSpanel** [comment]
The computation looks similar, however at least the `- 0.30` part at the end of the formula should be replaced with proper compensation for standing HR. The result will be very similar for most people, but for people with unusually low or high standing HR I think using their standing HR will be more precise. I will try to do more detailed comparison in a few days, too busy now.

The crucial part of the article I was basing my work on is:

> To calculate the baseline value, you start with two data points: your standing heart rate at rest (which corresponds to a running speed of zero), and your heart rate and running speed at VO2max. Then you draw a straight line between those two points, because research shows that speed increases as a roughly linear function of heart rate (as long as you're not going too close to all-out). That gives a straight line that tells you, in theory, what speed should correspond to what heart rate (and vice-versa).

See [Tracking Fitness With the "Heart Rate-Running Speed Index"](https://www.runnersworld.com/training/a20829802/tracking-fitness-with-the-heart-rate-running-speed-index/)

**Comment by lkj19zpdiDDe** [comment]
PR 790 (https://github.com/thomaschampagne/elevate/pull/790) created for this. (Since this is my first time in the code, I'm sure I've missed things and the review might take a while.)

@OndrejSpanel I reviewed the article and prior implementation, and I couldn't get the index to be consistent across my runs.

**Comment by Chrisx68** [comment]
Here is a figure which shows the correlation between the running index by polar (y axis) versus the result using the above mentioned calculation (x axis). The fit is very close to polar's result.
![image](https://user-images.githubusercontent.com/38325046/54073114-ad784480-4283-11e9-9cd7-9973d6bf2d07.png)

**Comment by Chrisx68** [comment]
>@OndrejSpanel   The computation looks similar, however at least the `- 0.30` part at the end of the formula should be replaced with proper compensation for standing HR. 

Here is the basis for the correction (based on more than 100 runners). It follows very well the equation y=1.45 x HR/HRmax - 0.30.


![image](https://user-images.githubusercontent.com/38325046/54073221-e95fd980-4284-11e9-987b-591962b7e42a.png)

**Comment by OndrejSpanel** [comment]
I am not sure I understand what do you correlate to what. Are you correlating your performance index against the polar index, or against some objective or subjective running performance?

**Comment by Chrisx68** [comment]
It's the first: I am correlating my running performance index against the polar running index. The data were taken from the polar flow website.
The second figure shows the correction factor x against the heart rate in % of HRmax. Did that help you?

**Comment by OndrejSpanel** [comment]
Thanks for explanation. The high correlation therefore says you almost precisely estimated how Polar computes their index.   I am not much convinced polar running index is a meaningful way to indicate a performance, though. The article I am referring to seems more reliable to me, as they publish what data are they based upon and refer to the study. I think am not the one to judge and accept or reject this eventually, though.

**Comment by thomaschampagne** [comment]
Closed by PR https://github.com/thomaschampagne/elevate/pull/790. Now on develop

**Comment by jonaganoj** [comment]
Thanks for a great index.  I have a question;

I have looked at the formula given by [Chrisx68](https://github.com/Chrisx68): 
Running Index = RI0 / x
RI0 = 213.9 / t * (d/1000)^1.06 + 3.5
x = HR/HRmax * 1.45 - 0.30

Since (d/1000)^1,06, the distance in km is only used in the exponential expression (^1,06), (and not for example t/d -  the pace), the index will be higher the longer the distance, even if the speed and HR is constant.  Is this correct and as it is implemented in elevate?  Or have I understood the formula wrongly?

**Comment by Chrisx68** [comment]
The idea behind is the equivalent running performance as also described here:
https://wismuth.com/running/calculator.html
When you run 20km instead of 10km you will need more than twice the time as your speed will decrease with longer distances. This fact is considered in the exponent 1.06. With the same performance (same RI and HR), doubling the distance will increase the running time t by factor of 2.085 (=2^1.06). Does this answered your question?

**Comment by Chrisx68** [comment]
The idea was to be as close to the Polar's running index as possible. And the RI by Polar is also dependent on the total distance as it can be seen from Polar's [table](https://www.polar.com/en/smart_coaching/features/running_index/chart).  For the same RI, doubling the distance (e.g. from 5 to 10 km) leads to more than twofold longer running time. 
Actually, Polar claims on their website that the RI is an estimation of your maximal oxygen uptake Vo2max. So in my opinion it can be used to estimate your vo2max.

**Comment by jonaganoj** [comment]
I thought vo2max was mostly connected to the absolute speed or pace of running and not length.  if I run 1 or 2 km at say an aerob level (submax) I did not expect the VO2 consumption to change.  But, there might be much more complex relationsships than I am aware of.
Of course when length really increases other aspects come into play, for instance glucogen levels, efficiency, etc.

thanks for the insights :-)

**Comment by Constantinesane** [comment]
i use both polar and elevate and i can say that elevate equation stays more consistent from run to run than polar's. This doesnt says much of course also in this kind of data it is better to look at the trends. My best friend who is an triathoner found that the fitting trend of the polars running index matches his tested vo2max with little error. Also have in mind that there is a table to convert polar's running index to vo2max there are not supposed to be equal
