### ISSUE TITLE
Dated Athlete Settings effective date changes without explanation

### ISSUE THREAD

**Issue by dlh3** [thomaschampagne/elevate#705]
### Step 1: Are you in the right place?

Yes.

### Step 2: Describe your environment

  * Plugin version: 6.8.0 Stable
  * Chrome/Opera/Chromium version: Chrome 70.0.3538.102
  * OS version: MacOS 10.14
  
#### Steps to reproduce:

  1. Open Athlete Settings
  2. Add new dated athlete settings
  3. Set the "Athlete settings since" date (either by typing the date, or with date picker)
  4. Click out of the "Athlete settings since" field
  
#### Actual Behavior:

  * The date changes to the day before (if you entered 11/11/2018, it becomes 11/10/2018)
  
#### Expected Behaviour:

  * I suppose this is the expected behaviour, but that isn't obvious.  Perhaps a note add to that field would reduce confusion.
  
#### Media attachment:

None.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

Not related to specific activities.

**Comment by thomaschampagne** [comment]
@dlh3 I can't reproduce your problem :/ Pb still there?

**Comment by dlh3** [comment]
Here's a screen recording to demonstrate the reported behaviour.  First I type a date (11/19/2018) into the "Athlete settings since" field, then when I click out, the value moves to the previous day (11/18/2018).  Next I use the date picker to select a date (11/21/2018), but when the date picker closes, the "Athlete settings since" field is the previous day (11/20/2018).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/648035/50070964-f341d700-0184-11e9-80f7-cf912dac5bc2.gif)
(sorry for the small size, you may need to zoom in)

Once again, I am guessing this is the intended behaviour.  If so, that is fine, but I think adding an explanation note to the field could reduce confusion so other people don't think it is a bug (as I did).

**Comment by dlh3** [comment]
@thomaschampagne thanks to @cwparsons, I think I know why you couldn't reproduce this!  Timezone difference.

I just tested this and confirmed that the date would consistently change when my system is set to UTC-8, but the behaviour stops when I set my system to UTC+1.  

It seems that the date field and picker function correctly from UTC and ahead (east), but this date shifting behaviour occurs for any timezones behind (west of) UTC.

**Comment by dlh3** [comment]
Looks like this is an OOTB issue with Angular-Material, see angular/material2#7167.

One user contributed a custom solution: https://github.com/angular/material2/issues/7167#issuecomment-385416948

But the MatMomentDateAdapter may be the best solution: https://github.com/angular/material2/issues/7167#issuecomment-333889114
