### ISSUE TITLE
Year progressions go past December 31st

### ISSUE THREAD

**Issue by mhjartstrom** [thomaschampagne/elevate#708]
* Plugin version: 6.8.0 Stable
  * Chrome version: 71.0.3578.80
  * OS version: Kubuntu 16.04.5 LTS

### Step 3: Describe the problem:

It seems that my Year Progressions view for 2016 will continue past December 31st and on to January 1st. Is it perhaps caused by some miscalculation because 2016 was a leap year?

#### Steps to reproduce:

Hover mouse over the last date in the Year Progressions graph.
  
#### Actual Behavior:

January 1st follows December 31st.
  
#### Expected Behavior:

End on December 31st.
  
#### Media attachement:

See attached picture.
![year progressions](https://user-images.githubusercontent.com/16958643/49724151-ebf06a00-fc68-11e8-8c4b-adcfd3d1fd00.png)

**Comment by thomaschampagne** [comment]
Strange can you provide me a history backup?

**Comment by mhjartstrom** [comment]
[2018.12.17-11.46_v6.8.0.history.json.zip](https://github.com/thomaschampagne/elevate/files/2685699/2018.12.17-11.46_v6.8.0.history.json.zip)

**Comment by thomaschampagne** [comment]
@mckennajones Could you tell me where do you live? Or what's your time zone? I'm thinking about a timezone bug...

**Comment by thomaschampagne** [comment]
@mhjartstrom  Could you tell me where do you live? Or what's your time zone? I'm thinking about a timezone bug...

**Comment by mhjartstrom** [comment]
I live in Sweden. GMT+1, much like yourself I presume?

**Comment by thomaschampagne** [comment]
Yes. I finally found the cause after a long debug. It's not really a bug. It's coming from the mozilla graphic library used in elevate: https://github.com/metricsgraphics/metrics-graphics

I'm a contributor of this library by many pull request i've done for elevate. So will see with them.

Thanks for you report !

**Comment by mhjartstrom** [comment]
Still present in 6.8.1 though.

**Comment by thomaschampagne** [comment]
@mhjartstrom Yes it's not a problem in fact :) it's https://github.com/metricsgraphics/metrics-graphics behaviour

**Comment by mhjartstrom** [comment]
I don't follow. Yes, it is a problem. January 1st is not the last day of the year, it's the first day of the year!

I don't see how you can close this issue when it's obviously not resolved. You can put it into some kind of pending state, waiting for fixes from "metricsgraphics", but as long as you don't merge (or whatever you do) the changes that is expected from that project then there is still work to be done here.
