### ISSUE TITLE
Whoops sync error occurred - always at the same place

### ISSUE THREAD

**Issue by carlbelanger** [thomaschampagne/elevate#711]
**Notes**
On activity https://www.strava.com/activities/195853636

Logs: https://github.com/thomaschampagne/elevate/files/2684132/www.strava.com-1545008442245.log

>Error: Invalid date or not formatted as 'YYYY-MM-DD'
>athlete-model.resolver.ts:89
---
Haven't been able to sync my activities since I changed computer.

![image](https://user-images.githubusercontent.com/11096/50058506-3f6e2680-0147-11e9-9215-de2e28768b59.png)

Always happen in group 42.  Tried resetting settings and reinstall apps but it just gives me the same error.

Plugin version: 6.8.0 Stable
Angular Core version: 7.0.4
Angular Material version: 7.0.4
D3js version: 5.7.0
Chrome : Version 70.0.3538.110 (Build officiel) (64 bits)

Any advice?  
Thanks,
Carl

**Comment by thomaschampagne** [comment]
@carlbelanger On same window can press F12 to display dev console. Then right click to save the log file. And post it to me here? Thx

**Comment by carlbelanger** [comment]
Here you go.
Thanks!
[www.strava.com-1545008442245.log](https://github.com/thomaschampagne/elevate/files/2684132/www.strava.com-1545008442245.log)

**Comment by thomaschampagne** [comment]
@carlbelanger Could you tell me if your problem is fixed with following build: https://bitbucket.org/thomaschampagne/elevate-ci-builds/downloads/v6.8.0_stable_2018-12-21-12-39.develop.19584da6.zip ?

If not you can reopen the ticket
