### ISSUE TITLE
Feature request: Choose beginning month for Year Progression

### ISSUE THREAD

**Issue by prdubois** [thomaschampagne/elevate#716]
To track winter sports, it would be nice to be able to choose the beginning month for yearly progression graphs. For example I would like to see the total number of kilometers of each x-country skiing season. But each season spans two years (say Nov 2017 to April 2018).

**Comment by thomaschampagne** [comment]
@prdubois I fully understand the need. It's quite hard stuff to perform that in year progression. But i will release a "query" system with filters in a upcoming update with excel export. This may help you

**Comment by prdubois** [comment]
Thanks for considering the request. I'll keep an eye out for the query system.
