### ISSUE TITLE
Feature request: New progress type for Year Progressions

### ISSUE THREAD

**Issue by mhjartstrom** [thomaschampagne/elevate#720]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.8.1 Stable
  * Chrome version: 71.0.3578.98
  * OS version: Windows 10
  
### Step 3: Describe the problem:

Add the possibility to use a Progress Type based on the Final Stress (TSS) column values used on the Fitness Trend view instead of e.g. Distance or Time.

**Comment by OndrejSpanel** [comment]
See also #580
