### ISSUE TITLE
Enhancement: add TSS/FSS bar chart to Fitness Trend

### ISSUE THREAD

**Issue by dlh3** [thomaschampagne/elevate#723]
Currently, the Fitness Trend graph includes dots on days with activities.  However, I think it would be useful if a bar chart showed Training/Final Stress Score (TSS or FSS) for those days.  

My initial idea was that the TSS bar chart could be an overlay of the existing graph, with a separate Y-axis on the right for the TSS chart.  If this is too difficult to implement as an overlay, perhaps a more viable alternative would be to add the TSS bar chart below the existing graph.

Strava's own Fitness & Freshness for inspiration:
![image](https://user-images.githubusercontent.com/648035/50583565-d06b2000-0e1e-11e9-8228-329871d3d5f1.png)

Likely related: #643 and #629.

**Comment by pistegerte** [comment]
Another Idea for TSS:
Would it be possible to show the Total TSS of the Weekin the Dashboard or the Traininglog (TSS only)?

Would be nice to see direct how high the actual trainingsload of the week is.
