### ISSUE TITLE
RSS not appearing for manually entered treadmill runs with no Heart Rate or GAP

### ISSUE THREAD

**Issue by ericwclymer** [thomaschampagne/elevate#733]
Edit -- Based on https://github.com/thomaschampagne/elevate/blob/79f928069fb84c3f63ec08e28eb3f21aaed7e410/plugin/core/scripts/processors/activity-computer.ts#L576 it appears that RSS requires a grade-adjusted average pace. 

So, perhaps my request is that a treadmill run with no GAP still works. I think this could be accomplished by assuming an entirely flat course. I'm new to this code, but maybe that could be accomplished by returning an array here with "flat altitude/elevation": https://github.com/thomaschampagne/elevate/blob/79f928069fb84c3f63ec08e28eb3f21aaed7e410/plugin/core/scripts/processors/activity-computer.ts#L1305

## Original Content of this issue
Plugin version: 6.8.1
Chrome/Opera/Chromium version: 71.0.3578.98
OS version: Windows 10
  
#### Summary

My treadmill activities have no stress score. I've tried changing settings and re-syncing. For treadmill runs with no heart rate data associated, the stress score is empty and the graphs are treated like rest days. Given that the RSS estimation toggle is on and Weight/HeartRate/LTHR/RFTP are set in athlete settings: I expect to see the an estimated stress score for those activities (treadmill runs).

I tried clearing my cache and all settings as well, and am still experiencing the same issue.
  
#### Media attachment:
Backup file:
[2019.1.7-14.32_v6.8.1.history.zip](https://github.com/thomaschampagne/elevate/files/2734205/2019.1.7-14.32_v6.8.1.history.zip)

**Comment by thomaschampagne** [comment]
@ericwclymer Thanks for this report! Do you have strava public treadmill runs activities?

**Comment by ericwclymer** [comment]
@thomaschampagne yeah, I should have plenty. 

The last three:
https://www.strava.com/activities/2093082449
https://www.strava.com/activities/2084072893
https://www.strava.com/activities/2081649746

**Comment by ericwclymer** [comment]
Yes! It looks like this is roughly the same thing @amokrunner .

**Comment by ahmism** [comment]
I'm new as well, but if I'm not mistaken manually entered runs have no associated activity streams, so the issue runs a bit deeper. I've tried to make this work in a pseudo-clean fashion.

**Comment by thomaschampagne** [comment]
@ahmism Really thanks for this PR! I will start looking at it today  :)
