### ISSUE TITLE
Feature request: Backup/restore Datad Athlete Settings

### ISSUE THREAD

**Issue by hnaess** [thomaschampagne/elevate#740]
* Plugin version: 6.8.1
  * Chrome/Opera/Chromium version: 71.0.3578.98
  * OS version: Windows 10
  
1. Athlete Settings

Similar as it is possible to backup/restore of HR Zones to copy settings between different browser and machine, it would be useful to backup/restore Dated Athlete Settings.

**Comment by thomaschampagne** [comment]
It's already done in backup/restore of activities. Hope this helps
