### ISSUE TITLE
Fitness trend - Form

### ISSUE THREAD

**Issue by TerjeLu** [thomaschampagne/elevate#746]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by TerjeLu** [comment]
Form doesn't work for two subsequent training sessions on the same day, it keeps rising when it should have gone down.

**Comment by dexe3** [comment]
I'm not exactly sure if it's the same cause, but I did two indoor workouts yesterday, both an hour, both around 60 TSS, however only the first workout is used to calculate the days TSS. Basically I'm missing 60 tss for the day and resyncing doesn't work.

Are your workouts both used for tss calculations?

**Comment by thomaschampagne** [comment]
@TerjeLu @dexe3 Did you rode the **FAQ** or **Fitness trend helper** before posting here 😄 ?

It's written in issue you posted: https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions

OR _chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/app/index.html#/frequentlyAskedQuestions_ inside elevate app.

You will find:
>**My form does not fall after an effort while my fitness and fatigue goes up... Why?!**
This is the expected behaviour, your form will drop the day after your effort. Form = (Yesterday Fitness) - (Yesterday Fatigue). Open helper in fitness trend feature for more details.

**Comment by greglondon** [comment]
Hi. 

* Plugin version: Plugin version: 6.9.1 Stable
* Chromium version: 71.0.3578.98
* OS version: Xubuntu 16.04

I use Strava and elevate on two different computers. Both pretty much with the same setup. Uploaded my activity (cycling) last night on home computer (possibly with a previous version of Elevate - need to check it), Elevate fitness trend updated automatically.
Checked this morning on a work computer (latest plugin version) and the activity dot was shown on the graph, but showing 'no stress score'. It was all good until yesterday. I used 'clear and re-sync activities' option, but it went even worse - not only running activities shows a stress score. Cycling and weight training don't. Didn't change any settings in the plugin recently.
Also on a Strava activity page the plugin doesn't show advanced stats any longer (I could click there and it was showing graphs of speed, time in zones, cadence, grade, VAM, etc.)

**Comment by Alobaloba** [comment]
Hi, I got the same problem. I installed the plugin the first time today and at first it worked (i saw the lines in the graphic). Then, after a few seconds reading the "tutorial" I changed my weight and those things and when I did sync again  it showed only a flat line with all the activties with 0 stress score.

**Comment by laurahicks30** [comment]
Only run stress scores showing up since update. Friend has the same issue. No changes made to athlete settings or any other settings. Rides show No Stress Score
