### ISSUE TITLE
Strava

### ISSUE THREAD

**Issue by dlkruger** [thomaschampagne/elevate#747]
Are you guys aware a problem has been created about a month ago, and many of us who use Cateye computers cannot directly upload to strava.
This is a problem!
See the following link:
https://support.strava.com/hc/en-us/community/posts/360033565471-Upload-Strava-ride-with-Cateyes-Sync?page=1#community_comment_360004049231

or are you just ignoring it?

Thanks.

**Comment by thomaschampagne** [comment]
... I'm not Strava. There's nothing to ignore since there's no link with elevate... 

Hope this helps

**Comment by thomaschampagne** [comment]
No problem ;)

Have a nice day ;)

Tom
