### ISSUE TITLE
Trainer Road Virtual Ride not calculating PSS.

### ISSUE THREAD

**Issue by j-kess** [thomaschampagne/elevate#753]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
Yes, did not see it there.

  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?
Yes, did not see it there, but found this somewhat related ticket. However, I can still see the extended stats, just not the PSS.

### Step 2: Describe your environment

  * Plugin version: __6.8.1___
  * Chrome/Opera/Chromium version: _____
  * OS version: __Chrome OS Version 71.0.3578.127___
  
### Step 3: Describe the problem:
I have my FTP set to 216 in both strava and elevate under athlete settings. When I upload a ride from Trainer Road to Strava, elevate gives me a notice to "update my ftp in athlete settings to get a power stress score." My regular (non virtual) rides seem to work okay.

#### Steps to reproduce:

  1. Do a ride with the trainer road app._____
  2.  Trainer Road app automatically syncs and pushes the activity to strava._____
  3.  Power stress score is not available in the elevate app, and only the HRSS is used._____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console? no

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

![image](https://user-images.githubusercontent.com/6363185/52073555-a94a6000-253c-11e9-842e-2689e481738c.png)

![image](https://user-images.githubusercontent.com/6363185/52073728-1827b900-253d-11e9-9017-3e8ca3224e93.png)

![image](https://user-images.githubusercontent.com/6363185/52073758-2e357980-253d-11e9-8f8b-c8b0b3b46bdd.png)

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
Bug already fixed here: https://github.com/thomaschampagne/elevate/issues/735

Released in 6.9.0
