### ISSUE TITLE
Elevate and Strava Not Syncing

### ISSUE THREAD

**Issue by zabyxc** [thomaschampagne/elevate#759]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions? Yes
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues? Yes, could not find.

### Step 2: Describe your environment

  * Plugin version: 6.8.1
  * Chrome/Opera/Chromium version: 72.0.3626.81
  * OS version: High Sierra 10.13.6
  
### Step 3: Describe the problem:
Elevate is not syncing correctly with Strava.  All of my rides seem to be syncing, but mileage is off.  For instance, in Jan 2019 I had 22 activities on Strava, total miles of 373.  Elevate shows 22 activities, but yearly progressions shows only 227mi.  Problem dates back to at least mid-2017 in my data (Jan 2018 Strava mileage is 579, versus 262 in Elevate).

I have tried fully re-syncing data and uninstalling and re-installing the plugin with no change in data.  

My apologies if the answer to this problem is somewhere in the forum; I searched and was unable to find.

#### Steps to reproduce:

  1. View my annual progression data Jan 31, 2019
  2. Compare against Monthly mileage in Strava
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by zabyxc** [comment]
Hi, Thomas.

I do believe the issue is with virtual rides (all are done on Zwift).  I
have them saved as 'virtual ride' in Strava.  All show up in Elevate, but
their mileage is not being picked up.  Jan 4, 2019 is a good case study -
please see Strava screenshots attached.  The mileage for this activity was
not picked up by Elevate, though it is marked as a virtual ride.  Am I
missing something silly and obvious here?

I apologize for not sharing more info in the public post; reticent to share
info in that sort of forum.  Here's my Strava profile:
https://www.strava.com/athletes/1737339.

Thank you,
Rob

**Comment by thomaschampagne** [comment]
@zabyxc Thanks for details. Can't see your profile (private)

**Comment by thomaschampagne** [comment]
I sent you a friend request to debug on my side

**Comment by thomaschampagne** [comment]
@zabyxc Did you check VirtualRides like this: https://imgur.com/a/r5jAR2W ?

Or as explained in FAQ: https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions#zones-settings

Thx

**Comment by thomaschampagne** [comment]
New message again... This kind of activity (https://www.strava.com/activities/2116297333) i've seen in your history could not give distance data: look the empty "Analysis" curves

**Comment by zabyxc** [comment]
Hi, Thomas.  I'm having trouble following your last comment.  When I check
this activity (https://www.strava.com/activities/2116297333), I see
mileage, power curve, HR data, etc.  Pls see screenshot attached.

**Comment by thomaschampagne** [comment]
@zabyxc I can't see images when you reply by mail to the ticket. I see this on this activity: https://user-images.githubusercontent.com/151973/52281252-050e5200-295e-11e9-9d48-ab603e656cba.png

And what about this?
> Did you check VirtualRides like this: https://imgur.com/a/r5jAR2W ?
Or as explained in FAQ: https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions#zones-settings

**Comment by zabyxc** [comment]
Hi, Thomas.  Just following up on the below.  Any ideas here?
