### ISSUE TITLE
Segment Quick Details not working for some activity types

### ISSUE THREAD

**Issue by daniandr** [thomaschampagne/elevate#765]
* Plugin version: 6.9.1
  * Chrome/Opera/Chromium version: 71.0.3578.98
  * OS version: Windows 10 Enterprise 1803
  
When checking the list of segments the "details" for the segments does not load, e.g. the delta for your PR and CRs etc., this issue is only present on activity types that has segments on the primary tab but works fine for other activity types that has segments on its own tab e.g. running.

#### Steps to reproduce:

  1. Go to a Nordic Ski activity with segments
  2. When scrolling down to the segments the segment quick details won't load.
  
In the console I get the following error when loading an activity like this.

  ```javascript
  boot.bundle.js:73 Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined
    at t.handleExtendedActivityData (boot.bundle.js:73)
    at boot.bundle.js:73
  ```

I first encountered this issue in version 6.9.0

**Comment by Jiiwee2** [comment]
I have exactly the same problem with Nordic Ski and plugin version 6.9.x (no problems with runs/rides). To ensure nothing else has changed in my system I loaded your previous package 6.8.1. With this Elevation version also Nordic Ski works perfect.

**Comment by RomanKovalev** [comment]
> I have exactly the same problem with Nordic Ski and plugin version 6.9.x (no problems with runs/rides). To ensure nothing else has changed in my system I loaded your previous package 6.8.1. With this Elevation version also Nordic Ski works perfect.

How to downgrade Elevate extension to 6.8.1 version?

**Comment by RomanKovalev** [comment]
> I have exactly the same problem with Nordic Ski and plugin version 6.9.x (no problems with runs/rides). To ensure nothing else has changed in my system I loaded your previous package 6.8.1. With this Elevation version also Nordic Ski works perfect.

How do you install downgrade extension version?
I tried:
1. Download and unpack 6.8.1 version
2. In Chrome extensions enable developer mode, click Load unpacked, place the way to elevate-6.8.1/plugin/.
3. Don't works.

**Comment by Jiiwee2** [comment]
I just followed Thomas' instructions (see issue #762)

"If you want to bring back the old feature you can still download an old build here: https://thomaschampagne.github.io/elevate/#/builds (with filters **branch: **master,** version: 6.8.1**)"

**Comment by thomaschampagne** [comment]
@daniandr @RomanKovalev @Jiiwee2 Could you provide me activities links (with public access) so i can fix this bug for next version 6.10

Thanks

**Comment by Jiiwee2** [comment]
Hello,

Hope you can access these links

https://www.strava.com/activities/2169453831
https://www.strava.com/activities/2171958896

BR
Jarmo V

________________________________
Lähettäjä: Thomas Champagne <notifications@github.com>
Lähetetty: Sunday, February 24, 2019 2:48:47 PM
Vastaanottaja: thomaschampagne/elevate
Kopio: Jiiwee2; Mention
Aihe: Re: [thomaschampagne/elevate] Segment Quick Details not working for some activity types (#765)


@daniandr<https://github.com/daniandr> @RomanKovalev<https://github.com/RomanKovalev> @Jiiwee2<https://github.com/Jiiwee2> Could you provide me activities links (with public access) so i can fix this bug for next version 6.10

Thanks

**Comment by thomaschampagne** [comment]
This bug is fixed. You can validate it by downloading the latest build here: https://thomaschampagne.github.io/elevate/#/builds

If not fixed you can re-open the ticket :) But it should be OK ;)

**Comment by Jiiwee2** [comment]
Great job – works fine!

Lähettäjä: Thomas Champagne<mailto:notifications@github.com>
Lähetetty: sunnuntai 24. helmikuuta 2019 17.07
Vastaanottaja: thomaschampagne/elevate<mailto:elevate@noreply.github.com>
Kopio: Jiiwee2<mailto:jarmo.vainola@outlook.com>; Mention<mailto:mention@noreply.github.com>
Aihe: Re: [thomaschampagne/elevate] Segment Quick Details not working for some activity types (#765)


This bug is fixed. You can validate it by downloading the latest build here: https://thomaschampagne.github.io/elevate/#/builds

If not fixed you can re-open the ticket :) But it should be OK ;)
