### ISSUE TITLE
No stress score on all activities

### ISSUE THREAD

**Issue by MollyMooTM** [thomaschampagne/elevate#768]
* Plugin version: _____Plugin version: 6.9.1 Stable
Angular Core version: 7.2.3
Angular Material version: 7.2.2
D3js version: 5.8.0
  * Chrome/Opera/Chromium version: __CHROME___
  * OS version: _____
  
### Step 3: Describe the problem:
Was in strava, clicked on Fitness trend, followed the steps to re-sync, all activities showing but no stress score so no graph

  
#### Expected Behavior:

  I expected fitness trend graph to show. It has worked in the past
  
#### Media attachement:

![image](https://user-images.githubusercontent.com/47599162/52713466-7f3c7780-2feb-11e9-964a-12381d44d043.png)

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by greglondon** [comment]
I've got similar thing (only run activities have a stress score). Commented this morning about it on the existing Fitness Trend issue: https://github.com/thomaschampagne/elevate/issues/746#issuecomment-463166790

**Comment by thomaschampagne** [comment]
@MollyMooTM @greglondon Did you set Running FTP in single or dated athlete settings over the period?

How many activities do you have? Are they all displayed in fitness trend table? Do you have some activity links were the problem occurs?

A elevate backup file is welcome.

**Comment by thomaschampagne** [comment]
Could be this... https://twitter.com/champagnethomas/status/1095743506193305600

**Comment by greglondon** [comment]
I have a backup file from a point when noticed that the last activity stress score wasn't calculated, but before I re-synced all activities which made it even worse. So one, the most recent activity from a back it no showing the stress score. Shall I email you the backup file to you? If so - what address please? (don't want to share a full backup of my activities online)

**Comment by thomaschampagne** [comment]
You can here: th.champagne[at]gmail.com

But i think i identified the problem :/ I have to think from now :) I am always persevering to find a solution ;)

**Comment by MollyMooTM** [comment]
Yes all my activities are there (509 in total) but in a flat line like the image in your tweet. Hope you can find a solution!

**Comment by Alobaloba** [comment]
The same problem for me, I hope you can find a solution because It's a very useful plugin. Good luck!

**Comment by greglondon** [comment]
All seems normal to me this morning on both computers I use elevate. I think yesterday Strava had some issues as even some details on an activity page wasn't showing (like speed, hr, pace graphs).

**Comment by MollyMooTM** [comment]
I just reloaded and it is not working! YAY!

**Comment by thomaschampagne** [comment]
@MollyMooTM Reloaded what precisely?

**Comment by jeremyjhartley** [comment]
I am having the same issue. I opened strava on my work computer and resynced all activities. I now have a flat line.

**Comment by adhed** [comment]
the same issue. 

if it won't be possible to use Strava's API I suggest to maybe add an option to add TSS manually to every activity (we can calculate it on our own, or get it from TrainingPeaks)

**Comment by thomaschampagne** [comment]
I am currently working on a patch to manage the problem. Thanks for your patience

**Comment by greglondon** [comment]
My fitness trend seems ok, but recent activities' TSS score seems low. For yesterday's ride Training Peaks shows 166, but Elevate only 106. There were differences before but usually not more that 5% or so. This is much more now. Other previous TSS scores are ok (within a few percent margin). Do you think Thomas it is related to the same issue?

**Comment by cmagnuson** [comment]
@greglondon I saw the same, but when I expanded the duration of time shown in the fitness trend I saw that I had only the last two months of activities TSS recorded, maybe the same issue for you.  

Resyncing all activities would sometimes bring in no TSS history and sometimes only last couple of weeks.

**Comment by greglondon** [comment]
@cmagnuson - I've noticed that too. My trend is above zero on activities since August. I guess it doesn't matter as it's only last 60 or 90 days important for the calculation. Am I correct @thomaschampagne ?

**Comment by dbwz8** [comment]
I just downloaded onto a new machine. V6.10.1. I was able to sync 900+ activities... none of them have PSS anymore. Bummer. I don't think it's really fixed.
