### ISSUE TITLE
Nordic ski support stopped working

### ISSUE THREAD

**Issue by RomanKovalev** [thomaschampagne/elevate#769]
* Plugin version: 6.9.1
  * Chrome/Opera/Chromium version: Version 69.0.3497.92 (Official Build) (64-bit)
  * OS version: Debian 8

  1. Open any Nordic ski activities.
  2. Section "Segments" hasn't any additional statistics.
  3. It was working 1 week ago.
  4. But additional statistics for ride activities - working.
  
I don't know, whether related error in java console:
  ```javascript
  Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined
    at t.handleExtendedActivityData (boot.bundle.js:73)
    at boot.bundle.js:73
  ```
  
#### Expected Behavior:

 Should to see extended stats for nordic ski  segments (as it was 1 week ago).
 
My activities:
[2019.2.14-1.32_v6.9.1.history.json.zip](https://github.com/thomaschampagne/elevate/files/2862471/2019.2.14-1.32_v6.9.1.history.json.zip)

**Comment by Jiiwee2** [comment]
Same as issue #765

**Comment by thomaschampagne** [comment]
This bug is fixed. You can validate it by downloading the latest build here: https://thomaschampagne.github.io/elevate/#/builds

If not fixed you can re-open the ticket :) But it should be OK ;)
