### ISSUE TITLE
data not showing on activity pages

### ISSUE THREAD

**Issue by campybob** [thomaschampagne/elevate#773]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _6.9.2 Stable____
  * Chrome/Opera/Chromium version: __Chrome  72.0.3626.109 (Official Build) (64-bit)___
  * OS version: Windows 7 and 10_____
  
### Step 3: Describe the problem: On STRAVA activity page the Elevate data that used to appear automatically when the activity loaded is not showing up. I can click on the "Display Elevate Extended Stats" and that data shows up perfectly.

Can only see this when page loads:
  | Avg | Max
-- | -- | --
16.4mi/h | 20.8mi/h
148bpm | 168bpm
66 | 86
899
1:26:53

No Elevate data is shown.

Thank you,
  Bob King

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

Nothing shown.

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen? I expected the block of Elevate data to show on page load like it always did.
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
It's an expected behavior. New Strava servers behavior implied this change. Everything is explained in 6.9.2 release note. 

Thomas

**Comment by campybob** [comment]
Thank you, Thomas!
