### ISSUE TITLE
Odo is broken

### ISSUE THREAD

**Issue by LastDragon-ru** [thomaschampagne/elevate#774]
### Describe your environment

  * Plugin version: Plugin version: 6.9.2 Stable
  * Chrome/Opera/Chromium version: Chrome 72.0.3626.109
  * OS version: Win 10 x64
  
### Describe the problem:

![image](https://user-images.githubusercontent.com/1329824/53115697-4e66c000-3560-11e9-999b-e4449ee37fb9.png)

#### Actual Behavior:

  * Odo on activity page is broken, and show 2 instead of ~2000

#### Expected Behavior:

  * Valid odo (~2000)
    ![image](https://user-images.githubusercontent.com/1329824/53116161-6985ff80-3561-11e9-9d76-f3ae972d6989.png)

**Comment by thomaschampagne** [comment]
@LastDragon-ru Yes its broken with imperial system
Thanks for report

**Comment by thomaschampagne** [comment]
This bug is fixed. You can validate it by downloading the latest build here: https://thomaschampagne.github.io/elevate/#/builds

If not fixed you can re-open the ticket :) But it should be OK ;)

**Comment by LastDragon-ru** [comment]
@thomaschampagne, thanks and sorry for delay. On latest version (Plugin version: 6.10.1 Stable) I see this :( 

![image](https://user-images.githubusercontent.com/1329824/54075085-2abbad80-42b4-11e9-928b-a351e959ee02.png)

**Comment by thomaschampagne** [comment]
Bug occurs in russian only :/
