### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by la-8-pv** [thomaschampagne/elevate#776]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.9.2 Stable
  * Chrome/Opera/Chromium version: Chrome Versjon 72.0.3626.109
  * OS version: macOS Mojave 10.14.3
  
### Step 3: Describe the problem:
Sync does not run at all on this home mac. AND on my work PC only partial sync is running!
Major trouble... and it has been lasting for a few days now... PLEASE HELP

I´ve re-istalled the extnesion toaday and no change.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by JorickdeB** [comment]
Same, sync has not been working the whole day. I have cleared and resynced activities on one client and that stops syncing at some point and doesn't seem to continue (I have almost 1000 activities). On my client that misses just recent activities sync doesnt work at all.

**Comment by thomaschampagne** [comment]
It's an expected behaviour (unfortunately) with new strava servers changes
