### ISSUE TITLE
synchronizer operation

### ISSUE THREAD

**Issue by gaechang** [thomaschampagne/elevate#779]
![1](https://user-images.githubusercontent.com/48104905/53596469-25d76980-3be3-11e9-81c3-f98ceb80cd85.JPG)

No matter how long I wait, it will not sync

**Comment by thomaschampagne** [comment]
Could you open developer console (press F12) before the sync starts. Then after error occurs right click in console, save as.., and upload console out file here.

Thanks

**Comment by vbino** [comment]
I have the same issue.

Most of my recent rides have been 'virtual' (indoors / zwift). Tried uninstalling and reinstalling with no effect.

**Comment by thomaschampagne** [comment]
@gaechang @vbino Here's a fix to your problem:
https://github.com/thomaschampagne/elevate/issues/785#issuecomment-473521350

Could you try and tell me if solved?

Thanks !
