### ISSUE TITLE
Segment ▲ Stats constantly loading

### ISSUE THREAD

**Issue by AG-Spike** [thomaschampagne/elevate#780]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.10.1 Stable
  * Chrome/Opera/Chromium version: Chrome 72.0.3626.119 (64-bit)
  * OS version: Win 10 10586.1176
  
### Step 3: Describe the problem:
![image](https://user-images.githubusercontent.com/48119010/53625040-f718bd80-3bf9-11e9-8543-c550ddc6fb65.png)
The segment difference times just 'loading' the last day or so.

#### Steps to reproduce:

  1. Open any activity
  2. _____
  3. _____
  
#### Actual Behavior:

No errors, just not loading.
  
#### Expected Behavior:

▲KOM, ▲PR, and ▲yPR to load with values.
  
#### Providing your Elevate synced athlete activities can be useful to solve the problem

**Comment by AG-Spike** [comment]
For completeness sake, unless the 'fix' did not come from you, and as you have marked this to do in next release, turning Rank on allows the ▲ stats to load.

**Comment by thomaschampagne** [comment]
Let me know if problem continue. Re-open the ticket if necessary.

**Comment by AG-Spike** [comment]
It still requires Rank to be on to load any deltas, this is not how it used to be. Having Rank on is growing on me though, if only the Strava page was wider to save things being squished causing the segment names to go onto multiple lines, or am I doing something wrong / missing a setting that I can change myself somewhere or a hack?
![Untitled1](https://user-images.githubusercontent.com/48119010/55222219-43f4b180-5203-11e9-921e-6c5fad1ac718.jpg)
