### ISSUE TITLE
FitnessTrend: malfunction option estimated estimated RSS

### ISSUE THREAD

**Issue by vinyloup** [thomaschampagne/elevate#781]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version:  6.10.1 Stable
  * Chrome/Opera/Chromium version: Chromium v71.0.3578.98 (ubuntu stable)
  * OS version: Linux Xubuntu 18.04 LTS
  
### Step 3: Describe the problem:
I did a running activity without cardio frequency on Tuesday 26/02/2019. My activity was correctly imported into Strava and synchronized correctly in Elevate App. With Elevata App, despite the use of the estimated Running Stress Score option, the display of this activity makes the graph of my FitnessTrend completely unreadable.
Is it possible to correct this problem of bad interpratation of my activity? is it possible to no longer only display this activity?
In attached, the graphs of my FitnessTrend with and without the option

Thank you in advance for your assistance. Available to help or give any additional information.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
Graph of my FitnessTrend completely unreadable.
  * Do you have javascript errors logs in browser console?
No

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.
![fitnesstrend-rss_disable](https://user-images.githubusercontent.com/48121770/53631025-cc3a6380-3c11-11e9-8e22-dac581f884f0.png)
![fitnesstrend-rss_enable](https://user-images.githubusercontent.com/48121770/53631026-ccd2fa00-3c11-11e9-8978-c98167f89819.png)

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here. 
[ElevateApp-backup_activities.zip](https://github.com/thomaschampagne/elevate/files/2918958/ElevateApp-backup_activities.zip)

**Comment by thomaschampagne** [comment]
@vinyloup Thanks for your feedback

That's because your Running FTP is wrong since 1/1/2019:

![image](https://user-images.githubusercontent.com/151973/55160362-718a1e00-5163-11e9-8da1-f459431d0fd8.png)

Which gives:

- Metric pace => 00:55:00/km
- Imperial pace => 01:28:31/mi

Since your activity as a average pace of 5:17/km, your RSS score is huge!

(Je passe en français car je viens de comprendre que tu es Grenoblois... de même pour moi, Meylanais à vrai dire ;))

**Comment by vinyloup** [comment]
Bonsoir Thomas,

Merci pour avoir "debuguer" et trouver le problème de paramétrage de mon
Running FTP. Une fois ce paramètre corrigé, ça va nettement mieux :-)
Bravo pour la qualité et la régularité de ton travail accompli sur ton
extension Elevate For Strava depuis de nombreuses années.

En effet, je suis comme toi grenoblois (Uriage). J’espère avoir le plaisir
de te rencontrer à l'occasion car évidement comme beaucoup d'utilisateur de
ton extension, j'ai plusieurs questions à te poser ou des retours
d’expérience à te faire partager, notamment par rapport au Fitness Trend ou
l’utilisation de ton extension (sous Linuxien notamment).

Bien cordialement,

--
Vincent L.

Le jeu. 28 mars 2019 à 14:16, Thomas Champagne <notifications@github.com> a
écrit :
