### ISSUE TITLE
Delta PR & Delta YPR not working

### ISSUE THREAD

**Issue by gbowser** [thomaschampagne/elevate#782]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
Plugin version: 6.10.1 Stable
Angular Core version: 7.2.7
Angular Material version: 7.3.3
D3js version: 5.9.1

Chrome Version 72.0.3626.119 (Official Build) (64-bit) 
Windows 10

### Step 3: Describe the problem:
The Delta PR and Delta y
[strav1.pdf](https://github.com/thomaschampagne/elevate/files/2921976/strav1.pdf)
PR just have "swirling circles".
I have removed the add-in, re-installed and re-synced all activities.
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?  Left overnight, but still shows no data.
Re-loaded activity page, no change
Closed browser and re-started Strava, no change.

  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
I expected stats to appear as before.  
#### Media attachement:

see attached screen grab

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by gbowser** [comment]
Issue seems okay now

**Comment by thomaschampagne** [comment]
Cool :)

**Comment by AG-Spike** [comment]
I still have this going on, was there a fix or did it just start working?

**Comment by gbowser** [comment]
I used to be able to set up the Strava page with Delta PR and DeltayPR without Rank.

Now, you have to show Rank to get Delta PR and DeltayPR .

Not a big deal, but Rank is of no interest to me.

 

Thanks

GB

**Comment by AG-Spike** [comment]
I did have Rank off, mainly because it was all getting a bit cramped with the limited width on the Strava page, but did resolve the issue as you said.

**Comment by gbowser** [comment]
Thanks!
