### ISSUE TITLE
Swimming - No stress score

### ISSUE THREAD

**Issue by ecneb85** [thomaschampagne/elevate#783]
### Step 1: Are you in the right place?
yes

### Step 2: Describe your environment

  * Plugin version: _6.10.1____
  * Chrome/Opera/Chromium version: __58___
  * OS version: __Linux Mint 19.1___
  
#### Steps to reproduce:

  1. __Swim workout manually added___
  2. __Swim workout not considered for fiuttness trend (no stress score)___
  3. _____
  
#### Actual Behavior:
no stress score for swimm workout
  
#### Expected Behavior:

Proper stress core for swimming in fitnesstrend
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem
![screenshot from 2019-03-02 16-12-34](https://user-images.githubusercontent.com/1805137/53683867-57952100-3d06-11e9-9aaa-9d45778b668e.png)
[2019.3.2-16.14_v6.10.1.history.json.zip](https://github.com/thomaschampagne/elevate/files/2922214/2019.3.2-16.14_v6.10.1.history.json.zip)

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
There's no swim ftp at all in your settings. Problem is here

![image](https://user-images.githubusercontent.com/151973/53684011-4fd67c00-3d08-11e9-8b80-db53f609c6ef.png)

If solved you can close the ticket

**Comment by ecneb85** [comment]
Sorry. My fault.

**Comment by mkonzen** [comment]
i'm having almost the same problem. No Estimated swimming stress score at all.
But i have set the ftp and sync all. My activities are not manually.

![Sem título](https://user-images.githubusercontent.com/38529992/56464693-6d010000-63c5-11e9-9a87-c52a7ba0f109.jpg)
