### ISSUE TITLE
Elevate Plugin Breaks strava.com/jobs

### ISSUE THREAD

**Issue by nikimicallef** [thomaschampagne/elevate#789]
* Plugin version: 6.10.1 Stable
  * Chrome: 72.0.3626.121
  * OS version: Windows 10 Pro N

#### Steps to reproduce:

  1. Go to strava.com/jobs
  
#### Actual Behavior:

The header appears without any classes which also blocks any elements behind the buttons (probably because the CSS classes are broken).
  
#### Expected Behavior:

The header doesn't show I guess
  
#### Media attachement:

I don't have anything to add except that you have a typo in this section title. attachment not attachement :D

**Comment by MQuaresma** [comment]
@thomaschampagne can you assign me to this one?
