### ISSUE TITLE
Weight units not changing from metric to imperial

### ISSUE THREAD

**Issue by nategarner314** [thomaschampagne/elevate#793]
### Step 2: Describe your environment

  * Plugin version: _6.10.1 Stable____
  * Chrome/Opera/Chromium version: __Version 72.0.3626.121 (Official Build) (64-bit)___
  * OS version: ___Windows 10__
  
### Step 3: Describe the problem:
The "weight" entry under athletes settings doesn't change from kg to lbs when changing from metric to imperial units

#### Steps to reproduce:

  1. change from metric to imperial units under global settings
  2. go to athlete settings. any weights entered in kg remain in kg
  3. try to enter new weight. Prompt still asks for kilograms

**Comment by thomaschampagne** [comment]
Actually i never prompted lbs units to the user since watts/weight is always displayed as w/kg for cycling.

But indeed you right with that miss.

If i had a real time conversion next to the kg in lbs. Is this OK for you? (like Running Functional Threshold Pace)

Thanks for reporting

**Comment by nategarner314** [comment]
Thanks for responding!

I would just like to input my weight in lbs instead of kg so I don't have
to convert it. a second box right next to it to enter in lbs instead would
work for me

Thanks again!
