### ISSUE TITLE
Recalculate without re-syncing?

### ISSUE THREAD

**Issue by A1Dan75** [thomaschampagne/elevate#799]
Apologies if I'm missing an obvious way to do this already or if there's a reason it wouldn't be practical... Would it be possible to have an option to recalculate your fitness trend across your whole history without resyncing with Strava?  

I've realised looking at my trend that that pre-using HRM, the calculations for RSS and PSS aren't really realistic with the parameters I put in.  But as far as I can tell, if you want to change / add athlete settings, it has to do an all-time resync to recalculate.  And as we're aware, syncing a couple of thousand activities is an arduous task with strava now.  I'd assume that just doing the calculations with existing Strava data is relatively light?

**Comment by thomaschampagne** [comment]
I will store the sensor data with activities in couple of weeks so you will be able to recalculate activities faster. Today it works like this as temporary solution. But working hard to produce something else ;)

**Comment by A1Dan75** [comment]
Thanks TC, keep up the good work!

**Comment by A1Dan75** [comment]
Hi Thomas,

Did this ever get implemented?  I'd like to adjust my athlete settings, but I'm nervous to do so if it might still require a full sync of all activities from Strava, which means Strava won't work for a day or two while it completes!

Thanks

Aidan
