### ISSUE TITLE
display a races marker/indicator in the plugin's fitness trend chart

### ISSUE THREAD

**Issue by zsoldosp** [thomaschampagne/elevate#800]
### environment

  * Plugin version: 6.10.2 Stable
  * Chrome version: 72.0.3626.121 64 bit
  * OS version: Windows 10
  
### Enhancement/Feature request:

In the "Fitness Trend" view, I would love to see some visual marker (vertical lines or similar) for race dates - so I can see how my form/fatigue was before a race to help me pace my upcoming race better

#### Steps to reproduce:

  1. Open plugin
  2. go to "fitness Trends" view
  
#### Actual Behavior:

There is no vertical line or other visual indicator for days on which one (or more) races took place.
  
#### Expected Behavior:

Some visual indicator on the chart so I can quickly locate my races and observe my fitness/fatigue/form values going into that race.

**Comment by zsoldosp** [comment]
I would be happy to make a PR, but need help/pointers, but due to lack of time, I would appreciate some pointers on how to get started (e.g.: is `ActivityInfoModel.type` the none/race/workout classifier? which test and source file should I start looking at? etc.)

**Comment by guillaumepotier** [comment]
Hi there, I'd be very happy to see that feature coming and also help to integrate it with a PR 💪
