### ISSUE TITLE
Question: Exclude an individual workout from fitness trend

### ISSUE THREAD

**Issue by AmarPrabhu** [thomaschampagne/elevate#801]
How do I exclude an individual workout from the fitness trend calculation?

There is some data anomaly that is causing the TSS to be calculated out of whack. 

I want to exclude an individual workout from the fitness trend calculation, how do I do it?

I do not want to delete the activity in Strava.

### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by lanzagar** [comment]
Fitness Trend -> Fitness trend configuration (gear icon) -> Exclude activities from fitness trend

As described in the above section of settings, you can add a hashtag for activities with data anomalies and exclude activities with that tag.
I think this should be enough for you, in which case you can close the issue.
