### ISSUE TITLE
Rolling progression sum is "wrong"

### ISSUE THREAD

**Issue by mathin** [thomaschampagne/elevate#802]
### Describe your environment

  * Plugin version: 6.10.2 Stable
  * Chrome/Opera/Chromium version: Version 73.0.3683.86 (Official Build) (64-bit)
  * OS version: Windows 7 64bit
  
### Describe the problem:

I believe that there is a miscalculation happening on the new "rolling" mode as it was implemented on issue #760 that limits the usefulness/accuracy of that wonderful new feature.

The other day I set the rolling interval to 1-day and looked at my graphs. I was surprised to see values of 30mi+ which seemed rather odd as I have never run more than a Marathon (only on a race day) and even including the pre-race warm-up (max 1mi) I would never exceed a maximum of 28mi on a single day (never over 30mi).  I then changed the rolling interval to 1 week and again I noticed in the plot that I had some 100mi+ weeks when I know from my detailed logbook (and Strava's native log functionality) that I have never run more than 93mi in a week.  So clearly there is an error in the calculation and I believe I can hypothesize where it is coming from.

Here is a dummy test case.  What if one runs 10mi at 10am on one Sunday and then another 10mi at 11am next Sunday?  Meaning just two runs "roughly" one week apart.  If one implements the rolling week based on exact time of day, then the plot would be mostly steady at 10mi rolling but then there is a period of 1 hour when the rolling interval is zero (and it appears on the plot as a spurius "dip").  I would imagine that the person would "expect" that they have run 10mi on each week so the rolling interval would show up as "constant" plot of 10mi.

The converse timing would also be a problem.  What if the same person runs 10mi at 11am on one Sunday and then another 10mi at 10am next Sunday? Again if one implements the rolling week on exact times, then the rolling value is 10mi but there is a period of 1 hour when both activities fall within the rolling interval and so it sums to 20mi (and it appears on the plot as a spurious "peak").  Again the person would "expect" that they have run 10mi on each week so the "peak" of 20mi would be correct in the mathematical sense but false in the mind of the user.

To me it seems that the "correct" functionality would be to first "quantize" (sum up) the distance on a daily (midnight to midnight) (or weekly/monthly) basis and then run the rolling sum on top of that.  I added "sum up" on parenthesis because a lot of runners run doubles (two runs) in a day and it is more useful to calculate the sum for the day instead of again having the same problem as described above.

Last note, people also travel internationally and usually the runs count for the "local" day of travel.  Strava resolves this by updating totals after midnight on the origin not the destination of travel.  We can discuss this on a separate thread but it is another reason not to use absolute time intervals bur rather sums / quantization for the local time zone.

#### Steps to reproduce:

  1. just observe how many peaks and dips exist on all rolling calculations and compare with the logs that Strava or people keep.

**Comment by mathin** [comment]
I looked at commits https://github.com/thomaschampagne/elevate/commit/074a7848f6b1b92cbc4094a2a568221b5c6f36c0#diff-a24bcf2198b1b13ad985304483f7f324 and https://github.com/thomaschampagne/elevate/commit/bb437c796a3f46407a298de751338f30df3f0c98#diff-a24bcf2198b1b13ad985304483f7f324 to see where the logic is implemented/tested but it's the first time I browse the code and I don't write JS so couldn't find it.  Could you point me to it to take a look and maybe offer a suggestion?

**Comment by thomaschampagne** [comment]
@mathin Thanks for the found.

The typescript code for rolling progression is located here: https://github.com/thomaschampagne/elevate/blob/develop/plugin/app/src/app/year-progress/shared/services/year-progress.service.ts#L195

Associated unit tests are here: https://github.com/thomaschampagne/elevate/blob/develop/plugin/app/src/app/year-progress/shared/services/year-progress.service.spec.ts#L505

Could you provide me a elevate backup?

The right thing to do is to create another unit test  that follow your study case. Ensure test failure and then fix  it.

**Comment by thomaschampagne** [comment]
According my previous comment. Could you post here unit test(s) case(s) of your problem?

Just copy & inspire yourself from **"it"** functions here: https://github.com/thomaschampagne/elevate/blob/develop/plugin/app/src/app/year-progress/shared/services/year-progress.service.spec.ts#L505

Don't worry about syntax errors in your unit test(s), i will fix them & fix the impacted code so your test(s) can pass ;)

Thanks

**Comment by thomaschampagne** [comment]
@mathin I added a unit test case for your problem with that commit: https://github.com/thomaschampagne/elevate/commit/26423f9d714fe6dcf0cfa09b682e232aa459160b

The test pass with current code. Could you check/edit the test?

Thanks

**Comment by mathin** [comment]
@thomaschampagne I took a look at the UT.  Quick question, on the call createActivity("2019-02-02", "Ride", 10000, 3600, 100) what are the two last parameters used for and why are they the same for all entries? (3600, 100)

**Comment by thomaschampagne** [comment]
@mathin Sry for the delay of my reply i missed the ticket notification :/
It's `moving_time_raw` in seconds & `elevation_gain_raw` in meters

The function is defined here (in the same file): https://github.com/thomaschampagne/elevate/blob/26423f9d714fe6dcf0cfa09b682e232aa459160b/plugin/app/src/app/year-progress/shared/services/year-progress.service.spec.ts#L509

**Comment by mathin** [comment]
Thanks.  I have looked at the code a couple of times and I still cannot tell how to address this, I am sorry. 
 But let me offer a different point of view on this "time quantization" issue.

Imagine that you want to display the rolling progression over the past "year".  In the parameters, if one chooses 1 year, 52 weeks (approximately) or 365 days, currently I think the resulting plot will be exactly the same in all three cases since the "quantization" is always 1 day (I believe).  But if you wanted to look at your past year as let's 52 weeks, then the quantization should be 1 week.  An additional parameter would then be necessary to denote the start day of the week as other runners consider Monday as the start or Sunday as the start.  I hope this somehow makes sense.
