### ISSUE TITLE
Odo still broken

### ISSUE THREAD

**Issue by LastDragon-ru** [thomaschampagne/elevate#805]
* Plugin version: 6.10.2 Stable
  * Angular Core version: 7.2.7
  * Angular Material version: 7.3.3
  * D3js version: 5.9.1
  
Related to #774, odo still broken :(

![image](https://user-images.githubusercontent.com/1329824/55237878-91e1d780-524c-11e9-90d5-0ebfa656a91b.png)
![image](https://user-images.githubusercontent.com/1329824/55237909-a02ff380-524c-11e9-849d-6130d3a12d95.png)

**Comment by thomaschampagne** [comment]
Bug occurs in russian only :/
