### ISSUE TITLE
Activity List - Extended Statistics Export - Decimal Places for Distance

### ISSUE THREAD

**Issue by ACCtionMan** [thomaschampagne/elevate#807]
Love the new option to view extended statistics for activities.  Would it be possible to include the decimal places in the distance please.

**Comment by A1Dan75** [comment]
Yeah, it's wiped mine and says it needs to sync from scratch again.

**Comment by Elevateapp** [comment]
This option is very helpfull, could you add one more column like "equipement" (Bike A, Bike B, Shoe A, and so on).

**Comment by sprete98** [comment]
I would like to see the distance with decimal places as well if possible.
