### ISSUE TITLE
Dated Athlete Settings

### ISSUE THREAD

**Issue by MarkLutterman** [thomaschampagne/elevate#810]
### Step 1: Are you in the right place?

Dated Athlete Settings revert to default.  Does not keep multiple dated settings of weight, max HR, runningFTP.  I think it saved, but then reverts to default.  Go to advanced and for a while it shows multiple dated settings, but then when I come back next day it is back to default with none of the dated settings showing even in advanced settings. 
  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
Synced activities size: 2.54 MB
Plugin version: 6.11.0 Stable
Angular Core version: 7.2.11
Angular Material version: 7.3.6
D3js version: 5.9.2
Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Windows 10 Enterprise 1803 OS build 17134.648
  
### Step 3: Describe the problem:
I entered Three dates for measures of weight, max HR, and changing running FTP which seemed to work. They didn't show at first when I entered them and clicked "+Add new dated athlete settings", but did show when I went back to Athlete Settings from Activities.  When I viewed activities for periods that seem covered by the Dated running FTP, I still get "No running FTP in dated athlete 
settings for this activity date".  So I figured I needed to re-synch.  But after re-synch all, the athlete settings all reverted to default with only a default (and not accurate) weight, and Max HR and no running FTP and only for current date.  

#### Steps to reproduce:
  0. Default Athlete Settings seem to always start with 70kg, and Max HR of 190.  
  1. _Add new dated athlete settings for three dates Jan 2 2017, March 2 2018 and Oc 2 2018: In particular I changed weight to various 84kg, 80kg, and 75kg, Max HR to 185 for each, and running FTP to 335, 300, 270. 
  2. _View activities for any dates in that time period and will show "No running FTP in dated athlete 
settings for this activity date". 
  3. __Click on Synch All Activities.  
  
  
#### Actual Behavior:

  * What happened?
4. __ Athlete settings revert to 70kg, and Max HR of 190, and have lost the three dated athlete settings set in step 1.  
  * Do you have javascript errors logs in browser console?
Hitting Fn and F12 
  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
6.62eddc2c51611a371a87.js:1 t
n.handleErrors @ 6.62eddc2c51611a371a87.js:1
9.17a33fff64d86954b87d.js:1 Setup done
7.ad86ce8c363c2bd6d111.js:1 Graph update time: 196 ms.
9.17a33fff64d86954b87d.js:1 Setup done
7.ad86ce8c363c2bd6d111.js:1 Graph update time: 148 ms.
7.ad86ce8c363c2bd6d111.js:1 Graph update time: 217 ms.

  
#### Expected Behavior:

  * What did you expect to happen?
I had expected the three dated athlete settings to remain and not to revert to nothing for running FTP, and 70kg and 190HR max.  
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here. 
[2019.4.2-11.26_v6.11.0.history.zip](https://github.com/thomaschampagne/elevate/files/3034981/2019.4.2-11.26_v6.11.0.history.zip)
[2019.4.1-7.53_v6.11.0.history.zip](https://github.com/thomaschampagne/elevate/files/3034982/2019.4.1-7.53_v6.11.0.history.zip)

**Comment by thomaschampagne** [comment]
Fixed with aa9ec111b9d1367a1af43b7e59d954a6a51b37a2 & f774fa0ad9e6a112dac9b53b08fec627d4aedd6c Patch 6.11.1 incoming...
