### ISSUE TITLE
Cannot download any data

### ISSUE THREAD

**Issue by kleinen12** [thomaschampagne/elevate#811]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _6.11.0____
  * Chrome/Opera/Chromium version: __chrome version 73___
  * OS version: __winodws 10 64 bit___
  
#### Steps to reproduce:

  1. __Got to strava, select year progression.___
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?  A new window opens to download my data - but nothing is ever downloaded.  I get the window that says to try again in 4-5 hours but when I come back and try to download the remaining data nothing happens.   I can close strava and go back in and I get the same message on the yearly progression page.  I also uninstalled the extension and reinstalled.  This has been happening for about 3 weeks since I realize you are working on some other issues.  I was hoping version 6.11.0 would solve my issues but no luck.
![yearly progression](https://user-images.githubusercontent.com/35115818/55431677-585fe380-554e-11e9-8b19-3fcd1e94510e.jpg)
![download data](https://user-images.githubusercontent.com/35115818/55431700-66156900-554e-11e9-8339-37c54bd02923.jpg)

  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by vbpad** [comment]
Having the same problem on three different computers sync happens but none of the data is showing up in the extension. it keeps reminding me to sync my activities

**Comment by kleinen12** [comment]
Same problem with the latest version:
About this plugin
Elevate extension is just adding some features that riders and runners would like to see in their Strava web. If these features could be added by default in Strava... It could be cool! Consider getting Strava Premium. There are a ton of features that you will love. Remember, this extension has for ambition to enhance the experience of all users (Free and Premium) and tends to keep users loyal in Strava.
Strava logos, product and service names are the exclusive trademarks of, and are owned by, Strava, Inc. This extension is not approved by Strava. Do not ask them for support.
Synced activities size: 2.01 MB
Plugin version: 6.11.1 Stable
Angular Core version: 7.2.13
Angular Material version: 7.3.7
D3js version: 5.9.2
You are running the latest version

**Comment by thomaschampagne** [comment]
I'm aware of strong issue with sync since february. I'm working on something totally new to avoid this. Please wait
