### ISSUE TITLE
Elevate not updating athlete settings

### ISSUE THREAD

**Issue by jimkeeble** [thomaschampagne/elevate#813]
I have just spent two days resyncing all activities on my Strava. 

I then tried to update my athlete profile. But it just keeps reverting to the page shown 
 
![Screenshot (64)](https://user-images.githubusercontent.com/49349922/55674340-5af26e00-58ab-11e9-9cf5-ac9ec452d168.png)

None of my swims now show a TSS.

**Comment by MMEnter** [comment]
I have the same issue trying to set it up as a new user I get the following error message:
When I edit:

> Dated athlete settings do not exists. You should add it instead.

When I try to add:

> Dated athlete settings already exists. You should edit it instead.

When I try an edit with a different date:

>Default forever dated athlete settings must exists.

When I try to add with a date before today:

> Dated athlete settings already exists. You should edit it instead.

**Comment by Coffetocode** [comment]
I had the same problem today, as a new user. After visiting a few other parts of the elevate site, then trying to sync and update the Athlete setting again my previus update was there. So the setting was saved, it just wasn't showing.

**Comment by jimkeeble** [comment]
Just tried again to update athlete settings and this comes up "Default forever dated athlete settings must exists."

**Comment by jimkeeble** [comment]
Still no TSS for swimming but TSS comes up for ride I completed yesterday

**Comment by MMEnter** [comment]
> I had the same problem today, as a new user. After visiting a few other parts of the elevate site, then trying to sync and update the Athlete setting again my previus update was there. So the setting was saved, it just wasn't showing.

I just checked that appears to not be the case for me.

**Comment by toebgen** [comment]
Same problem here, seems to be related to #810 .

**Comment by WizoneDE** [comment]
+1 fresh installation of 6.11.0 Stable
after starting the sync got the same "paradox" for athlete settings.

after first start, there was only an entry with start date today. After clicking on the reset button a second entry appeared with start date forever.

**Comment by tintwrs3** [comment]
i've the same problem "Default forever dated athlete settings must exists."

**Comment by thomaschampagne** [comment]
Could one of you upload an elevate backup?

**Comment by MMEnter** [comment]
Backup Activities? If that's not it can you tell me how?

**Comment by 20021cl** [comment]
I've had the same experience but the following resolved it for me.. Using the default athlete settings as a base, i changed only one variable - ie changed max heart rate from 190 to 164 and then "confirm changes". An error message appears indicating "Default forever dated athlete settings must exists." (which I ignore b/c A. Dont think it is related & B. not sure how to fix) but I switch between "Global Settings" and then back to "Athlete Settings" and the updated Athlete Setting then appears. Then I update all required settings and again switch between "Global Setting" and 'Athlete Setting' and the updated 'Athlete Profile' then appears to stay in place..  Hope this helps.. 
<img width="1148" alt="Screenshot 2019-04-15 21 50 12" src="https://user-images.githubusercontent.com/49604414/56130518-773b8c80-5fc8-11e9-9cac-1c2944bcd418.png">

**Comment by 20021cl** [comment]
[2019.4.16-5.20_v6.11.0.history.json.zip](https://github.com/thomaschampagne/elevate/files/3081759/2019.4.16-5.20_v6.11.0.history.json.zip)

**Comment by jimkeeble** [comment]
I tried the suggestion yesterday about switching between global and athlete settings and it did save them while I was on that session. Still no Swimming TSS so all fitness trends not accurate at all. 
However when I booked off and on again all my settings had disappeared again. 
This is really not helpful. 
Attached a backup
Jim

Jim Keeble JK Sports Coaching jim.k@talk21.com 07534096457 

    On Monday, 15 April 2019, 20:22:05 BST, 20021cl <notifications@github.com> wrote:  
 
 
2019.4.16-5.20_v6.11.0.history.json.zip

**Comment by MMEnter** [comment]
@thomaschampagne 
[2019.4.16-9.08_v6.11.0.history.json.txt](https://github.com/thomaschampagne/elevate/files/3085258/2019.4.16-9.08_v6.11.0.history.json.txt)

**Comment by thomaschampagne** [comment]
To all:

Do you have a backup of the 6.10.2 version ? 

(I would like to emulate the migration process to 6.11.0 to understand why it gone wrong with your data :/)

Thanks !

**Comment by thomaschampagne** [comment]
Fixed with aa9ec111b9d1367a1af43b7e59d954a6a51b37a2 & f774fa0ad9e6a112dac9b53b08fec627d4aedd6c Patch 6.11.1 incoming...

**Comment by jimkeeble** [comment]
Thomas 
version 6.11.1 does not appear to be available as yet as I've tried deleting the extension and then when you try and upload it again it only has 6.11.0


Jim Keeble JK Sports Coaching jim.k@talk21.com 07534096457 

    On Tuesday, 16 April 2019, 21:27:57 BST, Thomas Champagne <notifications@github.com> wrote:  
 
 
Closed #813.

**Comment by sethrevelle** [comment]
I am seeing this issue or a very similar one in version 6.13.0.  In that I re-sync every 5 hours, and initially make good progress, then regress in such a way that synching doesn't get to previous high water mark.  So I might work up to 50% of my 1500 activities, then next time through will get stuck at 22% ( after waiting 5 hours or more before attempting).  Been trying to sync now for several days, and seen this progression several times.  Is there any information I can provide to help figure this out?

**Comment by sethrevelle** [comment]
It went through in the next restart / continually update cycle for me.  I would advise anyone experiencing same issue I did to close all windows, and start completely from scratch... and (hopefully) it will eventually properly maintain record of synched and unsynched activities from start to finish for you as well!
