### ISSUE TITLE
Similar but Different Question on HRSS

### ISSUE THREAD

**Issue by A1Dan75** [thomaschampagne/elevate#817]
Hi Thomas,

While I'm digging around the Stress Score calcs, I've found similar issues with Heart Rate Stress Score to those I found with RSS...

First being that I think the Guide has a slight error (though I may be wrong!). It gives the TRIMP calculation as:

∑ δt × HRR × 0.64^(k × HRR)

But looking at other sources I believe this should be:

∑ δt × HRR × 0.64 x e^(k × HRR)

Using the latter (and equivalent change to OneHourTrimp@LTHR) I get approximately the same values as Elevate, but as with RSS they are never quite the same.

I can give an example, if you're able to find the specific values and calculations used for a run?

Thanks

Aidan

**Comment by thomaschampagne** [comment]
@A1Dan75 The calculation in code is well: ∑ δt × HRR × 0.64 x e^(k × HRR)
Look at:
https://github.com/thomaschampagne/elevate/blob/develop/plugin/core/scripts/processors/activity-computer.ts#L860

It's a typo in the manual.

Differences between HRSS & RSS can be from not enough accurate athlete settings

**Comment by A1Dan75** [comment]
Thanks Thomas, that's great.  The differences I mentioned were between my manual calculation of HRSS and the values in Elevate, but hopefully from working through that source code I can spot where the discrepancy is coming in in my calculations!

**Comment by A1Dan75** [comment]
Yep, that's cleared it up - my calculations were pre-summing the data rather than properly summing all the deltas from the original GPX.  Re-worked it from the GPX and it matches Elevate precisely.  
Thanks for the help!
