### ISSUE TITLE
RSS based on RAP

### ISSUE THREAD

**Issue by TRIWOLF79** [thomaschampagne/elevate#820]
Wouldn't make more sense to calculate the RSS based on the RAP and not in the average pace? It's no the same effort to running at the same pace when doing hilly running than when flat, and thus, the same pace for both exercises would be the same and therefore the RSS, what makes nonsense at all.

**Comment by lanzagar** [comment]
What is RAP? Do you mean GAP (grade adjusted pace), which accounts for hilly running vs flat as you mention?
In that case - GAP is actually supposed to be used - at least that is how it is presented in the help on power scores.
I have not checked the actual code, and there is another issue open about those equations: #816
(so it might be the case that it is not actually grade adjusted _pace_ that is used but _speed_ or something similar?)

**Comment by TRIWOLF79** [comment]
In my version is RAP, probably because it's Spanish; but yes, that's the point, the pondered speed in hilly running trainings.
