### ISSUE TITLE
Virtual Cycling : Cadence not reported in "Activities"

### ISSUE THREAD

**Issue by BKKDhalsim** [thomaschampagne/elevate#821]
Hello !
Thanks for the great work with the plugin !

Here's my little concern ;-)

### Step 2: Describe your environment

  * Plugin version: 6.11.1 Stable
  * Chrome/Opera/Chromium version: Chrome 73.0.3683.103 (64 bits)
  * OS version: Windows 10
  
### Step 3: Describe the problem:

The cadence data does not appear in the activity list while they do appear on Strava.
I only ride virtual routes so I don't know if the problem also appears in real rides.

#### Steps to reproduce:

  1. Open Elevate for Strava from the extension shortcut top right corner of Chrome
  2. Go to Activities
  3. Activities display empty (dash) cadence information (see : [https://imgur.com/a/dfmEEK8](https://imgur.com/a/dfmEEK8))
 
#### Actual Behavior:

  * Do you have javascript errors logs in browser console?
No

  > Press F12 to see developer console and javascript logs
I don't see anything
  
#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here. 
[2019.4.18-11.38_v6.11.1.history.zip](https://github.com/thomaschampagne/elevate/files/3093718/2019.4.18-11.38_v6.11.1.history.zip)

**Comment by thomaschampagne** [comment]
@BKKDhalsim Do you have activity links? (strava)

**Comment by missedtheapex** [comment]
I see this is quite an old issue, but it's still open so I'm going to add my inputs here...hopefully I can be of help.

I'm having the same issue that @BKKDhalsim is having. (Plugin version 6.16.2 Stable).  All of my synced Zwift activities, going back forever, are missing cadence data. Viewing the activity on Strava (with the Elevate extra stats on the activity page) shows cadence stats, and the cadence details/graphs are all shown in the "Elevate Extended Stats" popup.

However, when viewing my activity list from within Elevate, or exporting that data to a spreadsheet, the cadence data is missing and replaced with "-". This does not affect outdoor rides.

Please let me know what I can provide to help solve this problem.  Thanks!

**Comment by dolohow** [comment]
Same problem

**Comment by ArkadiuszKuprowski** [comment]
The same problem for me - all of the cadence related fields under the activities list in Elevate App are empty.
Elevate extended stats in strava is showing cadence properly
