### ISSUE TITLE
Fitness Trend more than 6 monath

### ISSUE THREAD

**Issue by speci-man** [thomaschampagne/elevate#823]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
yes
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?
yes

### Step 2: Describe your environment

  * Plugin version: 6.11
  * Chrome/Opera/Chromium version: Chrome v.73
  * OS version: Win10
  
### Step 3: Describe the problem:
I'm not able to use the "minus" sign in the fitness trend chart, even I have chose 12 months in the calendar. The date will be marked with a red underscore.
Therefore I'm only see the last 6 month in the graph. I have fresh synced date for the last 5 years.

#### Steps to reproduce:

  1. open the fitness trend graph
  2. choose 12 months in the calendar, the from date will be shown with a red marked underscore
  3. using "minus" "-" not working
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?
no
  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * show more the 6 months in the fitness graph
  
#### Media attachement:

![12_monate1](https://user-images.githubusercontent.com/25671203/57067668-ea831500-6ccf-11e9-8c19-1125e231bad5.PNG)
![12_monate](https://user-images.githubusercontent.com/25671203/57067825-5d8c8b80-6cd0-11e9-83cc-bc08aa33cf10.PNG)

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by matthew-swift** [comment]
I'm having the same problem with the latest plugin version 6.13 and Chrome 75.
