### ISSUE TITLE
Year Progressions dont go all the way back in time

### ISSUE THREAD

**Issue by donutFred** [thomaschampagne/elevate#824]
My Year Progression graph only shows 2019, 2018, 2017 however in Elevate my Strava activities are synched all the way back to 2014. Year progression used to show all previous years. Am I doing something wrong?

**Comment by angladacamps** [comment]
it simply doesn't work... it's always buggy, giving quota errors.. the old year progression was perfect.

**Comment by thomaschampagne** [comment]
@donutFred Could you provide me a backup of your elevate history?

**Comment by donutFred** [comment]
Hi Thomas - Here you go.

Attached history
