### ISSUE TITLE
Strava activity distance doesnt match 

### ISSUE THREAD

**Issue by donutFred** [thomaschampagne/elevate#825]
Massive mismatch between an activity in Strava that i loaded from GPX file

In strava the activity is 24.53km and in Elevate it is 369km!

I have hopefully attached 2 images that you can see.

![elevate activites](https://user-images.githubusercontent.com/50280334/57186890-4f39ac00-6f2a-11e9-9819-2f8d9763737d.jpeg)
![strava activity](https://user-images.githubusercontent.com/50280334/57186891-4f39ac00-6f2a-11e9-8ed4-bafbf31dac84.jpeg)

**Comment by thomaschampagne** [comment]
Strange do you have the gpx?

**Comment by thomaschampagne** [comment]
(i downloaded GPX from your activity then uploaded it to a dummy account. I have 25km distance in both strava & elevate)

**Comment by donutFred** [comment]
Strange - because now in Elevate that activity shows the correct distance for me of 24.5km.
Why did it change?

**Comment by thomaschampagne** [comment]
Do you have the source gpx (the real one)?

**Comment by donutFred** [comment]
OK, now I have more information for you. This particular file was part of a 100 hour multi-sport Adventure Race. My watch wouldn't last that long, so the race organisers gave us the GPX from the GPS trackers that we carried. I have attached the original GPX. This is for the ENTIRE Race.
[gpsseuranta_20190423raid100_nov5024.gpx.zip](https://github.com/thomaschampagne/elevate/files/3244451/gpsseuranta_20190423raid100_nov5024.gpx.zip)


I then used Strava website to manually split and crop the file into 5 parts for the 5 segments. You can see these in the screen shot of my original post.
You can also see in the Elevate screenshot of my original post that part 4 has a moving time of 00:00:00!


Now that I've re-synched it a few times, I just noticed that Elevate has interpreted these parts different again. NOTE, I haven't edited the strava activities at all. See elevate new.png

![elevate new](https://user-images.githubusercontent.com/50280334/58757059-17814c80-8548-11e9-8bba-ebd94eff83cd.png)

WAS / NOW (Moving Time / Distance)
RAID100 Part 1 Rogaine Girraween NP WAS 14:34:12 + 369km / NOW 00:00:00 + 24.5 km
RAID100 Part 2 - Mountain Bike 04:37:46 + 68km / 04:27:46 + 68.5 km
RAID100 Part 3 - More Rogaine and Scrambling down dry riverbed 07:08:19 + 217km / 00:00:00 + 53.6 km
RAID100 Part 4 So called "White water Rafting" more like waste deep in water for 5 hours at night 00:00:00 + 19km / 00:00:00 + 19.3km
RAID100 Part 5 - Putting the "Mountains" into Mountain Biking. Finally they came saved us.07:08:19 (note, same as part 3)+ 144km / 06:39:04 + 144.3 km

Obviously, I can't give you the original parts GPX, because they were done in Strava from the original overall GPX that I've attached to this message.

Hope this helps?
