### ISSUE TITLE
Please, bring back old year progressions

### ISSUE THREAD

**Issue by angladacamps** [thomaschampagne/elevate#827]
the year progressions is buggy, constantly giving quota errors. PLEASE keep old, simple, and always working year progressions button to the profile. It was perfect, it always worked.
The new progressions chart never works, it's always only displaying last 10 or 15 rides, despite of having resynced some days ago. 
So PLEASE make it happen, bring back OLD progressions chart

thank you very much

**Comment by gplatt** [comment]
Second that.  My year to date figure is way off (half the actual amount), not possible to see what is missing as I can see that some training rides are included.
