### ISSUE TITLE
Distance extra precision

### ISSUE THREAD

**Issue by troybillings** [thomaschampagne/elevate#833]
Can we get an extra digit of precision in the Distance field?  We've got a ton of other data, I don't know why we can't afford a little bit of extra space to differentiate 13 vs 13.1 miles, for example.

Big fan of Elevate otherwise.  Thanks!

**Comment by thomaschampagne** [comment]
@troybillings Which feature are you talking about? Elevate activities list?

If yes speed data has already a precision of 1 (7th param of NumberColumn constructor): https://github.com/thomaschampagne/elevate/blob/master/plugin/app/src/app/activities/activity-columns.namespace.ts#L399

You want precision of 2?

This could be a bug, please provide me here a backup of your elevate/

Thanks

**Comment by troybillings** [comment]
Hi there,

Yes, in the elevate activities list.  I'd like more than whole integer
precision (10 miles) which is what it is currently at, I don't need a bunch
more digits just 1 more digit even (to see 10.1 miles), but 2 more digits
precision would cover all my precision needs forever (say 10.13 miles).
Ideally I want miles but to gain a smidge more accuracy in my activities,
I've changed it to kilometers, since it's a smaller unit.

Not sure how to do a backup, but I can attach my latest download csv of the
activities? see attached.

Thanks!

,Troy

**Comment by thomaschampagne** [comment]
You can backup by following this: https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions#backuprestore-synced-activities

I don't understand why you don't have a precision of 1. It's already the case :/ Look at below screenshot:

![image](https://user-images.githubusercontent.com/151973/58201998-c5823080-7cd6-11e9-83b5-4d250ba1de92.png)

**Comment by troybillings** [comment]
I will look at the backup process you mention.  But FYI the column I'm
looking at for the desired precision is Distance (5th column), which in
your screenshot does not have the precision I want, see first line 11 miles
under Afternoon Ride.

,T

**Comment by troybillings** [comment]
are you saying that the best measure you have for Distance is NOT Distance
column but...
Moving Time (converted to hours, 41.25 becomes 0.6875) * Avg Moving Speed
(16.2) = 11.1375 miles

Seems like a roundabout way to compute Distance since there is already a
Distance column, but if that's the best that you've got, I can work with it.
Thanks.
,Troy

**Comment by troybillings** [comment]
hi Thomas,

I've attached my JSON backup to this email.
,Troy

**Comment by thomaschampagne** [comment]
My bad i was on wrong field :/ I fixed the ticket as below:

![image](https://user-images.githubusercontent.com/151973/58203145-bc469300-7cd9-11e9-888e-4d6eeb72f5e6.png)

**Comment by troybillings** [comment]
Thanks so much!
,Troy
