### ISSUE TITLE
Loss of data

### ISSUE THREAD

**Issue by kevinraabe** [thomaschampagne/elevate#843]
I wanted to add my running FTP to enable estimated stress scores without an HRM. However once I did that I lost all of my historical fitness, fatigue and form data - the runs are being pulled from strava but there is no curve and there are no scores.

Even when I deleted the FTP to try and go back, same thing. I already re-set everything, deleted and resynced everything multiple times and nothing happened. 

Screenshots:

![3](https://user-images.githubusercontent.com/51364481/59104021-10d44a00-8939-11e9-95b8-6459321e35eb.png)
![2](https://user-images.githubusercontent.com/51364481/59104022-116ce080-8939-11e9-9602-38e97908a8ab.png)
![1](https://user-images.githubusercontent.com/51364481/59104023-116ce080-8939-11e9-9541-96426da6b3b3.png)

Activity data:

[2019.6.7-15.27_v6.5.2.history.json.zip](https://github.com/thomaschampagne/elevate/files/3265852/2019.6.7-15.27_v6.5.2.history.json.zip)

**Comment by velofreak88** [comment]
Hey I got the same problem just a minute ago. I lost my Fitness Trend chart after either updating FTP and LTHR or switching on the option 'Dated Athlete Settings' and adding new setting dated to May 1st 2019.

Resyncing obviously did not work as well as 'clear and re-sync'.


![Bez tytułu1](https://user-images.githubusercontent.com/51515469/59150560-caa8e480-8a25-11e9-8d76-41fafe939f66.jpg)
![Bez tytułu2](https://user-images.githubusercontent.com/51515469/59150561-caa8e480-8a25-11e9-87a4-e5ff822f3252.jpg)
