### ISSUE TITLE
Form score is one day off

### ISSUE THREAD

**Issue by kevinraabe** [thomaschampagne/elevate#844]
My fitness and fatigue scores are OK, but the calculation of the form score seems to be lagging by a day or just off all together. For example on June 2 I had a run with a stress score of 92, but my form increased by 7.2.
![Screen Shot 2019-06-09 at 5 53 50 PM](https://user-images.githubusercontent.com/51364481/59160569-0902da00-8ae0-11e9-9dbc-d0abc8f89016.png)

**Comment by A1Dan75** [comment]
This is how it's meant to work...


![image](https://user-images.githubusercontent.com/24933894/59191670-153a7600-8b78-11e9-909e-1f87b45b0871.png)

**Comment by kevinraabe** [comment]
Really? It wasnt like that when I was on Firefox, this only appeared when I switched over to Chrome? Doesnt really make sense that I would **gain** form score on days of significant stress. Also isn't your form supposed to be fitness-fatigue=form?
