### ISSUE TITLE
Freshness/Neutral/Optimal/Overload, word position does not match zone in Fitness Trend

### ISSUE THREAD

**Issue by VineyardPaul** [thomaschampagne/elevate#848]
Plugin version: 6.12.0 Stable
Angular Core version: 7.2.15
Angular Material version: 7.3.7
D3js version: 5.9.2

Chrome: Version 74.0.3729.169 (Official Build) (64-bit)

Windows: Version	10.0.17134 Build 17134

Please see attached image.

I feel that the words on the righthand side should be moved _under_ the lines, not on top of, to truly represent the bands of zones. Ultimately, they should be centred between each zone line as the words represent an area, not a line.

In the example, my cursor is showing the popup box, form-> Freshness, but looking at the graph to the right, the word Neutral is above the line.

Is that clear?
  
Just a GUI update, not major functionality issue...

(BTW, love it!!!!
![2019-06-21 10_44_04-Elevate App](https://user-images.githubusercontent.com/52056064/59890077-9b757880-9412-11e9-97be-934016f54049.png)
)

**Comment by VineyardPaul** [comment]
A quick cut and paste of what I am trying to explain...
![2019-06-21 10_44_04-Elevate App](https://user-images.githubusercontent.com/52056064/59890254-703f5900-9413-11e9-8f56-5eb6f9c50274.png)

**Comment by brunopen** [comment]
I tend to agree with the remark. 
Maybe an other way to make these zones clearer would be a color code for each band...
