### ISSUE TITLE
Activities Won't Sync Even After 5+ Hours

### ISSUE THREAD

**Issue by bumski** [thomaschampagne/elevate#851]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions? Yes
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues? Yes

### Step 2: Describe your environment

  * Plugin version: 6.12.0 Stable
  * Chrome/Opera/Chromium version: Version 75.0.3770.100 (Official Build) (64-bit)
  * OS version: Windows 10
  
### Step 3: Describe the problem:

I have been trying to sync since many hours ago today, yet I continually get the wait 4-5 hour warning.  However, no activities of mine have been synced.  I am unable to sync anything due to this.

#### Steps to reproduce:

  1. Open extension
  2. Click Sync
  3. Click Start Sync
  
#### Actual Behavior:

  * What happened?

  * Do you have javascript errors logs in browser console?  Yes

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ``` 
  ERROR SYNC_1: Not synced. SyncState is: NOT_SYNCED
(anonymous) @ 9.1b027735be8a67cc53dc.js:1

#### Expected Behavior:

  * What did you expect to happen? I expected it to sync about a few hundred activities and then not work for a few hours.
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by rvhilst** [comment]
How did you resolve this?
