### ISSUE TITLE
Plus de classement

### ISSUE THREAD

**Issue by NoemieLa** [thomaschampagne/elevate#857]
Je continue d'avoir mes chronos et des PR, mais je ne suis plus classée dans le classement et ne peux donc plus faire de QOM.
Pouvez vous corriger ce bug?
Merci

**Comment by thomaschampagne** [comment]
Je comprends pas le réel problème derrière.  Est-ce vraiment un bug? Quel est le résultat attendu?

Merci de ré-ouvrir le ticket si besoin
