### ISSUE TITLE
Syncing only opening Strava page

### ISSUE THREAD

**Issue by leboyd** [thomaschampagne/elevate#861]
I checked other issues and did not find this simply one I am having.

Plugin version: 6.13.0 Stable
Angular Core version: 8.0.0
Angular Material version: 8.0.0
D3js version: 5.9.2

Chrome - Version 74.0.3729.169 (Official Build) (64-bit)

Windows 10 Pro, Version 1803, OS Build 17134.556

###
I recently created a Strava account and uploaded activities for the year from Polar Flow.  Everything looks good on Strava.

Today I installed the Elevate add-on, modified the Athlete and other settings and then selected "Activities not synced".

The pop up window about the time required and to make sure the settings were set was displayed and I selected "start sync".

The Strava dashboard is opened in a new Chrome window but nothing seems to happen.

I expected some kind of message or status that syncing was occurring.

I have 74 running and cycling activities.

I'm obviously doing something wrong as this is basic, I know.  

Thanks for the help

**Comment by rvhilst** [comment]
I'm getting a similar issue as of yesterday. With the standard message of "Please continue you synchronization after 4-5 hours....." This is normal after the extension has synch'd a bunch of activities, but I'm getting it on my first attempt now, even after leaving it overnight and trying again. 


![Synching error](https://user-images.githubusercontent.com/53023992/61419312-101fd200-a941-11e9-9032-7e0953149202.JPG)
