### ISSUE TITLE
Fitness Trend displays as a flat line

### ISSUE THREAD

**Issue by DScott7** [thomaschampagne/elevate#863]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
Yes

  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?
Yes

### Step 2: Describe your environment

  * Plugin version: 6.13
  * Chrome/Opera/Chromium version: Version 75.0.3770.142 (Official Build) (64-bit)
  * OS version: Windows 10
  
### Step 3: Describe the problem:
Fitness Trend shows everything as zero, no difference between workouts.  Fitness, Fatigue, Form all at zero, stress score rates as "-"

#### Steps to reproduce:

  1. Log in
  2. Click on "Fitness Trend"
  3. Observe flat line
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  I thought it would show me different scores for my workouts.
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by grobbie** [comment]
Same here but on Mac OSX. Chrome Version 75.0.3770.142 (Official Build) (64-bit). Also some charts in Strava like relative effort don't display - just hangs when loading
