### ISSUE TITLE
Virtual ride not listed in year progression, yet showing in activities

### ISSUE THREAD

**Issue by arthurvanhoeysmith** [thomaschampagne/elevate#869]
This issue was reported before, but no answer was given. I have hide virtual rides toggled off, FTP is listed, the virtual ride is listed in my activities, but simply is not listed in the yearly progression. My normal rides and runs are listed correctly.

I view the stravistics on my desktop.

**Comment by thomaschampagne** [comment]
You have to check the "virtualride" checkbox sport type in year progressions

Please reopen with more infos if problem persist
