### ISSUE TITLE
Year progressions

### ISSUE THREAD

**Issue by tkajstura** [thomaschampagne/elevate#870]
### Step 2: Describe your environment

  * Plugin version: 6.13.0 Stable
  * Chrome/Opera/Chromium version: Chrome 75.0.3770.142 (Official Build) (64-bit)
  * OS version: macOS 10.14.5
  
### Step 3: Describe the problem:

In Year Progressions, leap years (eg. 2016) get displayed as Jan 1 - Jan 1 instead of Jan - Dec 31 with an added day for Feb 29. When you click on the last day of the year in the graph (Jan 1) the totals for the years reflect only data for Jan 1 instead of the 365 or 366 days in that year. Clicking on the day before the last day in the graph (Dec 31) shows data for 365 days correct, but is incomplete for the leap year since everything is shifted by a day (and the last day, Dec 31st shows up as Jan 1).

#### Steps to reproduce:

  1. Open Elevate plugin.
  2. Click on Year Progressions.
  3. Click on last day in graph.

**Comment by osirion** [comment]
I can confirm that I have the same issue.
I dont know if its related, but this also may be linked to incorrect totals displayed for the years and their respective distance:
"No mouseover":
[http://tinyimg.io/i/6pQHvi1.jpg](url)
"Mouseover on last day of 2013":
[http://tinyimg.io/i/DwXOWBy.jpg](url)
