### ISSUE TITLE
Training Plan/Calendar based on Current Fitness Trend

### ISSUE THREAD

**Issue by cameronmehl** [thomaschampagne/elevate#873]
I would love to have an automatically generated (or generate one easily) training plan based on prior activities and my current fitness trend. Not looking really for exact workouts, but more for somethign like "FTP" workout or "VO2 Max" workout days again, based on the current fitness trend. Perhaps even a recommended workout type for the next day, week, or month.

Does anything like this exist? Is this type of feature desired by others?

Disclaimer: I have **not** explored strava's own training plans.

**Thank you _very_ much** - I use the elevate app daily.

Best,
Cameron

**Comment by ndaman** [comment]
I think training plans like what you are mentioning would need to be perhaps a community effort to build various types of training plans.

What I would like to see is the ability to see future fitness and fatigue based on possible future exercises.
