### ISSUE TITLE
Averages are wrong

### ISSUE THREAD

**Issue by simoncarbajal** [thomaschampagne/elevate#874]
### Step 2: Describe your environment
  * Plugin version: 6.13.0 Stable
  * Angular Core version: 8.0.0
  * Angular Material version: 8.0.0
  * D3js version: 5.9.2
  * Chrome version: 76.0.3809.100 (Official Build) (64-bit)
  * OS version: macOS Mojave v10.14.6
  
### Step 3: Describe the problem:
Averages are wrong.

For instance, https://www.strava.com/activities/2627225582
Avg Speed: 27.2 km/h is wrong.
Since 154,57 kms in 5:25:50 hs gives an average speed of
154,57km / (5 + 25/60 + 50/3600)h = 28,46 km/h

Avg Ascent: 913 vm/h is wrong.
Since 2,562m in 5:25:50 hs gives an average speed of
2,562m / (5 + 25/60 + 50/3600)h = 471.77 vm/h

#### Steps to reproduce:
Click in "Display elevate extended stats" and see the values.

**Comment by ckald** [comment]
I noticed that your math is wrong. When you compute duration in hours, the formula should be `hours + minutes/60 + seconds/3600`. Then average speed is 28,46 which agrees with Strava's number. 

But I confirm that Elevate's average seems wrong
