### ISSUE TITLE
Loss of database, when not synced for awhile

### ISSUE THREAD

**Issue by roccolord** [thomaschampagne/elevate#879]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____6.13.0
  * Chrome/Opera/Chromium version: _____chrome 77.0.3865.70
  * OS version: _____os x 10.13.6
  
### Step 3: Describe the problem:
Not been syncing for 18 days. When autosync is run all data is lost only last 20 records shows.
#### Steps to reproduce:

  1. _____sync all data
  2. _____wait 18 days
  3. _____start plugin again.
  
#### Actual Behavior:

  * What happened?
All records before sync (they where visible) are gone and only last 20 activities are available.
  * Do you have javascript errors logs in browser console?
no
  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * The additional 18 days to be added to the already synced data.

**Comment by thomaschampagne** [comment]
Could you provide a backup before the 18 days and after? Thanks

**Comment by thomaschampagne** [comment]
Did you logon on another strava account between sync?
If problem persist please re-open ticket

**Comment by roccolord** [comment]
Same account. Only have one. Will try to find a backup. Where is the DB stored?

**Comment by roccolord** [comment]
Happened again, where is the db stored?

**Comment by roccolord** [comment]
2019/12/10-14:02:20.745 11403 Reusing MANIFEST /Users/robert/Library/Application Support/Google/Chrome/Profile 3/Local Extension Settings/dhiaggccakkgdfcadnklkbljcgicpckn/MANIFEST-000001
2019/12/10-14:02:20.747 11403 Recovering log #1571
2019/12/10-14:02:20.747 11403 Reusing old log /Users/robert/Library/Application Support/Google/Chrome/Profile 3/Local Extension Settings/dhiaggccakkgdfcadnklkbljcgicpckn/001571.log
2019/12/10-18:17:39.447 14a27 Level-0 table #1576: started
2019/12/10-18:17:39.498 14a27 Level-0 table #1576: 3156021 bytes OK
2019/12/10-18:17:39.568 14a27 Delete type=0 #1571
2019/12/10-18:19:03.329 14a27 Compacting 1@1 + 1@2 files
2019/12/10-18:19:03.385 14a27 Generated table #1577@1: 4 keys, 3156139 bytes
2019/12/10-18:19:03.411 14a27 Compacted 1@1 + 1@2 files => 3156139 bytes
2019/12/10-18:19:03.453 14a27 compacted to: files[ 0 1 2 0 0 0 0 ]
2019/12/10-18:19:03.472 14a27 Delete type=2 #1573
2019/12/10-18:19:03.472 14a27 Delete type=2 #1576
