### ISSUE TITLE
feature request: "Body efficiency" metric

### ISSUE THREAD

**Issue by anverx** [thomaschampagne/elevate#880]
To calculate "BE" per ride divide average power with average heart rate, that is work done per effort made.  The more work you do at the same effort the more efficient your body is.   Using weighted avg. power over raw avg. power might make more sense. 
 
It's also possible to graph it for a ride, that's average power and HR over a time window like 1 minute, then divide one by the other to get the value for one point.

Another cool graph would be "BE" over long periods of time, like a year or six months, same time scale as fitness/freshness.

**Comment by thomaschampagne** [comment]
Hi I'm brainstorming this.... And thinking if it makes sense to skip the time in the formulas? For example:

- Ride A of **4 hours** with: 160bpm avg & 150 watts avg => 0.937 BE
- Ride B of **1 hours** with: 175bpm avg & 250 watts avg => 1.428 BE

So BE ride B > ride A. But it doesn't mean that you have less efficiency on ride A which took 4 hours..

Your opinion?

**Comment by anverx** [comment]
I suppose this takes a bit of research to get it right.  At the moment i have 3 ideas:

- HR shouldn't count from zero.  Any power generated at rest HR should yield infinite efficiency.  Thus we can do: BE = Avg(Power)/(Avg(HR) - rest HR) 

- Effort is not linear, so going from 170 to 180 is a lot harder then from 140 to 150.  We could do an exponential transformation.  (It could also be square or cube, but those are quite arbitrary)

- We could factor in the duration of activity, the easiest way would be to just use stava's suffer score or what ever it is called now instead of average HR.  This i don't like very much.  I don't think BE should depend on duration.  If anything it should drop as you get tiered.

I found this, it's relevant but not quite the same thing: https://www.cyclinganalytics.com/blog/2013/06/heart-rate-vs-power-chart

**Comment by thomaschampagne** [comment]
So you basically need a hr based stress score: Trimp or HRSS (check formulas within extension)

**Comment by avipilot** [comment]
This is a good feature request but I would suggest using 
BE = 75% Watts / 75% HRM.
The reason for this to me is this... I can compare all my ride types with this formula very accurately (if I am commuting and have stop lights which may differ day-to-day, I can still make a good judgement based on the 75% statistical data).

Also, we can plot these two variables x-axis=75% HRM, y-axis=75% Watts to see athlete's capability.. 

BTW, isn't this feature request (BE) something similar to EF in Training Peaks???

**Comment by anverx** [comment]
It might be difficult to express BE as a single number.  How can we compare efficiency at 150w with efficiency at 600w?  So how about a graph (somewhat similar to power curve) of HR vs power.  Go through all possible power values and average HR over each.  Then we could compare this BE curve from one ride to another.  Maybe an area under this curve could be a useful metric.  I need to graph some numbers to see if any of this makes sense.
