### ISSUE TITLE
Strava Summit Fitness feature not on my Iphone 7

### ISSUE THREAD

**Issue by sorenmoller73** [thomaschampagne/elevate#881]
Dear Strava, 

See attached pictures.
I read your blog today: "Fitness was a mystery. Now it's a number."
On my profile https://www.strava.com/athletes/18900995 I cannot see the new Summit feature on my Iphone 7, that was described in the blog. Btw my iOS 12.4.1 should be fairly newly updated.

Why is this??

Regards
Søren 

![IMG_1530](https://user-images.githubusercontent.com/55535189/65239622-b9b94600-dadf-11e9-855c-a9c91b81b54f.PNG)

![Strava1](https://user-images.githubusercontent.com/55535189/65239646-c9388f00-dadf-11e9-96a0-fd50883227dc.jpg)

**Comment by thomaschampagne** [comment]
wrong project
