### ISSUE TITLE
Incoherent year progression between elevate and strava

### ISSUE THREAD

**Issue by docles2000** [thomaschampagne/elevate#886]
### Step 2: Describe your environment

  * Plugin version: _____6.14
  * Chrome/Opera/Chromium version: _____ 77.0.3865.90
  * OS version: _____windows 10
  
### Step 3: Describe the problem:

incoherent values in year progression between Strava and Elevate for 2019. 
I already cleared and synced all activities (705 activities) and didn't fix the issue

  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:
I upload images from Strava and from elevate.

![strava ](https://user-images.githubusercontent.com/55985078/65879621-948dc880-e366-11e9-864e-90d5ca8f76fa.png)
![elevate](https://user-images.githubusercontent.com/55985078/65879630-98214f80-e366-11e9-880d-ac178c9500f7.png)

**Comment by dundeeedd** [comment]
I have same issue.  I have over 200kms in Strava and all these are in my activities in Elevate but Year progression does not show this

**Comment by thomaschampagne** [comment]
Do you have virtual rides not checked on elevate side?

Also for ebike rides?

**Comment by dundeeedd** [comment]
Hi Thomas

That was teh first thing I checked and they are on.

[image: image.png]

**Comment by thomaschampagne** [comment]
Can't see images on github when replied by mail. 

Try to export a CSV from activities section. Import it into excel and let me know if travelled distance are correct between CSV export and year progression

**Comment by dundeeedd** [comment]
Hi Tomas - Will do this now and update

**Comment by dundeeedd** [comment]
Hi So for 2019 the excel states 2050kms and the yearly progression dashboard states 719kms.  I have attached the excel 
[elevate_activities_export.2019.10.21-12.28.29.xlsx](https://github.com/thomaschampagne/elevate/files/3750525/elevate_activities_export.2019.10.21-12.28.29.xlsx)

**Comment by dundeeedd** [comment]
Also here is a snapshot of my dashboard 
![elevate ](https://user-images.githubusercontent.com/17157874/67202537-bd9ef780-f400-11e9-9f29-24895e4547a3.png)

**Comment by docles2000** [comment]
Hi,

I feel that the issue is on strava.
I just made manually the sum of each bike activity for the year, the result
is exactly the same than ELEVATE, where strava shows 10% more.
Using another tool (veloviewer) gives the same result as you Elevate.
Then, I just opened a ticket on strava
I will keep you posted
Charles Doceur
+55 11 989 422 469

**Comment by dundeeedd** [comment]
HI CHarles

I have the opposite from you.  All stats are fine from strava and in my
activities on Elevate.  The activities on elevate are not showing on yearly
progression in Elevate

**Comment by thomaschampagne** [comment]
@dundeeedd The virtual rides are not ticked in activities list of your last screenshot.

If problem persist please provide me an elevate backup and strava activities links (public accessible) so i can debug.

Thanks

**Comment by dundeeedd** [comment]
@thomaschampagne thank you Tomas - PICNIC - (Problem In Chair Not In Computer). LOL I was thinking that the virtual ride slider being on was enough.  Didn't realize I had to tick virtual rides too from dropdown - so thank you

**Comment by docles2000** [comment]
Ok

I keep you posted on Strava answer and let's see

Charles Doceur
+55 11 989 422 469

**Comment by docles2000** [comment]
Hi

Strava just answered me about the issue.
They suggested me to do a refresh on the statistic calculations.

It did resolve the issue, now having same number in Strava and Elevate.
Thanks for your support
Charles Doceur
+55 11 989 422 469
