### ISSUE TITLE
Swimming Stress Score (SSS)

### ISSUE THREAD

**Issue by Bezzinatef** [thomaschampagne/elevate#888]
I think there is a bug with the Swimming Stress Score (SSS).
It's mentionned that the SSS is calculated from workout **moving duration**, distance and athlete Swimming Functional Threshold Pace (SFTP). But it's actually calculated from the **elapsed time**.
I added a manual activity on Strava with the same swim speed but with the elapsed time not the moving one and it's showed the same SSS from the activity synced with m Garmin account...

**Comment by thomaschampagne** [comment]
It's not a bug. Moving duration is use if available: https://github.com/thomaschampagne/elevate/blob/master/plugin/app/src/app/fitness-trend/shared/services/fitness.service.ts#L212

If not (case of manual) elapsed time is used instead
