### ISSUE TITLE
Just installed Elevate, Didn't realize I'd lose visibility to routes on Strava maps ... What now?

### ISSUE THREAD

**Issue by rls241** [thomaschampagne/elevate#889]
Hi,
I'm not overly technical and I'm unable to find my answers elsewhere and what I've tried thus far has not worked so I'm looking for assistance here.
I was impressed with the notion of getting additional fitness data through Elevate via Google Chrome but when I installed and begin syncing my previous runs, I noticed I lost the ability to zoom in on run mapping routes in my Strava activity feed. I then googled this issue and saw a few other people reported having the same issue and there doesn't appear to be a fix for this if you are using Google.
At this point, I just want to go back to my regular Strava account and restore my ability to view routes close up. I use this feature a lot and do not wish to lose this capability.
I've tried deleting my activities on Elevate and removing the Chrome add in but nothing yet has restored the maps, splits, etc on Strava and I'm freaking out a bit!
I just want to go back to what I had before on Strava; does anyone know what my options are?

Thank you!

**Comment by rymalia** [comment]
Can you share a screenshot of this? I'm not understanding where you're seeing this issue.

**Comment by thomaschampagne** [comment]
Same

False positive?

**Comment by rls241** [comment]
I uninstalled Elevate and the very next day thankfully my maps on Strava, to include the route I took, were restored.
I use the routes a lot on my desktop Strava so unfortunately I don't think Elevate is going to work for me. I need the actual map routes to plan my training runs and to prepare for races.

**Comment by thomaschampagne** [comment]
Do you use the latest version on chrome?

Make sure to install from https://thomaschampagne.github.io/elevate/#/landing

You shoudn't have any problem with routes on latest 6.14.0 version

**Comment by thomaschampagne** [comment]
Make sure to update your chrome too.

Do you run any other extensions for strava?

**Comment by rymalia** [comment]
> I uninstalled Elevate and the very next day thankfully my maps on Strava, to include the route I took, were restored.

Are you sure the map view and splits “went away” with Elevate activated or did you not notice that they’re just shown a little further down the page, below the Elevate analytics info? I’m not entirely sure, but I think if you reinstall the plugin and just scroll down a bit when looking at the detail page of an activity in Strava that you’ll see the normal map view and splits you’re referring to.
