### ISSUE TITLE
Wrong  Avg Moving Speed 

### ISSUE THREAD

**Issue by gizmou** [thomaschampagne/elevate#892]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.14.0 Stable
  * Chrome version: 77.0.3865.120 (Build oficial) (64 bits)
  * OS version: Microsoft Windows 6.1.7601 (Windows 7 SP 1)
  
### Step 3: Describe the problem:

Viewing Activities, the average Moving Speed is not calculated correctly.
For example
Moving Time 03:06:33
Distance: 52.2 km
Avg Moving Speed Given: 16.4 kph
The real Avg Speed is 16.8 kph

#### Steps to reproduce:

  1. Open Elevate Plugin
  2. Go to Activities
  3. View the column Avg Moving Speed
  
  
#### Media attachement:
![image](https://user-images.githubusercontent.com/47594644/67615934-b0a05080-f7d2-11e9-89ce-dbf0c01041a4.png)
>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here. 
[2019.10.26-9.28_v6.14.0.history.zip](https://github.com/thomaschampagne/elevate/files/3774564/2019.10.26-9.28_v6.14.0.history.zip)

**Comment by afunkebr** [comment]
I confirm the "avg moving speed" column does not provide the "avg moving speed" as obtained by dividing Distance by Moving time (taking into account proper unit conversions). Perhaps the column title does not accurately reflect actual calculation used. I've attempted to inspect the plugin source code and found that this column is defined in the file app/modules/shared/models/activity-data/speed-data.model.ts as:

`new NumberColumn(Category.COMMON, "extendedStats.speedData.genuineAvgSpeed", Definition.SPEED_SYSTEM_UNITS, "Avg Moving Speed", Print.number, 1, 1, Constant.KM_TO_MILE_FACTOR).setDefault(true),`

That points us to a perhaps different average speed concept, which is "genuineAvgSpeed". Again grepping the source code tree for this term, I've found the following definitions in the file "core/scripts/processors/activity-computer.ts":

`const genuineAvgSpeed: number = genuineAvgSpeedSum / genuineAvgSpeedSecondsSum;`

`// distance
					genuineAvgSpeedSum += this.discreteValueBetween(velocityArray[i] * 3.6, velocityArray[i - 1] * 3.6, movingSeconds);`

`// time
					genuineAvgSpeedSecondsSum += movingSeconds;`

Perhaps someone more familiar with the concept of "genuineAvgSpeed" and its source statistics could clarify whether the column name is mistaken or explain what actually is "GenuineAvgSpeed"...

**Comment by avipilot** [comment]
I confirm too. I see a similar difference in all my data as well. I have the following data
Total distance: 7.11 miles (11.44 km)
Moving Time: 33:16 minutes (0.554444 hours)
Elapsed Time: 36:15 minutes (0.604167 hours)
STRAVA calculated values:
  Avg: 12.8 mph (20.6 kph)

Elevate calculated values (from extended statistics):
  Avg:12.6 mph (20.3 kph)

My calculations based on Moving time listed above
  Avg: 12.82 mph (20.64 kph)

If Elevate has a different moving time than what STRAVA evaluated, that could be a reason for it... For my example Elevate thinks my moving time is 33:51 instead of 33:16 that STRAVA notes.... That could explain the difference.
