### ISSUE TITLE
Fitness Trend not using Estimated PSS?

### ISSUE THREAD

**Issue by NordieBoy** [thomaschampagne/elevate#895]
I have the Estimated PSS ticked, but:
46 HRSS  & 206 Power SS -> 46 Stress Score.

**Comment by NordieBoy** [comment]
An hour long gravel ride 206w estimated weighted avg power (FTP 217 so seems about right).
Several Strava PB's.
57 HRSS & 258 Power SS -> 57 Stress Score.
Fitness +0.1

**Comment by NordieBoy** [comment]
164 HRSS  &  529 PowerSS   ➔  164 Stress score

**Comment by thomaschampagne** [comment]
That's normal. Heart rate data is used over estimated power.
If you had a real power meter, the power data would have been used instead.

**Comment by NordieBoy** [comment]
"Fitness Trend will USE AND DISPLAY estimated PSS"
It seems to display it OK, but does not USE it at all in the fitness trend calculations.
My fitness trend is dropping like a stone since my power meter died.
![Screenshot 2019-12-17 at 18 55 41](https://user-images.githubusercontent.com/57917233/70968798-1b994400-20ff-11ea-8b28-23b4e868608d.png)
