### ISSUE TITLE
Pace from manual entries not importing into Elevate

### ISSUE THREAD

**Issue by kellylint** [thomaschampagne/elevate#897]
I'm not sure what's going on but any manual entry runs from Strava do not import with a pace! Therefore estimated RSS doesn't work as it depends on average pace

See screenshot. Last 3 runs all on treadmill with no HR data... (see screenshot)
https://www.strava.com/activities/2905030623
https://www.strava.com/activities/2903022328
https://www.strava.com/activities/2898377620

Am I just doing something stupid?

Thanks

![Screen Shot 2019-12-01 at 1 35 42 PM](https://user-images.githubusercontent.com/58403267/69920679-87ad5400-143f-11ea-9c3d-7d061aa99272.png)

**Comment by Tyler959** [comment]
I've seen the same issue. I ran last week on a treadmill and forgot my watch. This morning, the app I use for cycling crashed. Neither count toward my fitness trend. I just started using Elevate recently and it looks like a lot of my old treadmill runs are also not counting. 

I'll be happy to donate if this can be fixed! The fitness trend data is very helpful, but it loses all of its value if a day with a decent workout is calculated as a rest day.

<img width="1190" alt="Screen Shot 2019-12-07 at 9 20 10 AM" src="https://user-images.githubusercontent.com/58631209/70376177-215b8200-18d4-11ea-8cbf-09e817b17116.png">

**Comment by owenhenley** [comment]
Same issue for me that I've only just clocked onto. No average pace from a manual entry with no HR, so no RSS, thus inaccurate graph data unfortunately.

![Screenshot 2020-01-31 at 13 26 01](https://user-images.githubusercontent.com/28428200/73542719-43cdcf80-442d-11ea-8d13-f6317b5b391d.png)

**Comment by MarkLutterman** [comment]
I agree with the above that it would be nice to have a way to have manual entries calculate in Fitness trends.  That might require some particular inputs like average pace, or other data to calculate RSS, or such.

**Comment by thomaschampagne** [comment]
Fixed with https://github.com/thomaschampagne/elevate/pull/953

Coming with next release
