### ISSUE TITLE
Activities not syncing 

### ISSUE THREAD

**Issue by duarteteixeira** [thomaschampagne/elevate#900]
* Plugin version: 6.15.0 Stable
  * Chrome version: 78.0.3904.108 (Official Build) (64-bit)
  * OS version: Windows 10
  
#### Steps to reproduce:

1. Fresh installation of the Elevate app plugin
2. Started sync
3. Sync founds 249 activities and processed them all
4. No activities are shown.
5. selected option "Clear and re-sync activites"
6. finds the same 249 activities and processes them
7 . no activities show up
8. selected "clear synced activites" and sync again
9. same sad results

  after a few tries, I got blocked for the day (image bellow)

![image](https://user-images.githubusercontent.com/19978831/70249782-cbbc9380-1774-11ea-8cd3-d6675ff13f16.png)

**Comment by owenhenley** [comment]
Has been fixed. Waiting for Google to approve release

https://github.com/thomaschampagne/elevate/issues/899

**Comment by duarteteixeira** [comment]
thanks!

**Comment by xenius** [comment]
Not updated on the store yet? Something went wrong?

**Comment by thomaschampagne** [comment]
Still pending review by google. It only fixes the last sync date not updated.

The message you are getting you will still ahev if you perform too much queries to strava. Not elevate but. Strava behavior. See https://blog.usejournal.com/elevate-for-strava-is-jumping-the-strava-fence-to-become-an-independent-desktop-training-app-1f644c2af824

**Comment by tijnbenedek** [comment]
Thanks! Hopefully it works soon

**Comment by thomaschampagne** [comment]
![image](https://user-images.githubusercontent.com/151973/70468012-92628b80-1ac6-11ea-9046-caa626227b68.png)

**Comment by tijnbenedek** [comment]
Yes! Works again :) Thanks Thomas
