### ISSUE TITLE
Desktop vs Webapp

### ISSUE THREAD

**Issue by tomglynch** [thomaschampagne/elevate#901]
Hi Thomas,

Appreciate all your work and feel free to close this issue right away but just thought I'd put it out there.

Currently there are quite a few desktop apps on the market but not a fully featured webapp. The current Elevate user base is largely already using web apps but may not be using any desktop apps for training related data. Given your app currently runs in browser, is there much stopping you from building out a webapp rather than the three pronged (linux, windows, mac) desktop apps? What would the costs be?

It just seems odd to me from a product perspective that you're going the desktop route rather than a fully fledged webapp. I see huge potential in Elevate jumping the 'Strava Fence' but was surprised when you announced it would be as a desktop app. 

As I said earlier, feel free to close this issue because of course the choice is completely up to you, but it might be worth keeping this open and seeing if anyone else would like to chime in to the discussion.

Kind regards,

Tom

**Comment by thomaschampagne** [comment]
@tomglynch Could you post this on the medium story instead for everyone? Github issues are dedicated to bug/features

i have a reply for you ;)

Thanks

**Comment by tomglynch** [comment]
Good idea, cheers. I'm out and quite tipsy atm but will do tomorrow
