### ISSUE TITLE
Missing Extended Stats for Nordic Ski activities

### ISSUE THREAD

**Issue by igiskard** [thomaschampagne/elevate#911]
* Plugin version: 6.15.1
  * Chrome version: 79.0.3945.88
  * OS version: Windows 10
  
In the "Nordic Ski" activities the "Display elevate extend stats" button is missing.
The button is present in the other activities like "Ride" or "Walk".
Thanks.

**Comment by thomaschampagne** [comment]
Hi @igiskard Could you post some Nordic activities please? thanks

**Comment by igiskard** [comment]
Hi Thomas,
here a couple of Nordic Ski segments where you can find a lot of activities:
https://www.strava.com/segments/6127447
https://www.strava.com/segments/6330352

**Comment by thomaschampagne** [comment]
Here's a build: [v6.15.1_stable_2020-02-06-22-23.zip](https://github.com/thomaschampagne/elevate/files/4167800/v6.15.1_stable_2020-02-06-22-23.zip)

Could you perform some tests and validate the fix?

**Comment by igiskard** [comment]
Hi,
I overwrite the new version into my extension dir:
C:\Users\Andrea\AppData\Local\Google\Chrome\User Data\Default\Extensions\<extid>\6.15.1_0
but I still don't see the Extended Stats button.
Maybe I did it wrong?

**Comment by thomaschampagne** [comment]
You dont need to do that. Just follow INSTALL.txt in the zip file.

**Comment by igiskard** [comment]
Whoopsie daisy, I totally missed the Install instructions ... 
Now it's OK, I can see the Extended Stats button for the Nordic Ski activities, thanks Thomas.
