### ISSUE TITLE
Using RSS ahead of HRSS for specific runs

### ISSUE THREAD

**Issue by A1Dan75** [thomaschampagne/elevate#912]
Hi,

I'm just wondering if it's possible to get elevate to use RSS ahead of HRSS for specific runs?  

I've done a couple recently for which I didn't wear my HRM strap.  My watch has a built in HRM, so HR is still recorded, but ti's totally inaccurate when running (far too low), leading to totally inaccurate HRSS.  In these cases the RSS would be a much better approximation.  

Would be great if there's a way to do this - it's annoying to know that my fitness trend is incorrect because of this.

Thanks

Aidan

**Comment by thomaschampagne** [comment]
Pinned.

And for cycling:
- EstPSS instead of HRSS (PSS only has priority over HRSS)
- HRSS instead of PSS

Link: 
- https://github.com/thomaschampagne/elevate/issues/736
- https://github.com/thomaschampagne/elevate/issues/686

**Comment by A1Dan75** [comment]
Thanks for picking up Thomas, and thanks again for all the hard work! 

I see a few other people have had similar requests (apologies, I did try and search to see if there was already an open ticket, couldn't find any!).

I'm not too clear on the status / resolution though, may have missed it in one of those other tickets - is the ability to chose RSS over HRSS for specific runs something that you are planning to introduce?

**Comment by tjin92** [comment]
I have a similar request. My power meter died halfway through my ride, so I have an inaccurate PSS; there should be an option to choose HRSS instead.
