### ISSUE TITLE
Year Progressions - 60 minutes should be an hour

### ISSUE THREAD

**Issue by waldev** [thomaschampagne/elevate#913]
* Plugin version: 6.15.1 Stable
  * Chrome: 79.0.3945.117
  * OS version: Windows 10 Pro

Today when I checked my year progression, the time is displaying as "18 h, 60 min" - this should probably be "19 h"?

![image](https://user-images.githubusercontent.com/4507145/72688738-45aaaf80-3b5e-11ea-9f14-bc9fc334cd92.png)

**Comment by thomaschampagne** [comment]
You right :) Nice one !
