### ISSUE TITLE
Missing Extended Stats for Indoor Rowing activities

### ISSUE THREAD

**Issue by vk2him** [thomaschampagne/elevate#914]
* Plugin version: 6.15.1 Stable
  * Chrome/Opera/Chromium version: Version 79.0.3945.130 (Official Build) (64-bit)
  * OS version: MACOS 10.15.2
  
Similar to the "Nordic Ski" issue, in all Rowing activities the "Display elevate extend stats" button is missing.
The button is present in the other activities like "Ride" or "Walk".
Thanks Ian

![Screen Shot 126](https://user-images.githubusercontent.com/22878629/73435949-b8f1c400-439d-11ea-97d0-aec73645ea96.jpg)

**Comment by thomaschampagne** [comment]
@vk2him Could you post me some rowing activities? Thanks

**Comment by vk2him** [comment]
Thanks Thomas - I just emailed you @ Gmail

**Comment by thomaschampagne** [comment]
Closed by https://github.com/thomaschampagne/elevate/commit/02e4c527491a92811a93bc007a4d9fe16fd5f933

**Comment by thomaschampagne** [comment]
Here's a build: [v6.15.1_stable_2020-02-06-22-23.zip](https://github.com/thomaschampagne/elevate/files/4167800/v6.15.1_stable_2020-02-06-22-23.zip)

Could you perform some tests and validate the fix?

**Comment by vk2him** [comment]
Hi Thomas,
 
It is working perfectly, many thanks! One suggestion – rowing activities have cadence data, otherwise knows as Strokes Per Minute. I notice the extended stats don’t include Cadence for rowing – could that be added with the appropriate Athlete Cadence settings?
 
I’ll be sending you a Paypal donation, I really appreciate the effort you’ve put into this, it is very helpful.
 
Cheers
Ian
