### ISSUE TITLE
Syncing resets continually - activites not being synced.

### ISSUE THREAD

**Issue by PureAbstract** [thomaschampagne/elevate#915]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.15.1 Stable
  * Chrome:  79.0.3945.13
  * OS version: OS X 10.14.6
  
### Step 3: Describe the problem:

Syncing never completes. Every so often it tells me to try again in a few hours, and it resets to the beginning.

#### Steps to reproduce:

  1. Install Elevate
  2. Start syncing
  3. Wait for it to pause. Wait a while. Continue syncing. Notice that it's reset to the beginning.
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
I expected activites to be synced. This is not happening.
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem
If I had any, I wouldn't have the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
I aware of the problem. It's on Strava side :/. I can't fix it.

All is explained in this post: https://blog.usejournal.com/elevate-for-strava-is-jumping-the-strava-fence-to-become-an-independent-desktop-training-app-1f644c2af824

The good news: a new independant project is on development to overcome the problem.
