### ISSUE TITLE
Strava has modified segment details, Elevate now obscures them

### ISSUE THREAD

**Issue by JMA72** [thomaschampagne/elevate#919]
Elevate buttons became to big to see the segment details of a ride anymore:
![image](https://user-images.githubusercontent.com/46564651/74939189-c3790980-53ef-11ea-9a05-6b6c325011aa.png)

**Comment by dabdab825** [comment]
Same issue here !

**Comment by tomglynch** [comment]
Issue fixed and now to be closed.
