### ISSUE TITLE
Segment expansion bug

### ISSUE THREAD

**Issue by shaunginsbourg** [thomaschampagne/elevate#920]
### Step 2: Describe your environment

  * Plugin version: _____6.16.0
  * Chrome/Opera/Chromium version: _____Version 80.0.3987.116 (Official Build) (64-bit)
  * OS version: _____Win 10 Pro
  
### Step 3: Describe the problem:

Elevate blocks out segment data in expanded view

#### Steps to reproduce:

  1. _____go to activity overview
  2. _____click on segment to expand
  
#### Actual Behavior:

  * What happened?
See screenshot attached
![stravabug](https://user-images.githubusercontent.com/61333337/75075673-7e211d00-5552-11ea-9b52-26532947fb58.png)

#### Expected Behavior:

The large red block to the left of the top 10 is covering segment data such as maximum power and heartrate
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by dabdab825** [comment]
Same issue here

**Comment by tomglynch** [comment]
Issue fixed and now to be closed.

**Comment by shaunginsbourg** [comment]
Thanks Tom. I really love this extension, it adds a lot of functionality to Strava that as a competitive amateur cyclist I find very useful


Shaun Ginsbourg
Barrister
 
(+613) 9225 6444 | F 9225 6464 | 0403 584 918
 
Owen Dixon Chambers
Room 707 East | 205 William St | MELBOURNE
 
Mail to –
Clerk Holmes | 555 Lonsdale St | MELBOURNE VIC 3000 | DX 88 MELBOURNE
 
Liability limited by a scheme approved under Professional Standards Legislation.
 
PRIVACY STATEMENT
 
This e-mail and its attachments are intended only for use by its named recipients.  If you are not the intended recipient please notify the sender, delete all copies, and do not use, store or distribute any information contained in the email or its attachments.
