### ISSUE TITLE
Sync doesn't resume when syncing for the first time

### ISSUE THREAD

**Issue by sup3rfly** [thomaschampagne/elevate#924]
### Step 2: Describe your environment

  * Plugin version: 6.16.0 Stable (Mac & Windows 10)
  * Chrome version:  79.0.3945.130 (Mac & Windows 10)
  * OS version: OsX Mojave v10.14.6, Windows 10
  
### Step 3: Describe the problem:
When having a lot of activities in Strava (> 2000 activities) sync stops (after reaching quota, as expected) but it doesn't resume the sync.

#### Steps to reproduce:

  1. Installed the plugin
  2. Logged into Strava
  3. Started syncing the activities from Elevate
  4. Wait for the sync to finish
  
#### Actual Behavior:

  * What happened?
     3. The activities sync partially. I have more than 2200 activities to sync.
     4. Even If I wait for many hours after the sync stops, the sync doesn't resume.
    When I click on Continue sync (after some time it gets blocked) it starts from scratch.

 
     * Do you have javascript errors logs in browser console?

  > Here is a snippet of the console errors that I have

![image](https://user-images.githubusercontent.com/7603392/75331742-ec841900-588b-11ea-9683-d72bf5e6258a.png)

  
#### Expected Behaviour:

  * What did you expect to happen?
   - Ability to save locally the already synced activities. I cannot continue the sync afterwards. And it doesn't start automatically. 
   - I changed the computer's settings (Mac and windows PC) to not go into sleep mode and waited 24 hrs (repeated this 2 times). It get's stuck at 1760/2222 activities.
   - When I click on Continue sync (after some time) it starts from scratch. I would expect it should remember all the data (local storage) downloaded and resume from there.

  
#### Media attachement:

>You can upload/attach any images to this ticket.
Here is an example where the sync stopped earlier:

![image](https://user-images.githubusercontent.com/7603392/75179555-ffd79d00-5742-11ea-8541-6e6763381cf6.png)

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by JonDunsdon** [comment]
I have exactly the same issue.
@sup3rfly Did you ever find a workaround?
Thanks!

**Comment by ihleonard** [comment]
I'm having the same issue, consistently stuck at 91% of my 1496 activities when trying to sync for the first time (usually gets through 600 the first sync, second sync will start from there and gets to 12xx, third will start over again)
