### ISSUE TITLE
First sync does not starting

### ISSUE THREAD

**Issue by Mikola17** [thomaschampagne/elevate#934]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

* Plugin version: 6.11.0 Stable
* Angular Core version: 7.2.11
* Angular Material version: 7.3.6
* D3js version: 5.9.2 
** Firefox 74.0 (64-bit)

### Step 3: Describe the problem:
1rs sync does not starting

#### Steps to reproduce:
1. Opne plugin page
2. Click "Activities not synced"
3. Skip notification by press "start sync"

  
#### Actual Behavior:

Firefox open new read-only window with strava. Where no information about sync process

#### Media attachement:

>You can upload/attach any images to this ticket.
![2020-03-23 15_50_34-Elevate App](https://user-images.githubusercontent.com/17745177/77318474-2e36a100-6d1e-11ea-88d0-493826eab9fd.png)

**Comment by paenorcer** [comment]
I have the same issue... The pop-up window shows the following message for various days... 
![elevate](https://user-images.githubusercontent.com/63760645/79403569-7455ec00-7fce-11ea-83d2-ca499ced2488.png)

**Comment by Mikola17** [comment]
It does not started on Chrome too
