### ISSUE TITLE
[Feature request] Different values for indoor and outdoor FTP

### ISSUE THREAD

**Issue by LostHunter** [thomaschampagne/elevate#935]
Entering different values for indoor FTP and outdoor FTP. These two values often differ a little (some say the difference could be as big as 30-40W). Currently you need to create new athlete settings record each time you change from outdoor to indoor and back. It would be very handy if there were two separate fields for these two just like there are fields for swimming ftp, running ftp etc.

**Comment by TRIWOLF79** [comment]
+1 It would be great.
