### ISSUE TITLE
Fitness trend: Chronic Intensity Load

### ISSUE THREAD

**Issue by TRIWOLF79** [thomaschampagne/elevate#936]
Hi,

Would it be possible to roll out in the fitness trend another feature that is becoming more popular and useful like the Chronic Intensity Load (CIL)?  
It would be great to implement the CTL metric with that one, and be able to have access to both, compare, and so on.

Thanks.

**Comment by nyedid** [comment]
I would like to add an additional request for this. 

[Here is a link detailing how CIL is calculated. ](https://www.trainingpeaks.com/blog/chronic-intensity-load-a-new-measure-of-training-load-based-on-intensity-factor/)

The formula is: 
CIL = [(1000* Todays IF) * (1-e^(-1/42)] + {Yesterdays CIL * (e^(-1/42)]

Where IF is intensity factor. Elevate must be calculating IF somewhere as IF is a function of normalized power and FTP. Provided a user has entered their FTP, Elevate should be able to calculate IF, which would allow the calculation of CIL from those values.

**Comment by nyedid** [comment]
I've also added [issue 962](https://github.com/thomaschampagne/elevate/issues/962) to display Intensity Factor.

**Comment by csmith1210** [comment]
This would be around the same difficulty to implement as the Ramp Rate figure I've already added. However an issue that would need to be decided would be the pseudo-name for CIL. Since it's basically Fitness but using intensity to calculate versus stress, what would you call CIL?

"Fitness, Chronic Intensity Load, Fatigue, Form" doesn't look to nice 😜

**Comment by nyedid** [comment]
> This would be around the same difficulty to implement as the Ramp Rate figure I've already added. However an issue that would need to be decided would be the pseudo-name for CIL. Since it's basically Fitness but using intensity to calculate versus stress, what would you call CIL?
> 
> "Fitness, Chronic Intensity Load, Fatigue, Form" doesn't look to nice 😜

This is a really good question. I'm going to do some brainstorming and I'll reread the articles on TrainingPeaks and other places to see how folks describe CIL and see if I can find a pseudo-name that seems reasonable.

**Comment by TRIWOLF79** [comment]
As far as they implement the metrics with this one, and that I know that is what in trainingpeaks is called CIL... I know how is calculated, but I'm not going to do the equation every day, and make my own draw xD, that's the point in suggesting Elevate to add it.

**Comment by nyedid** [comment]
@csmith1210 What about "Strain" as the pseudo-name for CIL? It seems to capture the general concept that it's about how hard the efforts have been rather than their duration. I also think it would be very nice to have this metric displayed as a line on the graph rather than just a numerical value; the idea is to be able to visualize Strain on a time series graph so that the athlete can see the effect of shorter but higher intensity training and note any points of deviation between CIL and CTL (Strain/Fitness). 

@TRIWOLF79 Yes, we agree. That's why we are discussing how to add it in Elevate. :)

**Comment by TRIWOLF79** [comment]
I agree with not only a numerical value, but a graph too. Would be quite helpful (just adding it the same way as the metric fitness, fatigue and forme are displayed right now, a 4th metric).

**Comment by nyedid** [comment]
@TRIWOLF79 how do you feel about Strain as the short name for CIL?

**Comment by TRIWOLF79** [comment]
Could be a valid name, yes.

**Comment by nyedid** [comment]
For @csmith1210, [this link on the user forum](https://forum.intervals.icu/t/chronic-intensity-load/540/7) for Intervals.icu says something intriguing...

> But the advantage of this line of presentation is that the charts would be separate from the current CTL/ATL graph. At the moment, that is an elegant representation of the data, not to be carelessly thrown away. So I conclude that the most appropriate option for such data would be a separate chart of CIL/AIL that parallels the current CTL/ATL chart. This could be either an option offered at the top of the existing page or automatically populating the existing page.

Whether this would be a separate chart in Elevate is a different question, but what intrigues me is the concept of AIL in addition to CIL and how that would allow for a parallel calculation of intensity balance. Essentially exactly like we do for CTL/ATL and TSB but calculating and graphing them for intensity instead. 

In an ideal implementation we could see all six lines (CTL, ATL, TSB; CIL, AIL, and intensity balance) on one chart and be able to toggle them on and off depending on what we're interested in. I'm almost thinking there could be a toggle that allows individual metrics to be graphed or to simply turn on and off the intensity lines on the graph. What do you think?

**Comment by csmith1210** [comment]
Interesting, yes it seems from the original article and that discussion there is some merit in comparing graphs of CTL to CIL. The AIL and intensity balance is also a pretty interesting concept and probably advances Chris Baddick's original idea for CIL as a way for athletes to measure their fitness based on intensity instead of duration, essentially leading into fatigue and form as well from intensity since they are all intertwined. For non tour de France competitors, like us on the Peloton, this would be very useful as most of our workouts are very intense but rather short (30-45mins).

However, what do you think about Chris Baddick's original statement in that blog that:
> Chronic Intensity Load (CIL) is not designed as a replacement for CTL, but simply a useful addition. Athletes and coaches should monitor duration of training carefully, but CIL gives an indicator of how the quality of training is progressing through the season. 

To me this indicates that AIL and intensity balance really shouldn't be a thing. CIL is essentially an additional metric to determine if CTL truly predicts the athlete's fitness.

In any case, how I would envision this, if we were going to implement CIL, AIL, and intensity balance, there would be a toggle next to the already existing ones on Fitness Trend to display those three metrics as a line under Fitness, Fatigue, Form. Then we would change the graph to include a drop down selection of metrics to include and allow the user to choose what is plotted. One issue I foresee is definitely mapping colors to the lines and changing the colors based on theme. Currently, angular-js themes only allow three colors to be set for different themes (how I was able to make a new color for the Ramp Rate), so I'd have to look into how to detect which theme is displayed then set color directly based on that. But that's an issue for way down the line 😀

**Comment by TRIWOLF79** [comment]
> Interesting, yes it seems from the original article and that discussion there is some merit in comparing graphs of CTL to CIL. The AIL and intensity balance is also a pretty interesting concept and probably advances Chris Baddick's original idea for CIL as a way for athletes to measure their fitness based on intensity instead of duration, essentially leading into fatigue and form as well from intensity since they are all intertwined. For non tour de France competitors, like us on the Peloton, this would be very useful as most of our workouts are very intense but rather short (30-45mins).
> 
> However, what do you think about Chris Baddick's original statement in that blog that:
> 
> > Chronic Intensity Load (CIL) is not designed as a replacement for CTL, but simply a useful addition. Athletes and coaches should monitor duration of training carefully, but CIL gives an indicator of how the quality of training is progressing through the season.
> 
> To me this indicates that AIL and intensity balance really shouldn't be a thing. CIL is essentially an additional metric to determine if CTL truly predicts the athlete's fitness.
> 
> In any case, how I would envision this, if we were going to implement CIL, AIL, and intensity balance, there would be a toggle next to the already existing ones on Fitness Trend to display those three metrics as a line under Fitness, Fatigue, Form. Then we would change the graph to include a drop down selection of metrics to include and allow the user to choose what is plotted. One issue I foresee is definitely mapping colors to the lines and changing the colors based on theme. Currently, angular-js themes only allow three colors to be set for different themes (how I was able to make a new color for the Ramp Rate), so I'd have to look into how to detect which theme is displayed then set color directly based on that. But that's an issue for way down the line 😀
> 
> Edit: also Strain does make sense for the CIL metric!

I agree; as I said when I opened this post, the point is to implement it, is "in addition" no "instead of". It would be nice to select what metrics do you want to see, be able to see both and compare  "strain" and "fatigue" (or remove one if you are not interested in). I didn't know about the three colours issue, I hope it's a problem than can be solve. Thanks for the interest and the effort :) (sorry if my English is not perfect in those specific topics, but English it's not my mother tongue).

**Comment by nyedid** [comment]
I hear what you're saying about the AIL and intensity balance, but it also depends on what the data is being used for. The way I see it, for those of us who aren't necessarily training for specific events but also monitoring how exercise affects recovery, sleep, etc, those are useful metrics. In my case, CIL wouldn't tell the whole story if I've been pushing hard on shorter 30-45 minute Peloton rides and my sleep quality falls apart. But AIL and intensity balance might help determine if I've pushed past my current recovery capability on a microcycle (weekly, let's say) basis and that I may want to attend to other forms of stress, prioritize some extra rest for a day or so, etc. I know in my case I track my sleep, heart rate variability, RHR, and other recovery metrics via an Oura ring, and the combination of that data with the CIL/AIL/intensity balance would be a hugely useful way to understand that relationship. My sense is that Chris Baddick and others are more focused on performance than recovery, and also focused on long-term change. That makes perfect sense for athletes training for major events. But for those of us who are training primarily for health/fitness and not necessarily looking for peak performance for a given event, managing recovery and understanding the relationships between intensity and subjective experiences of wellbeing, how hard a given workout feels (the "heavy legs" days we all know), etc has real value. 

What are your thoughts? 

Implementation-wise, that's an interesting challenge with regard to the colors and how angular-js themes limit that.

**Comment by TRIWOLF79** [comment]
> I hear what you're saying about the AIL and intensity balance, but it also depends on what the data is being used for. The way I see it, for those of us who aren't necessarily training for specific events but also monitoring how exercise affects recovery, sleep, etc, those are useful metrics. In my case, CIL wouldn't tell the whole story if I've been pushing hard on shorter 30-45 minute Peloton rides and my sleep quality falls apart. But AIL and intensity balance might help determine if I've pushed past my current recovery capability on a microcycle (weekly, let's say) basis and that I may want to attend to other forms of stress, prioritize some extra rest for a day or so, etc. I know in my case I track my sleep, heart rate variability, RHR, and other recovery metrics via an Oura ring, and the combination of that data with the CIL/AIL/intensity balance would be a hugely useful way to understand that relationship. My sense is that Chris Baddick and others are more focused on performance than recovery, and also focused on long-term change. That makes perfect sense for athletes training for major events. But for those of us who are training primarily for health/fitness and not necessarily looking for peak performance for a given event, managing recovery and understanding the relationships between intensity and subjective experiences of wellbeing, how hard a given workout feels (the "heavy legs" days we all know), etc has real value.
> 
> What are your thoughts?
> 
> Implementation-wise, that's an interesting challenge with regard to the colors and how angular-js themes limit that.
It sounds quite interesting, but not everyone has access to an accurate HRV monitor, accurate sleep hours measurement, and so on (I emphasize the word "accurate"). And to add everyone of them would look like a total kaos xD In my case, I train for (or try to) "major events". And yes, it is more about peformance on the long haul that is what you can track easily. CIL topic appeared in our training group when we were locked down (hard lockdown) 2 months ago, and suddenly, overnight, our training volume was reduced drastically; it felt quite frustrating to see as our "fatigue" was descending so quickly, no matter how hard you trained in the turbo; and CIL seemed to answer to that problem, as it track intensity over volume, and in those cases when you can only do hard but short sessions it feels more realistic.

**Comment by nyedid** [comment]
> It sounds quite interesting, but not everyone has access to an accurate HRV monitor, accurate sleep hours measurement, and so on (I emphasize the word "accurate"). And to add everyone of them would look like a total kaos xD In my case, I train for (or try to) "major events". And yes, it is more about peformance on the long haul that is what you can track easily. CIL topic appeared in our training group when we were locked down (hard lockdown) 2 months ago, and suddenly, overnight, our training volume was reduced drastically; it felt quite frustrating to see as our "fatigue" was descending so quickly, no matter how hard you trained in the turbo; and CIL seemed to answer to that problem, as it track intensity over volume, and in those cases when you can only do hard but short sessions it feels more realistic.

I'm not talking about adding those to Elevate. I'm talking about having CIL/AIL in Elevate so I can easily see what my intensity load has been over the short and longer term. That's it.
