### ISSUE TITLE
Leaderboard is not updating for hours and hours

### ISSUE THREAD

**Issue by brennanmorrow** [thomaschampagne/elevate#945]
### Step 1: Are you in the right place?

Yes no other bugs I could find reported

### Step 2: Describe your environment

 4 devices, chrome, android Iphone. 
Problem is universal
### Step 3: Describe the problem:

Leaderboard to segments is significantly delayed. ( by 6hrs or more reported by a team mate) 
Problem, we and one other group our hold social distancing friend races used strava to be our time machine. The leaderboard allows for people to see where they are sitting in the race. 
I am sure our community is no the only one. 

#### Steps to reproduce:

1. record a ride or run that is better than the previous run. 
2. see that the activity did not populate the leader board. 
  
Attached is a screenshot of the issue from the chrome browser. 
https://drive.google.com/file/d/1B10Ye--CTPHilSfCYFwQZ4Q8YxFX7lBW/view?usp=sharing

**Comment by davidho95** [comment]
This appears to be a bug in Strava, not Elevate. Maybe try https://support.strava.com/hc/en-us?

**Comment by brennanmorrow** [comment]
Thanks I realise latter that this was the wrong forum.
thanks for the response.

Brennan Morrow
<https://solarlightinc.com/>
541.306.4141 office
541.390.5976 cell
Brennan@SolatubeBend.com
<Brennan@SolatubeBend.com>
CCB#207440
