### ISSUE TITLE
Not syncing at all

### ISSUE THREAD

**Issue by DanielKnabl** [thomaschampagne/elevate#952]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

Plugin version: 6.16.1 Stable
Angular Core version: 8.2.14
Angular Material version: 8.2.3
D3js version: 5.15.0
Chrome: 81.0.4044.129 (Official Build) (64-bit) (cohort: 81_Win_129)
Windows 10: 1909 Build: 18363.815
  
### Step 3: Describe the problem:
Not syncing initially/at all.

#### Steps to reproduce:

Open Elevate for Stravaand click
"Activities"
"Activities not synced"
"Sync"
"Start Sync"
  
#### Actual Behavior:

  * What happened?
Only Strava Dashboard appears, nothing else happens.

  * Do you have javascript errors logs in browser console?
  ```javascript
...
Uncaught TypeError: Strava.Maps.mapFactory is not a constructor
    at e.renderMap (ftue_manifest-a54f0d3642ba688fc322cb455d2f1f4a5e11d7db1445802db292c0ef9c3abbf3.js:1)
    at HTMLDocument.<anonymous> (onboarding:1613)
    at i (eval at n.exports (addScript.js:20), <anonymous>:1352:16)
    at Object.fireWith [as resolveWith] (eval at n.exports (addScript.js:20), <anonymous>:1394:85)
    at Function.ready (eval at n.exports (addScript.js:20), <anonymous>:1474:102)
    at HTMLDocument.J (eval at n.exports (addScript.js:20), <anonymous>:1479:87)
boot.bundle.js:59 No previous sync found. A first sync must be performed
...
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
I wanted to sync my first run from Strava to the Elevate App.

#### Media attachement:
n/a

**Comment by DanielKnabl** [comment]
The pop-up window shows the following address:

https://www.strava.com/onboarding

**Comment by choochoocherry** [comment]
I'm having this same exact issue and just wanted to add that the the pop-up window shows the following URL when I click on the sync button 
https://www.strava.com/dashboard?elevateSync=true&fastSync=false&forceSync=true&sourceTabId=35 
before it goes to https://www.strava.com/onboarding

**Comment by csmith1210** [comment]
Are these new Strava accounts per chance? Really would need more details to help.

If you could try again, in the browser console change the level of output to include verbose like in the attached screenshot. This can help track what's being done before the error.

![](https://i.imgur.com/YYFhKVK.png)

**Comment by DanielKnabl** [comment]
I tried to sync on another computer in the meantime and now I can sync on any computer without any problem. To answer your question: yes, my strava account was a completely new one. I had one single activity synced from polar flow. From my perspective, this issue can be considered obsolete/solved.Thanks, best Daniel 
null

**Comment by choochoocherry** [comment]
Hi, I tried clearing cookies, using a different browser, and a number of other things that didn’t work, but then a few hours later, I tried again on the same computer/browser, and it worked. Mine was also a new account that had nothing previously synced. It’s resolved for me now, I appreciate your help! Cindy

**Comment by csmith1210** [comment]
Yeah, I'd assume the new accounts might have contributed to this a bit. There were also sync issues reported in the past so it doesn't surprise me it started working after a couple of hours.

**Comment by IIIII155** [comment]
I'll try you tips and another computer see if it's just my chromebook that's playing up. I've removed elevate and going to reinstall add on, start from scratch.

**Comment by csmith1210** [comment]
Just another tip as well @IIIII155 that I noticed when I made my wife a Strava account. The mention of an “onboarding” url above is interesting because it wasn’t until about the second time I logged into her new account on the actual website (not the phone app) that Strava presented all of their TOS/Privacy Policy/Heart Health Data agreements that you have to agree to. I don’t know if that makes a difference, but just another thought.
