### ISSUE TITLE
PSS is Calculating Differently in Activities and Fitness Trend for Same Ride

### ISSUE THREAD

**Issue by nyedid** [thomaschampagne/elevate#961]
* Plugin version: 6.16.1
  * Chrome/Opera/Chromium version: 81.0.4044.138
  * OS version: Mac OS 10.15.4
  
Step 3: Describe the problem:

- Elevate is calculating Power Stress Score differently in two different places for the same ride. The differences are minor but it is odd that the same event is being calculated in two different ways apparently. 
- In the images below, Strava has the higher value logged when I am in the Strava dashboard. 
- Elevate is showing the same value as Strava in the Activities view. 
- However, in the Fitness Trend and Fitness Analysis table, the value is showing as one digit fewer than in Activities. 
  
#### Actual Behavior:

  * What happened?
    * Elevate is showing a different value for PSS in the same ride in different places. See above for description. 
  * Do you have javascript errors logs in browser console? 
     * No, there are no errors in the console. 
  > Press F12 to see developer console and javascript logs

  ```javascript
A cookie associated with a cross-site resource at https://medium.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
index.html#/newAppInProgress:1 A cookie associated with a cross-site resource at http://medium.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
main-es2015.1824aa76391995b470ba.js:1 checking athlete settings consistency
main-es2015.1824aa76391995b470ba.js:1 Athlete settings consistent: true
8-es2015.0c0e69cf740f5bffa33a.js:1 FitnessTrend component initialized
8-es2015.0c0e69cf740f5bffa33a.js:1 Graph update time: 139 ms.
8-es2015.0c0e69cf740f5bffa33a.js:1 FitnessTrend component initialized
8-es2015.0c0e69cf740f5bffa33a.js:1 Graph update time: 144 ms.
8-es2015.0c0e69cf740f5bffa33a.js:1 FitnessTrend component initialized
8-es2015.0c0e69cf740f5bffa33a.js:1 Graph update time: 119 ms.
8-es2015.0c0e69cf740f5bffa33a.js:1 Graph update time: 36 ms.  
```
  
#### Expected Behavior:

  * I expected the PSS value would be the same across Elevate regardless of where in the platform I'm looking. 
  
#### Media attachement:

**Fitness Analysis Table**
![Screen Shot 2020-05-15 at 10 05 46 AM](https://user-images.githubusercontent.com/9094699/82086411-58b03500-96a3-11ea-90bc-26abf9a29690.jpg)

**Fitness Trend Chart rollover**
![Screen Shot 2020-05-15 at 10 04 55 AM](https://user-images.githubusercontent.com/9094699/82086415-5948cb80-96a3-11ea-9f44-33ef2ec4e842.jpg)

**Activities View**
![Screen Shot 2020-05-15 at 10 04 38 AM](https://user-images.githubusercontent.com/9094699/82086418-59e16200-96a3-11ea-8d1d-3633fe6c8fd9.jpg)

**Comment by csmith1210** [comment]
I've looked into this. This has to do with how the data is outputted. The Fitness Trend page has a function to call to print stress scores that will floor() the score before displaying it. The activities table just spits out the data and I believe some global table definition rounds to whole numbers. I believe the discrepancy will happen if your PSS is between xx.500001-xx.999999. For instance one of my ride's stress scores is 77.59710417076332, so it's 78 on the Activities page and 77 on the Fitness Trend page.

I'll look into how the activities table is set up for rounding to see about fixing it.

**Comment by nyedid** [comment]
@csmith1210 many thanks, makes sense that there's a rounding function somewhere!

**Comment by nyedid** [comment]
@csmith1210 Assuming we have to wait until a new version drops for some of these fixes/changes, any idea how to accelerate that new release? I believe I'm on the newest version of Elevate and it doesn't look like there have been updates for a while, so I'm assuming a bunch of changes will go in at the same time on an upcoming update.

**Comment by csmith1210** [comment]
@nyedid I have a branch that I've been maintaining [csmith1210/elevate/development](https://github.com/csmith1210/elevate/commits/development) and keeping up to date with the latest pull requests people have been submitting. I've published a [package](https://github.com/csmith1210/elevate/releases/tag/v1.16.1.1) of the latest build that you can install and use yourself. You'll have to enable developer tools on chrome://extensions and then click Load Unpacked then choose the directory of the unzipped files.

**Comment by nyedid** [comment]
@csmith1210 I really appreciate it, I have your branch installed and it just needs to sync later as I think I hit the rate limit on Strava. Thanks so much for maintaining this! 

I hope @thomaschampagne will be able to release a Mac OS version of the app as otherwise I'll need to continue using the extension until then. Fortunately the current one works well enough and your updates will offer some huge enhancements as well.
