### ISSUE TITLE
"Your GPX file is (being) dropped in your download folder..." not downloading anything

### ISSUE THREAD

**Issue by jembow** [thomaschampagne/elevate#964]
Hello - I'm trying to download a segment using the "Export GPS segment effort". Whether i choose GPX or TCX the "Your GPX file is (being) dropped in your download folder..." window pops up & nothing happens. checked my downloads folder too and nothing is there.

Windows 10 Pro & Chrome Version 81.0.4044.138 (Official Build) (64-bit)

Thanks!

**Comment by andyhollis** [comment]
I also have this issue. Anyone have an idea how to fix?

**Comment by thomaschampagne** [comment]
Linked to https://github.com/thomaschampagne/elevate/issues/939 fix incomming

**Comment by thomaschampagne** [comment]
Fixed for next release
