### ISSUE TITLE
Using Elevate results into "Too Many Requests" Error page

### ISSUE THREAD

**Issue by gtom84** [thomaschampagne/elevate#968]
Following the restriction of Strava Leaderboards API I very often got "Too Many Requests" restricting all Strava access for 15 - 30 minutes.

I don't get this error page navigating through Strava, only on Activity details viewing Segment times where time differences between current and "All time PR" and "This year PR" are shown. Maybe it depends on number of segments on an activity.

**Comment by vk2him** [comment]
I had this issue as well - it seems to be an affect of Strava's recent change to reduce features for free users where they have reduced the number of API calls (this wasn't documented anywhere that I could see). The issue went away when I signed up for the free 60 day trial ....

**Comment by gtom84** [comment]
Would it possible to add API call limit on plugin site to prevent
overloading the limit on Strava site so free users can still use the plugin?

**Comment by compmaster** [comment]
It seems that Elevate sends inifinite number of requests trying to get segment efforts.

**Comment by nkonovski** [comment]
Same here, today my strava subscription expire and just open it to check how it look for free users so I get 'Too many request' after refresh a activity, but first I note that 2 segments try to load differences with KOM and my PB unsuccessfully (loader is in progress). So assume they are generated too many requests (Strava limit - 150 per 15min 1000 per day).

So i agree with @gtom84 that the app need a limit of API calls.

**Comment by brettgoss** [comment]
It looks like the segment effort requests aren't actually going through Strava's API, so there isn't any information being returned about approaching the rate limit before it's hit. The API requests have `X-RateLimit-Usage` and `X-RateLimit-Limit` response headers, but those don't seem to be included with non-API requests.

Assuming the rate limits are the same as the API, I'm not sure how this could be avoided apart from switching from making the segment effort requests on scroll and instead maybe adding a button to 'Load Elevate Segment Efforts'?

**Comment by NordieBoy** [comment]
Still happening...
