### ISSUE TITLE
"Show extended statistics of effort" not working

### ISSUE THREAD

**Issue by MrModenait** [thomaschampagne/elevate#969]
### Step 2: Describe your environment

  * Plugin version: 6.16.1
  * Chrome/Opera/Chromium version: 83.0.4103.61
  * OS version: Windows 10 Home version 1903
  
### Step 3: Describe the problem:

Although I can view extended statistics for a ride, the button for viewing extended statistics for a segment gives no response when clicked upon.
  
#### Actual Behavior:

The error I can read from the Console log is: "GET https://www.strava.com/segment_efforts/2700071620776468000 boot.bundle.js:25 404."
  
#### Expected Behavior:

I expected to see a pop-up to see the analysis of my segment effort.
  
As suggested in Pull requests #957, the origin of the problem seems to be the fact that the ID number for segment efforts has now become longer and longer, and the last three integers are rounded to "0" by the elevate app's code, hence creating a 404 error when the app attempts to fetch the data from the faulty URL. Could this be solved?

**Comment by shaunginsbourg** [comment]
Could this please be fixed. It was reported two months ago and not fixed:

https://github.com/thomaschampagne/elevate/issues/939

It is probably about the most useful feature of elevate and it is a real shame that it is not working.

Thanks.

**Comment by thomaschampagne** [comment]
Fixed for next release
