### ISSUE TITLE
Sync no longer possible

### ISSUE THREAD

**Issue by Grimpeur168** [thomaschampagne/elevate#970]
I have been using Elevate on Chrome successfully for the past fortnight. However the last four time that I have tried to sync my recent activities, over four days i have been unable to sync anything and when I try I get the following:

  
![Screen Shot 2020-06-04 at 20 26 31](https://user-images.githubusercontent.com/66436256/83791466-8553dd00-a6a2-11ea-9a2a-2dbe3beba9cb.png)

What can I do to re-enable sync as when I come back after 4 hours I get the same message.

**Comment by thenoseknowz** [comment]
I am having the same problems. Was doing my first sync and 1500 entries but stopped at 1320. Even waited overnight but keep coming up with the same error.

**Comment by JonDunsdon** [comment]
i have the same problem, and currently it seems to completely restart on each refresh. So i only ever get the first 160 to 420 activities sync'd :(
Any hints on how to work around this would be very welcome!

**Comment by piaseq** [comment]
Same problem here. It looks like Elevate is trying to download all activities from Strava and exceeds quota. With 2000+ entries it will be impossible to sync Strava account with the app... There should be a mechanism, which would resume syncing where it ended. Or at least resume syncing from the point where last backup ended...

**Comment by drumphil9901** [comment]
same problem here - and strava itself is impacted (can't display parts of strava activities) on chrome and other browsers that don't have elevate installed
