### ISSUE TITLE
Bad Swim Data throwing out Fitness Trend

### ISSUE THREAD

**Issue by A1Dan75** [thomaschampagne/elevate#973]
Hi,

Due to my watch being rubbish at tracking swimming, it over-stated this afternoon's distance by nearly 100%.  This results in a ridiculously fast swim, giving me a huge SwimSS, and sending my fitness and fatigue readings flying, as oyu can see in this image:
![image](https://user-images.githubusercontent.com/24933894/85447720-d7936a00-b58d-11ea-8787-bf7f4d7fac3e.png)

I can't work out any way to edit the distance in Strava, or exclude the swim from Elevate.  Is my only option to delete it from Strava?

Thanks

Aidan

**Comment by thomaschampagne** [comment]
Are you able to fix the GPS file by hand? If so, indeed delete it and upload it back.

**Comment by A1Dan75** [comment]
I could do but probably more hassle than it's worth, can just delete and put a manual entry in instead I guess.
