### ISSUE TITLE
Detailed analysis of segment leaderboard not showing

### ISSUE THREAD

**Issue by wijmaar** [thomaschampagne/elevate#976]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.16.2
  * Chrome/Opera/Chromium version: 83.0.4103.116
  * OS version: MacOS Catalina 10.15.5
  
#### Steps to reproduce:

  1. Log-in to Strava
  2. Open activity
  3. Scroll down segment overview
  
#### Actual Behavior:

  * What happened?

The leaderboard was shown without the segment analysis. 

![Screenshot 2020-07-06 at 09 36 59](https://user-images.githubusercontent.com/7959006/86569930-7301e300-bf6f-11ea-9286-c64d1f039c0a.png)

  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
  ```
  
#### Expected Behavior:

  * What did you expect to happen?

I expected to see the segment overview including the segment details provided by Elevate (e.g. Position in leaderboard). 

![Elevate_for_Strava_Segment_Analysis-800x509](https://user-images.githubusercontent.com/7959006/86569952-7b5a1e00-bf6f-11ea-9bd4-cc6fb7c1583d.png)

#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by dave-n-wilson** [comment]
FYI the defaults have changed in the latest release in Global Settings theres an "Activity Viewing Options" group if you enable the "Enabled Segment Time" options (i tihnk theres 4 or 5 of them) the splits should reappear.

**Comment by JackJudd** [comment]
> FYI the defaults have changed in the latest release in Global Settings theres an "Activity Viewing Options" group if you enable the "Enabled Segment Time" options (i tihnk theres 4 or 5 of them) the splits should reappear.

Been wondering this myself for a while, seems like a few other people have too. Thanks!
