### ISSUE TITLE
Final stress: when it is picking up HRSS or PSS

### ISSUE THREAD

**Issue by jorgejuanaparicio** [thomaschampagne/elevate#982]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.16.2 Stable
  * Chrome/Opera/Chromium version: 84.0.4147.89
  * OS version: Windows 10
  
### Step 3: Describe the problem:

Sometimes the Final Stress score is coming from HRSS or from PSS and I would like to understand which is the criteria to take one or the other as it is no explained in the documentation.
Does the system pick up HRSS when PSS is estimated even though is a higher number for certain activity?
How the system chooses which one is the "good" one to add into final stress score?

#### Steps to reproduce:

  1. Enter in fitness trend
  2. Go down to Fitness analysis table
  3. Check numbers in HRSS, PSS, etc.
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.
![2020-07-21 14_16_22-Window](https://user-images.githubusercontent.com/48485071/88053960-e8b7a280-cb5c-11ea-9c86-39d3f49eb074.jpg)

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by varanasib** [comment]
I'd like to know how this works, too.
