### ISSUE TITLE
Sync recent activities truncates data

### ISSUE THREAD

**Issue by finchr** [thomaschampagne/elevate#988]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.16.2
  * Chrome/Opera/Chromium version: Version 84.0.4147.89 (Official Build) (64-bit)
  * OS version: Mac OS 10.14.6 (18G6020)
  
### Step 3: Describe the problem:
When I 'Sync recent activities' it truncates all activities prior to July 15, 2020. I tried restoring from a backup and they running another sync and I get the same result.
#### Steps to reproduce:

  1. Click `Sync recent actvities` button
  2. When sync finishes validate there is no data prior to 7/15/2020.
  3. 
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
onloadwff.js:71 Assertion failed: Input argument is not an HTMLInputElement
getFormProfile @ onloadwff.js:71
  ```
  
#### Expected Behavior:

  * New activities would show up without deleting the older ones.
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here. 
[backups.zip](https://github.com/thomaschampagne/elevate/files/4990717/backups.zip)

**Comment by ddddavidee** [comment]
same here. 
I got only "last month" (or so) of activities
